### ISSUE TITLE
Need a logo!

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stampit#102]
Let's get creative. Drop you logo ideas here!

## UPD: Logo submissions have ended. Please proceed to this poll, leave your opinion: https://gist.github.com/koresar/aca0ca81edc34f58462c

**Comment by koresar** [comment]
@troutowicz proposed a stamp-like logo. This is an example (which should not be used due to copyrights obviously): 
![stampit example](http://www.stampitcanada.com/images/LogoImage.png)

**Comment by ericelliott** [comment]
:+1:

**Comment by elitenomad** [comment]
![stampit](https://cloud.githubusercontent.com/assets/1140447/8129765/c1cd5d4e-114f-11e5-922d-ab5b60c138f2.png)
(Learnt to use another Software Sketch 3 :+1: )

**Comment by koresar** [comment]
@elitenomad Hey, mate! Good evening. :)
Great work!

**Comment by unstoppablecarl** [comment]
![stampit-logo](https://cloud.githubusercontent.com/assets/913047/8131233/e826025c-10e6-11e5-96ea-a1a4021131b0.png)

Just a general concept. Font and details need to be refined.

**Comment by koresar** [comment]
@unstoppablecarl it looks like another handlebars-like module. :)

**Comment by unstoppablecarl** [comment]
![stampit-logo](https://cloud.githubusercontent.com/assets/913047/8131838/1b163cbe-10eb-11e5-8096-1ee22c99fd95.png)

Just came up with this one. Font is Open sans. I fine tuned the spacing and weight. Not sure about colors but I think it works well.

**Comment by koresar** [comment]
Can I ask why you put braces? Why not stamps? :)

**Comment by unstoppablecarl** [comment]
What do you mean?

**Comment by koresar** [comment]
In JS world the braces are usually associated with Handlebars or Mustache frameworks.

As long as we are creating stamps here it would be pretty logical to see stamp-like logo. See two examples above.

I cannot understand the logic behind your artwork. Sorry.

**Comment by unstoppablecarl** [comment]
What do you mean by stamp-like?

**Comment by koresar** [comment]
Stamp is the real physical thing. People use it to put special marks on paper.
[See images](https://www.google.com.au/search?q=stamp&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMIh-jo-a6KxgIVg6u8Ch0S-gCD&biw=1440&bih=728)

**Comment by unstoppablecarl** [comment]
I think making it an actual stamp is boring and generic.

**Comment by koresar** [comment]
Well, I've seen plenty of JS modules with braces on their logos. I haven't seen any which represent stamp. :)

Moreover, a picture of stamp would be highly recognisable alongside the other JS modules.

**Comment by unstoppablecarl** [comment]
These are good points. What do you think about a postage stamp?

**Comment by koresar** [comment]
Postage stamp is okay, but it's not meant to be reproducible. Ink stamps are designed to be multiplied. :)

**Comment by troutowicz** [comment]
It should be a classic stamp, with a sort of cartoonish look. The rubber lettering on the bottom of the stamp should spell "stampit". The rubber should have some color, as if it was just used. Here is an example.

![stamp](http://intlimg.demandmedia.com/DM-Resize/photos.demandstudios.com/184/47/fotolia_1458344_XS.jpg?w=400&h=200&keep_ratio=1)

**Comment by ericelliott** [comment]
I think we should keep an open mind. @unstoppablecarl I did like the typeography and color choices.

I do like the idea of basing the logo on a rubber stamp, but let's not shoot any ideas down at this stage. Let's just see what people come up with and make decisions later. =)

**Comment by NinjaGrisen** [comment]
A lot of talk about a stamp inspired logo so gave it a try, can change it up if I get some feedback.
![stampit](https://cloud.githubusercontent.com/assets/5888150/8138870/06cedebe-114f-11e5-806e-88b4e629a16a.png)

**Comment by troutowicz** [comment]
@NinjaGrisen I like that! Can I see what it would look like if you replaced "Open Source" with "Composable Factories"  and made "IT" lowercase?

**Comment by NinjaGrisen** [comment]
There we go, some simple text changes. Is there anything else like more/less details, another texture or no texture at all, colors and so on give me a shout 
![stampit](https://cloud.githubusercontent.com/assets/5888150/8140613/81352f42-115d-11e5-8451-0c7fbb54e3a2.png)

**Comment by MarkAurel** [comment]
![Stampit Composable Factories - MarkAurel](https://dl.dropboxusercontent.com/u/65373380/Stampit.jpg)

**Comment by ericelliott** [comment]
Thanks for these guys! It's starting to get interesting.

@NinjaGrisen  I definitely like the lowercase "it" on the end of Stampit. Love "composable factories". Great tagline!

I like the texture.

@MarkAurel Interesting shape. =) I think I'd prefer a flat design look - it would probably scale and translate better to different design situations.

**Comment by MarkAurel** [comment]
![Stampit Composable Factories - MarkAurel](https://dl.dropboxusercontent.com/u/65373380/Stampit-2.jpg)

**Comment by koresar** [comment]
Thanks @MarkAurel !

One more thing we should keep in mind. Stampit logo will be displayed small in many places (of GitHub at least). Like here: https://github.com/stampit-org
So, probably it would be good if the text is readable when the picture is shrinked.

**Comment by ericelliott** [comment]
At least the "Stampit" part should be legible, yeah. We may want a mini version that's simplified and drops the surrounding text. =)

**Comment by NinjaGrisen** [comment]
Made the text bigger to increase legibility on Stampit. 100x100 px example on the side, one with the surrounding text and one without it. 
![stampit](https://cloud.githubusercontent.com/assets/5888150/8144303/647ff434-11d7-11e5-9f7c-effe531e9c3c.png)

**Comment by koresar** [comment]
That's adorable, @NinjaGrisen !
And also I like your github nickname!

**Comment by NinjaGrisen** [comment]
@koresar Hehe thanks man :>

**Comment by unstoppablecarl** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/913047/8145365/1c7c956a-11d3-11e5-88cb-e0fcc6f52eb9.png)

**Comment by unstoppablecarl** [comment]
![stampit-logo3](https://cloud.githubusercontent.com/assets/913047/8145400/caaba8dc-11d4-11e5-8764-498bef8531b6.png)

**Comment by troutowicz** [comment]
I like that @unstoppablecarl !

**Comment by JosephClay** [comment]
I like the red one
:clap: @unstoppablecarl

**Comment by koresar** [comment]
The red one is simplistic. That's modern. I like it too.

**Comment by ericelliott** [comment]
Nice work @unstoppablecarl!  \o/

:fireworks:

**Comment by marcelopereirascmspain** [comment]
A riff on the ideas of @unstoppablecarl and an attempt to incorporate the aesthetics of korean stamp seals - https://en.wikipedia.org/wiki/Seal_(East_Asia)

![text4186](https://cloud.githubusercontent.com/assets/9739738/8147598/4c931cf6-1273-11e5-9a94-ac9b19d1a425.png)

**Comment by troutowicz** [comment]
Creative, I like it!

**Comment by elrumordelaluz** [comment]
![stamp-it](https://cloud.githubusercontent.com/assets/784056/8150612/7b5569f4-12f0-11e5-8c45-0c02ce23728c.jpg)

**Comment by elrumordelaluz** [comment]
+ variations
![sit-variations](https://cloud.githubusercontent.com/assets/784056/8150632/23345d4c-12f1-11e5-821d-89ecc6e01e43.jpg)

**Comment by troutowicz** [comment]
@elrumordelaluz I like your color choices. Do you have any designs in mind that relate to a stamp? I don't really see the relationship of brackets with stamps.

**Comment by elrumordelaluz** [comment]
+ variations 
![sit-variations](https://cloud.githubusercontent.com/assets/784056/8150643/d855f960-12f1-11e5-971b-4fd6c68ebdee.jpg)

**Comment by elrumordelaluz** [comment]
@troutowicz the initial idea is `{` + `some baseline` = `{⃒` , graphic synthesis of rubber stamp

**Comment by troutowicz** [comment]
Keep up the imaginative ideas, these are looking great so far.

**Comment by mjmcclain** [comment]
Stamp logo, over the top of braces. Just using a rubber stamp is too literal.

**Comment by koresar** [comment]
> Just using a rubber stamp is too literal.

That's exactly what we need! Explicit, obvious association. We don't want people confuse stampit with a templating module like handlebars or mustache.

**Comment by mjmcclain** [comment]
I said, "literal." When something is too literal, it can be very generic. By combining the two: braces and a stamp over it (X'ing it out) then you add a layer of meaning.

**Comment by mjmcclain** [comment]
I said, "literal." When something is too literal, it can be very generic. By combining the two: braces and a stamp over it (X'ing it out) then you add a layer of meaning.

**Comment by yeeyang** [comment]
@marcelopereirascmspain Reminds me of Jade's logo with the red box
![image](https://cloud.githubusercontent.com/assets/1013506/8152365/0d560f18-12ea-11e5-9a8d-c260a7e1dc78.png)

**Comment by nkbt** [comment]
Stampit is about composition, so let's compose some post stamps

![idea](https://lh3.googleusercontent.com/nHOTJ1xpZcYV6QMCLPwDs3QJcAzfuKNGeUbgFnmADfY=w481-h400-no)

**Comment by PhiLhoSoft** [comment]
[**@NinjaGrisen**](https://github.com/NinjaGrisen) commented on [12 juin 2015 22:05 UTC+2](https://github.com/stampit-org/stampit/issues/102#issuecomment-111600554 "2015-06-12T20:05:01Z"):
> [![stampit](https://cloud.githubusercontent.com/assets/5888150/8138870/06cedebe-114f-11e5-806e-88b4e629a16a.png)](https://cloud.githubusercontent.com/assets/5888150/8138870/06cedebe-114f-11e5-806e-88b4e629a16a.png)

I always disliked this kind of design (which is classical, I reckon) because I tend to read "Open StampIT Source", ie. I just read from top to bottom. Confusing.

That said, the design is nice, like most propositions here.

**Comment by unstoppablecarl** [comment]
Larger image. I don't know why I uploaded a small one.
![stampit-logo3](https://cloud.githubusercontent.com/assets/913047/8160731/08eb88f8-1340-11e5-8db5-949fcd357c3d.png)

**Comment by PhiLhoSoft** [comment]
Variation on the rubber stamp theme, stamping over the JS logo.
![stampit-logo](https://cloud.githubusercontent.com/assets/1087902/8181518/cdf7a726-1426-11e5-90c5-4692710cbe75.png)

**Comment by PhiLhoSoft** [comment]
A variant, enforcing the idea of stamp (postal & rubber).
![stampit-logo-2](https://cloud.githubusercontent.com/assets/1087902/8182068/cea44404-142b-11e5-8a90-75df5669cfb7.png)

**Comment by koresar** [comment]
@PhiLhoSoft that's clever!

**Comment by PhiLhoSoft** [comment]
[**@koresar**](https://github.com/koresar) commented on [16 juin 2015 15:01 UTC+2](https://github.com/stampit-org/stampit/issues/102#issuecomment-112419404 "2015-06-16T13:01:41Z"):
> [@PhiLhoSoft](https://github.com/PhiLhoSoft) that's clever!

Thanks. I chose simplicity (no "noise" effect) so it can scale better, and can even be readable in B&W.
The design is made with Inkscape, so you can scale it as you want.

JS logo: The MIT License (MIT)
Copyright (c) 2011 Christopher Williams <chris@iterativedesigns.com>, Manuel Strehl <boldewyn@gmail.com>

**Comment by koresar** [comment]
@PhiLhoSoft would you share the Inkscape file?

**Comment by PhiLhoSoft** [comment]
Of course! What is the best way to do this, here?

**Comment by koresar** [comment]
@PhiLhoSoft decide for yourself. :) But there is no way to attach files on GitHub. You can try gist though: https://gist.github.com/

**Comment by PhiLhoSoft** [comment]
Better / simpler: I realised I have lot of SVG files without version control (made a looong time ago...), so I grouped them, and created a Git repository for them.
So now you can find this logo there: https://github.com/PhiLhoSoft/SVG/blob/master/Inkscape/Stampit-logo.svg

**Comment by ericelliott** [comment]
Good idea to add svg in a repo. Do SVGs preview properly in gists?

**Comment by PhiLhoSoft** [comment]
Good question. The simplest way to answer is to try... [Answer is, alas, no.](https://gist.github.com/PhiLhoSoft/e8caebcb078515e3f34f#file-lozenge-svg)

**Comment by ericelliott** [comment]
:frowning:

**Comment by ericelliott** [comment]
How would this one look in green?

![untitled-2](https://cloud.githubusercontent.com/assets/913047/8145365/1c7c956a-11d3-11e5-88cb-e0fcc6f52eb9.png)

**Comment by julienetie** [comment]
Most of these logos are decent, there's a time and place for detailed logo design, too much details & textures can be a little overkill for this scenario IMHO. But also oversimplification can be way too boring for such a simple word.

From a professional POV I would go with unstoppablecarl's 2nd design (in color). 2nd to that MarkAurel's does a nice job. 

Ironically they both have "class" ;)

**Comment by juanmnl** [comment]
Hey there! a little late, but here is a first draft of an idea i had. I think a simplified version will be better, but i had to take it out of my head.
Let me know what you think.
![draft 1](https://cloud.githubusercontent.com/assets/699945/8298336/3982904a-192d-11e5-9f4a-6a1f513fd9c1.png)

Cheers from Ecuador!!

**Comment by koresar** [comment]
So many incredible options!
Let me create a poll later today. :) We'll vote.

**Comment by juanmnl** [comment]
Don't know why i forgot to upload the dark and light versions. Sorry :tongue: 
![line points line points](https://cloud.githubusercontent.com/assets/699945/8309078/036bb2fa-198e-11e5-82b1-71dad1e5ab72.png)
![logo square dark](https://cloud.githubusercontent.com/assets/699945/8309077/036a3e34-198e-11e5-9c4c-a717e158a5d2.png)
![logo square light](https://cloud.githubusercontent.com/assets/699945/8309079/036f1300-198e-11e5-85fb-c6ed5f5fbb7e.png)

**Comment by unstoppablecarl** [comment]
> How would this one look in green?

What kind of green were you thinking?

**Comment by juanmnl** [comment]
As the other one was very complex, i decided to make a simple draft about a stamp with classy montserrat typography.

While the previous one is about what stampit does, this is solely based on the name.
![stampit v2](https://cloud.githubusercontent.com/assets/699945/8322123/0eb63898-19f6-11e5-8d3e-2c9c886765f7.png)

Cheers.

**Comment by nkbt** [comment]
@juanmnl like yours, the only problem stamp shape. It is factually incorrect and should be the other way around. Compare:

![20150624-134259](https://cloud.githubusercontent.com/assets/175264/8322343/02048b14-1a77-11e5-8c55-cfdb98ffbc13.png)

![20150624-134411](https://cloud.githubusercontent.com/assets/175264/8322351/262cfe5e-1a77-11e5-9007-162409e77a3d.png)

**Comment by juanmnl** [comment]
@nkbt I know, i tried to make some random edges, but the asymmetry wasn't good. I tried straight. Wasn't good. It's late and got a bit tired, so i didn't put the best effort on the edges. If you are talking about the broken/teared paper shape at the edges, that will require lots (hundreds, even thousands) of vector points to achieve. If it's about the inversion of the circles, inward instead of outward, that's quickly achievable (and a nice observation).
This is a first draft so everything can be refined or changed. 
Cheers and thanks for the remark :smile:

**Comment by nkbt** [comment]
Nah, very simple shape, it just should be correct. There are heaps of
vector post stamp templates, so you don't need to do it yourself, unless
you really want to.

**Comment by ericelliott** [comment]
Good logos aren't photo-realistic. They're very, very simple. See Nike, Audi, Mercedes, Uber, etc.. We need something that looks great at 100px x 100px that scales well (simple shape vector).

**Comment by julienetie** [comment]
I would love to design a logo for Stampit but, from a realistic POV there's no point as I know after going though lots of crazy ideas I would probably have ended up with something similar to:
![image](https://cloud.githubusercontent.com/assets/7676299/8330787/df7d8d34-1a7b-11e5-90dc-65214eb8c7a8.png)
It's on the same wavelength as:
![image](https://angularjs.org/img/AngularJS-large.png)
Personally I think unstoppablecarl's logo is excellent, but if you're not feeling it, it could be better to let people build off unstoppablecarl's format & font style and maybe just experiment with the {it} symbol. 
(Just a thought)

**Comment by yeeyang** [comment]
Idea that I've been pondering about for a while.

![stampit_logo](https://cloud.githubusercontent.com/assets/1013506/8333294/ebebad68-1a57-11e5-90bb-174cf0d6d40f.png)

**Comment by NinjaGrisen** [comment]
I love this one yeeyang!

**Comment by juanmnl** [comment]
@ericelliott Well, you are right that great logos are very simple, but it ain't how they are born, it's how they evolve to be. They have the luck of becoming so known that they could oversimplify without losing their brand.
![mercedes-benz-logo-evolution-timeline](https://cloud.githubusercontent.com/assets/699945/8334898/fa82dc4a-1a5f-11e5-98fc-75be3d7bef77.jpg)

That's why you can create a -somehow- adaptative logo.
For example, i created this for a meteorjs plugin.
Normal (full detail)
![ua_256x256-color-cast](https://cloud.githubusercontent.com/assets/699945/8334954/443b18d4-1a60-11e5-993c-79034cf88d23.png)

Small (no detail)
![ua_150x150-simplest](https://cloud.githubusercontent.com/assets/699945/8334970/5ccd8b70-1a60-11e5-9ed0-add25c608172.png)

There's no ONE way of doing this kind of things and this is the internet, logos should be fun. :smile:

Cheers and good luck with this!

**Comment by koresar** [comment]
## Logo submissions have ended. Please proceed to this poll, leave your opinion: https://gist.github.com/koresar/aca0ca81edc34f58462c

**Comment by koresar** [comment]
Tomorrow I'll publish the results. It might change by then but I think already have a clear winner. :)

**Comment by ericelliott** [comment]
:)

**Comment by koresar** [comment]
And the winner is... **Image 2** by @unstoppablecarl 
We have created a [repository](https://github.com/stampit-org/stampit-logo) for logo(s). Trying to make variations of this logo for different resolutions and screen sizes.
The second place (also by @unstoppablecarl btw) is rather far, so no second voting round is necessary.

We appreciate all the participants. These were great contributions. See you around!

<img width="533" alt="screen shot 2015-07-03 at 10 21 54 pm" src="https://cloud.githubusercontent.com/assets/1622575/8499078/2b42d082-21d2-11e5-8fb5-310aeed4b3c2.png">
<img width="523" alt="screen shot 2015-07-03 at 10 22 17 pm" src="https://cloud.githubusercontent.com/assets/1622575/8499094/3b5bd270-21d2-11e5-8bca-4dac49df6725.png">
<img width="513" alt="screen shot 2015-07-03 at 10 22 30 pm" src="https://cloud.githubusercontent.com/assets/1622575/8499097/421d9b02-21d2-11e5-8c9e-dbd9e7e1eaf2.png">
