### ISSUE TITLE
Use ESLint instead of JSHint

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#111]
As we are using ES6 now the ESLint would do a better job. Should convert.

Please, use [Airbnb style](https://github.com/airbnb/javascript/tree/master/linters) as widest used and most popular one. Discuss!

**Comment by ericelliott** [comment]
Definitely ESLint. :+1: 

I've been experimenting with my own ESLint config, but I'll check out the Airbnb style.

**Comment by ericelliott** [comment]
https://github.com/stampit-org/stampit/issues/116

**Comment by koresar** [comment]
Implemented. Please, review #123 and merge. :)

**Comment by ericelliott** [comment]
:+1:
