### ISSUE TITLE
Are ES6 Promises can be `convertConstructor` ?

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#114]
I wonder if someone could try that (assuming ES6 environment lie babel or io.js):
```js
import stampit from 'stampit';
let PromiseStamp = stampit.convertConstructor(Promise);
```
Will it work the way promises work?
Can someone test that please?

**Comment by ericelliott** [comment]
JS native Promises take a function as a param, so that wouldn't be the only step...

**Comment by koresar** [comment]
I'll continues my example from above:
```js
PromiseStamp((resolve, reject) => {
});
```
Our converted stamps can pass those arguments with ease. :)

**Comment by koresar** [comment]
Crappy idea.
