### ISSUE TITLE
Needs coverage test

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stampit#115]
See the [prod-module-boilerplate](https://github.com/ericelliott/prod-module-boilerplate) [package.json](https://github.com/ericelliott/prod-module-boilerplate/blob/master/package.json#L12) for an example.

**Comment by ericelliott** [comment]
https://github.com/stampit-org/stampit/issues/116

**Comment by koresar** [comment]
Implemented with #123. Please, check and merge. Thanks.

**Comment by ericelliott** [comment]
:+1:
