### ISSUE TITLE
Dependency check

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stampit#118]
Make sure all installed dependencies are declared.

[Example](https://github.com/ericelliott/prod-module-boilerplate/blob/master/package.json#L22) (`"missing"`, `"extra"` and `"ok"` tasks).

See [Upgrade Stampit quality control and security meta](https://github.com/stampit-org/stampit/issues/116)

**Comment by koresar** [comment]
I'm not getting. What's that and what's the point?

**Comment by ericelliott** [comment]
This issue is a check to make sure that all the dependencies you've installed locally also exist in `package.json`, so when other people try to install it, they get all of the required dependencies installed. It also checks for dependencies that are required in `package.json` that are not used in the code (which sometimes results in false positives, so we don't count those ones as errors).

**Comment by koresar** [comment]
> when other people try to install it, they get all of the required dependencies installed.

Isn't it the way `npm` work by default?

> It also checks for dependencies that are required in package.json that are not used in the code

Do you think there is a possibility for that to happen in 100 lines code base of stampit? I doubt.

The dependency check worth doing for large projects. For a utility module like stampit it's an overhead.

**Comment by ericelliott** [comment]
> Isn't it the way npm work by default?

Not if it's missing from `package.json`, which is what this checks for.

> Do you think there is a possibility for that to happen in 100 lines code base of stampit? I doubt.

Hoping to get all my projects using the same standards so we don't have to reinvent the wheel for every new project. Think on the scale of stampit-org, instead of just Stampit. =)

> For a utility module like stampit it's an overhead.

The dep check will run very fast, and only on Travis (since we won't make it a pre-commit requirement).

Sound fair?

**Comment by koresar** [comment]
Yup. Sounds good.

**Comment by koresar** [comment]
See #132
