### ISSUE TITLE
Precommit hook

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stampit#119]
Example:

* [ ] [Package dependency](https://github.com/ericelliott/prod-module-boilerplate/blob/master/package.json#L38)
* [ ] [Configure pre-commit](https://github.com/ericelliott/prod-module-boilerplate/blob/master/package.json#L27)
* [ ] Lint (keep it really lightweight!)

See [Upgrade Stampit quality control and security meta](https://github.com/stampit-org/stampit/issues/116)

**Comment by koresar** [comment]
Hello Eric,

I'd like to share few stories from me experience with you.

As an experienced developer (12 years of commercial coding) I stand strongly against any git hooks. And here is why:
* I **often** `commit` uncompilable changes just to switch branches.
* I sometimes `push` broken tests and even uncompilable changes just to switch laptops/coding environments.
* About 5 years ago we tried git precommit hooks in our team of 5. Removed it in about 30 minutes.
* I often experiment using local branches. These never lint as you understand.

Please, do not introduce any pre-commit or pre-push hook to any projects, unless understand the devastating consequences.

**Comment by nkbt** [comment]
@koresar use `-n` (aka `--no-verify`) in that case. In this case you explicitly pass through precommit check, saying "I know what I am doing in this case"

**Comment by nkbt** [comment]
Ideally all commits should be valid and working, so a case of non-completed job is a deviation, not a norm

**Comment by koresar** [comment]
@nkbt Unfortunately I'm using SourceTree and WebStorm to commit. Other people use various visual git tools which do not pass `-n` or alike to the git command line.

**Comment by koresar** [comment]
@nkbt 
> Ideally all commits should be valid and working, so a case of non-completed job is a deviation, not a norm

Ideal commits should be merged. That's true.

I want freedom on my local machine(s). If I can't commit my own branches freely then let's get back to SVN. Git won't benefit us anymore. :)

**Comment by troutowicz** [comment]
> Ideally all commits should be valid and working, so a case of non-completed job is a deviation, not a norm

Really? You've never commited broken commits during development to record some kind of logical progression? This is extremely common.

**Comment by nkbt** [comment]
@troutowicz That happened maybe, umm, twice. And I used `-n` then.

@koresar on your local machine you can always mess with package.json (and add it to a separate `Local` changelist in Webstorm to not commit it accidentally) in this case to disable pre-commit hook.

I personally believe that committing broken code should be a rare exception.

Though possible solution could be to utilize pre-push rather then pre-commit.

**Comment by koresar** [comment]
@nkbt That you for the tip with the WebStorm. Is there a same for SourceTree?
I'm not using changelists in WebStorm, disabled them intentionally. Any other workaround maybe?

However, thinking of all the workarounds is making me anxious. It's simpler not to implement any git hooks, - no workarounds would be needed. :)

> I personally believe that committing broken code should be a rare exception.

That's is my personal opinion too, but only for the single developer projects. In my experience, if there are two or more people working on the same repository the git hooks suck. @nkbt try pre-commits in your team and let us know how it went.

> Though possible solution could be to utilize pre-push rather then pre-commit.

This brings same troubles as pre-commit hooks, just the troubles happen more rare.

**Comment by nkbt** [comment]
@koresar we are using pre-commit checks in our ~15 people team.

**Comment by koresar** [comment]
> we are using pre-commit checks in our ~15 people team.

Would you elaborate on that?

* Every repository of every developer have the pre-commit hook which:
 * Does linting and stops a dev from committing if linting fails.
 * Runs tests before the commit and stops a dev from committing.
 * Checks extra installed and missing modules like so:
```json
    "missing": "dependency-check package.json",
    "extra": "dependency-check package.json --extra --ignore",
```
* Could you please show use the pre-commit hooks themselves? What's being checked? For how many repositories?

**Comment by nkbt** [comment]
1. Yes. Does linting and stops a dev from committing if linting fails.
2. Yes. Runs tests before the commit and stops a dev from committing.
3. No deps checks since we freeze dependencies via npm-shrinkwrap and rarely update them.

```sh
#!/bin/bash

PATH="/usr/local/bin:$PATH"

# Validate code, use --silent to avoid NPM errors shown.
npm run validate --silent

RESULT=$?

[ $RESULT -ne 0 ] && exit 1
exit 0
```


```json
"validate": "npm run lint && npm run test:validate",
"lint": "eslint *.js app/assets/javascripts/psa app/assets/javascripts/utils ./app/assets/javascripts/react",
"test:validate": "node ./node_modules/karma/bin/karma start ./karma.conf.js --single-run --reporters progress > /dev/null",
```

**Comment by nkbt** [comment]
We have one project we are working on, so uhm one repo.

**Comment by ericelliott** [comment]
Let's do a lint-only pre-commit hook here. Travis will catch the rest. =)

**Comment by koresar** [comment]
@nkbt Thanks Nik. That's awesome to know that 15 people commit to the same repository and have such a great level of cooperation and clarity. Keep it up.

**Comment by koresar** [comment]
Today I switched between my local unlintable and test failing `eslint` branch (not pushed yet) and the `edvanced_examples` branch to fix up @troutowicz finds. 

Just sayin...

**Comment by unstoppablecarl** [comment]
Im with @koresar I prefer to commit progress even unfinished when I have to stop working so that it is in the repo instead of only the machine I was last using.

**Comment by ericelliott** [comment]
We already spent too much time arguing about this.

**Comment by ericelliott** [comment]
I do want this in the [prod-module-boilerplate](https://github.com/ericelliott/prod-module-boilerplate/pull/19). This thread has convinced me to make it lint-only.
