### ISSUE TITLE
Use console.Symbols.INSPECT for debug output

### ISSUE THREAD

**Issue by wheresrhys** [stampit-org/stampit#121]
I'm just watching your talk introducing stampit. One criticism someone raises is that identifying the type of the object in debug output is more difficult than in more classical inheritance. I wonder if, given the code is written in ES6 now, `console.Symbols.INSPECT` can be used to address this concern?

**Comment by koresar** [comment]
Hello @wheresrhys 

I'd like to understand your concern in full. Would you please answer few questions?

> identifying the type of the object in debug output

In JavaScript what do you mean by 'type of the object'? The `typeof` operator?

(I'll be asking more questions later.) :)

**Comment by koresar** [comment]
How do you see the usage of the `console.Symbols.INSPECT`? Code samples maybe?

**Comment by koresar** [comment]
For anyone, who's not familiar with `console.Symbols.INSPECT`, please have a good time reading this: http://blog.keithcirkel.co.uk/metaprogramming-in-es6-symbols/

**Comment by wheresrhys** [comment]
About 35:50 in to this https://vimeo.com/69255635 it's the issue raised by the audience member - I think he does a better job of outlining the problem than any typing by me would. I just happened to be reading the blog you linked to just before watching the video so it jumped out as a possible solution.

**Comment by koresar** [comment]
Hm, mate, I think we have solved the `typeof` issue with stampit v2.
Check this out: https://github.com/stampit-org/stampit/blob/advanced_examples/ADVANCED_EXAMPLES.md#self-aware-objects---instancegetstamp-2-ways

Here is your business logic stamp:
```js
const User = stampit(/* bla bla bla whatever */);
```

Here is the behavior you can compose to any other stamp (like the one above).
```js
const SelfAware = stampit.init(({ instance, stamp }) => {
  instance.getStamp = () => stamp;
});

const SelfAwareUser = User.compose(SelfAware);
```

And here is how it works now:
```js
const user = SelfAwareUser();
assert.strictEqual(user.getStamp(), SelfAwareUser); // All good
```

Is it the behavior you were looking for?

**Comment by ericelliott** [comment]
> "more difficult than in more classical inheritance"

`instanceof` lies in classical inheritance. Anybody depending on it is making a mistake. The fact that it doesn't work for stamp instances is a **feature**, not a bug.

**Comment by ericelliott** [comment]
:+1: @koresar

**Comment by koresar** [comment]
@wheresrhys Were your question answered? Please, feel free to express your concerns. We love to hear those.

**Comment by koresar** [comment]
Closing. The issue starter is not active.
