### ISSUE TITLE
Simplifying README

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#122]
This might sound as not an important issue, but in my opinion this is the most important one. People come across stampit and move on because readme is too broad.

There are ways to do a better README.
* http://danhough.com/blog/nodejs-maintainer/
* https://github.com/zcei/standard-readme

It would be great if someone would draft a better README. Any ideas are very welcome. Any! Anyone?

## Checklist

* [x] [Restructure README doc](https://github.com/stampit-org/stampit/issues/122#issuecomment-118570103)
* [x] [Add pseudo code & remove confusing stuff](https://github.com/stampit-org/stampit/issues/122#issuecomment-118512009)
* [x] Link to [Fluent talk](https://vimeo.com/69255635)
* [x] Link to [The Two Pillars of JavaScript Part 1](https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3)
* [ ] Link to [Common Misconceptions About Inheritance in JavaScript](https://medium.com/javascript-scene/common-misconceptions-about-inheritance-in-javascript-d5d9bab29b0a)
* [ ] In all examples, always use the `stampit.*` shortcuts when we're not passing a param.

**Comment by unstoppablecarl** [comment]
I think these primary questions need to be answered at the start of the file as concisely as possible.

- What is stampit?
- What is a stamp?
- Why is this better than Classes?

**Comment by ericelliott** [comment]
We need to answer "what is stampit?" and "why should I care?" in a short paragraph or two at the top of our README.

Then move on to the [https://github.com/zcei/standard-readme](Standard README) features.

I have no objection to moving the detailed API docs to individual files in the `docs` folder.

**Comment by unstoppablecarl** [comment]
> moving the detailed API docs to individual files in the docs folder.
Agreed

**Comment by unstoppablecarl** [comment]
> We need to answer "what is stampit?" and "why should I care?" in a short paragraph or two at the top of our README.

I think we should answer them as concisely as possible in 1 or 2 sentences at the top and elaborate later in the readme. Maybe a link in the short answers to the detailed explanations. I think the lack of conciseness at the start of the file is what is leading to the inability to get what stampit is after skimming the top.

**Comment by koresar** [comment]
:+1: Conciseness and examples!

**Comment by ericelliott** [comment]
* [ ] What is Stampit?
* [ ] Getting Started
  - One very basic example of install and use (a, b, compose)
  - Link to advanced examples
* [ ] What can it do for me?
* [ ] Where can I learn more?
  - [The Two Pillars of JavaScript](https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3)
  - [Classical Inheritance is Obsolete: How to think in Prototypal OO](https://vimeo.com/69255635)
  - ["Programming JavaScript Applications"](http://pjabook.com)

**Comment by unstoppablecarl** [comment]
> A stamp is a composable factory function. It creates object instances. You can compose multiple stamps together to create new stamps.

I think this needs to explain what it means to compose multiple stamps.

Factory functions require the `new` keyword? Is that a typo?

I think we should add a file that explains our philosophy and what anti-patterns we are avoiding with stampit. thoughts?

**Comment by koresar** [comment]
Today a person in [gitter](gitter.im/stampit-org/stampit) was asking questions. He reminded me of the things in the README I stared at months ago understanding nothing. What I thought when I saw [the examples in readme](https://github.com/stampit-org/stampit/blob/64cc63dabb252c4c256e6ee382efee358011dad0/README.md) for the first time: **wtf?**

Back then I had to go to the source code in order to understand what's going on. Also, nowadays, when I'm explaining stampit to others, I find that the only way they understand it fast is to explain stampit internals. Like that:
> This is what stampit is doing to your refs, props, methods and inits. PSEUDO CODE:
```js
var instance = Object.create(methods); // methods is the prototype
_.assign(instance, refs);
_.merge(instance, props);
inits.forEach(function (func) { func.bind(instance)(); }); // calling with `this` instance
```

##### 1. I strongly believe that the pseudo code above should be going just after the first examples in the README.

The other thing that the person in gitter was confused about is the `stampit.mixin` function. He thought it's kind of stampit's special purpose API function which is doing something smart. And, yes, he took idea that from our readme!!!
> But that's boring. Let's see what else is on tap:
...
```js
// Some more privileged methods, with some private data.
// Use stampit.mixin() to make this feel declarative:
var availability = stampit().init(function () {
  var isOpen = false; // private
  return stampit.mixin(this, {
    open: function open() {
      isOpen = true;
      return this;
    },
    close: function close() {
      isOpen = false;
      return this;
    },
    isOpen: function isOpenMethod() {
      return isOpen;
    }
  });
});
```

The `stampit.mixin()` line above confused me very much 1.5 years ago. It still does to some extent. I believe the example (and few other examples) should be rewritten for newbie JS devs or even removed.
##### 2. We should teach people to use less confusing syntax:
```js
// Some more privileged methods, with some private data.
var availability = stampit().init(function () {
  var isOpen = false; // private
  this.open = function open() {
      isOpen = true;
  };
  this.close = function close() {
      isOpen = false;
  };
  this.isOpen = function isOpenMethod() {
      return isOpen;
  }
});
```

Also, I believe we
##### 3. should deprecate `stampit.mixin()`
and ask people to use `lodash`, `Object.assign` or `supermixer` directly. This is not stampit's responsibility at the end the day. But if deprecating sounds too radical we can expose the `supermixer`'s functions via `stampit.mixer` and use it like so: `stampit.mixer.mixin()`.

**Comment by troutowicz** [comment]
I agree with all 3 points. Stampit does not need to provide a wrapper to `Object.assign`.

**Comment by ericelliott** [comment]
Agreed on all counts. The only reason `stampit.mixin()` exists is because when I originally wrote Stampit, only the most in-the-know devs were actively using `_.extend()` and `$.extend()`.

The world has changed a lot since then!

:+1:

**Comment by koresar** [comment]
I'd create an issue to eliminate `mixin` function mention everywhere in the docs we have. Also, the `@deprecated` JSDoc tag should be allied to all them. Agree?

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
One more close to useless feature which complicates stampit is "multiple arguments to methods, refs, init". Especially "init".

Reading something like that confuses people. Moreover, it complicates stampit source code (which we have to support unfortunately).
```js
myStamp = myStamp.
...
.init({
  foo: function bar() {
    this.b = true;
  }
}, {
  bar: function baz() {
    this.c = true;
  }
});
```

I have never passed my init functions as properties of an object.

##### Let's leave the multiple arguments feature but remove any mentioning of it from the README.
Or, we can leave a small note in the README saying "Any of the following accept multiple arguments." or alike.

**Comment by ericelliott** [comment]
> Reading something like that confuses people.

Sure, remove it from the README, but we should add a more detailed API doc and include it.

> I have never passed my init functions as properties of an object.

I use these features all the time for more complex inheritance. Consider this a strong keep vote.

> Let's leave the multiple arguments feature but remove any mentioning of it from the README.

Agreed, but we'll need to create a more detailed API doc. The README can serve as our "welcome to Stampit, here's how to get started" guide. =)

> Or, we can leave a small note in the README saying "Any of the following accept multiple arguments." or alike.

That would be fine, as long as there's an example in the API docs somewhere. =)

:+1:

**Comment by koresar** [comment]
Agree to all that, Eric. Cheers

**Comment by ericelliott** [comment]
We should start a checklist for the new README. And these should be on it:

* [ ] Link to [Fluent talk](https://vimeo.com/69255635)
* [ ] Link to [The Two Pillars of JavaScript Part 1](https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3)
* [ ] Link to [Common Misconceptions About Inheritance in JavaScript](https://medium.com/javascript-scene/common-misconceptions-about-inheritance-in-javascript-d5d9bab29b0a)

**Comment by koresar** [comment]
:+1:

**Comment by ootoovak** [comment]
Copied from the Gitter chat by request:
> @ericelliott I have been reading your book which is great for many reasons. When it comes to Stampit though and learning new material a lot of hand holding really helps (as well I think with adoption). The book at the moment has the Stampit v1 API. And the blog posts are what got me interested in prototypical OO in the first place but they are at too high a level to hook them into day-to-day usage of Stampit.
I think there almost needs to be the hook, like:
- This is why prototypical OO is great [link to video or blog post for more info].
- This is why Stampit is great.
- Here is a quick easy example of a common Stampit use case.
- Click here to see more (one concept and use case step at a time) examples [best practices link].
- Here are some of the really cool advanced things you can do with Stampit [advanced examples link].
- If you want to read/watch more about why prototypical OO is so cool check out these links [link to blogs/book/videos]

**Comment by ootoovak** [comment]
> Classical OO is so pervasive I think there will be a lot more work involved in education that most open source libs. As I said I think the hooks (blog posts, video) are already in place. Now having an easy way to get people (especially pre-existing classical OO programmers) using Stampit in their pet project could really help boot it's usage (which will be great for a shift to prototypical OO).

**Comment by ericelliott** [comment]
@ootoovak Thanks! :+1:

**Comment by ootoovak** [comment]
In the ReadMe Stampit is uses both uninvoked `stampit.` and invoked with no parameters `stampit().`. Would be good to either have consistency and maybe a small note about it being optional either way if it is or having some place to explain the difference between the two.

**Comment by ericelliott** [comment]
:+1:  We should always use the `stampit.*` shortcuts when we're not passing a param.

**Comment by unstoppablecarl** [comment]
I think it would be better to always use `stampit()` so it is clear that there is a step where you are creating a new stamp then adding things to it.

**Comment by koresar** [comment]
:+1: Carl.

**Comment by troutowicz** [comment]
The idea is to make the README as straight forward as possible. I think shortcuts should be mentioned in a tips & tricks doc.

**Comment by netaisllc** [comment]
+1 for 'better to always use stampit()"

BTW, this is a great project and deserves much wider notice, much like EE's more conceptual views on OOP. 

What you guys are tussling with is the age-old challenge of docs written by the Authors. Don't fret. The key is to gain/forge/force consensus on the purpose of a doc or page. (Think DOT.)  After that, content and style micro decisions become much easier. 

And always true is: if the reader gets interested, then will gladly click deeper and deeper in the content.  (Google Adwords pretty much proved this.)  What I mean is: ignore the lazy devs who want it all on the same page and modularize your content like you would an app. Because it is.

**Comment by ericelliott** [comment]
:+1:

**Comment by unstoppablecarl** [comment]
What is stampit?
 - A library with tools to assist in the creation of composable factories that leverage prototypal OO.

What is a stamp?
 - A stamp is a composable factory function [link to factory function definition].

What is a composable factory?
 - Stamps can be composed to make new stamps with merged behavior.

Image that shows a tree representing classical inheritance and 4 stamps side by side with arrows down pointing to a new composed stamp.

Is stampit a framework?
 - No
 - Multiple codebases using stampit and making stamp objects can be used to compose new stamps with merged behavior.

How does stampit work?
 - When creating an object instance in javascript properties on the resulting object instance will be one of the following types:
  - Immutable primitives such as string or number
  - Objects by reference (objects or arrays referenced elsewhere)
  - Objects created specifically as part of the object instance creation process
  - Functions

Juggling these properties when creating an object in javascript can be tricky. 

@TODO add an example of implementing all of these types of properties using a function constructor in js, then how it would be done using stampit

thoughts?

**Comment by troutowicz** [comment]
@unstoppablecarl Looks good. Under __Is stampit a framework?__ I would add that stampit is an implementation of EE's specification for composable factory functions.

**Comment by ericelliott** [comment]
Looking much better. =)

Simple = good.

**Comment by koresar** [comment]
Current stampit README is good. I'll leave this closed for now. Feel free to reopen if something is still bothering you or you feel the discussion should continue.
