### ISSUE TITLE
Bad reference to ADVANCED_EXAMPLES.md

### ISSUE THREAD

**Issue by jorrit** [stampit-org/stampit#125]
The ADVANCED_EXAMPLES.md file only seems to exist in the advanced_examples branch. However, it is referenced from the README.md file in the master branch, referencing to a non-existing file: https://github.com/stampit-org/stampit/blob/master/ADVANCED_EXAMPLES.md .

**Comment by koresar** [comment]
Thanks mate! We know. It's not good. Although, good news!
It'll be fixed today. :)
@troutowicz people need #109 merged. How do you think, should we do it **now**? :smiley:

**Comment by koresar** [comment]
Fixed @jorrit 
Cheers
