### ISSUE TITLE
convertConstructor to addup "static" properties to stamp

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#128]
We have new `stamp.static` feature. However, we forgot to update `convertConstructor` to append "static" properties of a constructor to stamps.

See this test: https://github.com/stampit-org/stampit/blob/master/test/convert-constructor.js#L11
It should also change that "staticFunc" and "staticProp" are present at the `oldskool` stamp object.

**Comment by ericelliott** [comment]
:+1:
