### ISSUE TITLE
DefinitelyTyped need to be updated to stampit v2

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#131]
See http://definitelytyped.org/
And https://github.com/borisyankov/DefinitelyTyped/tree/master/stampit

Make sure version is reported in the http://definitelytyped.org/tsd/ table.

**Comment by koresar** [comment]
The PR submitted. Awaiting review: https://github.com/borisyankov/DefinitelyTyped/pull/4764

This time I made it right. The stampit and stamp members are shown while you type.

Last time it didn't pick up the syntax hints for code like `stampit().` - didn't show up Stamp functions.

I'll show screenshots after the PR get's merged.

**Comment by ericelliott** [comment]
Nice! =)

**Comment by koresar** [comment]
The PR got merged, although my IDE didn't pickup the syntax to make predictions work. Oh, well.

**Comment by ericelliott** [comment]
Do we need to open a new issue to address the IDE problem?

**Comment by koresar** [comment]
Nah, I don't think we should run after each IDE integration. IDE's problem is IDE's problem.

**Comment by ericelliott** [comment]
:+1:
