### ISSUE TITLE
Make stamp.fixed safer

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#134]
Since `stamp.fixed` object is exposed to the wild we should make sure stampit doesn't behave unexpectedly when someone decides to change it. For example:
```js
const stamp = stampit();
stamp.fixed.refs = /^hahaha/;
stamp.fixed.methods = [function hahaha() {}];
stamp.fixed.init = 42;
stamp.create(); // here might be problems!
```

We should validate the `.fixed` object each time it's used internally.
Places to validate: 
* All chaining methods.
* All all `stampit.` shortcut methods.
* The factory itself.

The functions where the validations should take place: `cloneAndExtend`, `compose`, `shortcutMethod` and `Factory`.

**Comment by troutowicz** [comment]
I don't know. I think `fixed` is fine as long as the API docs mention that `fixed` is an internal prop. No need to add complexity if it can be avoided.

**Comment by koresar** [comment]
There is one more likely scenario:
```js
var stamp = stampit().static({ fixed() { console.log('haha'); } });
stamp.create(); // the `stamp.fixed` was overriden with the `static`
```

What stampit should do in this case?

**Comment by troutowicz** [comment]
I'd say that might merit some sort of warning in dev mode.

**Comment by koresar** [comment]
What's "dev mode"? How to check if stampit is in the mode?

**Comment by troutowicz** [comment]
I've never tried myself, but I think Babel can handle environment checks for us.

https://babeljs.io/docs/usage/babelrc/

**Comment by koresar** [comment]
That's something weird. Correct me if I'm wrong, but...

When using our module, in order to see he did a bad thing to the `fixed` object the developer should:
1) Install `babel` if not yet installed (many use CoffeeScript or TypeScript).
2) Create the `babelrc` file, set it correctly up.
3) Run his code using `babel-node`.

Is that what you have just suggested?

**Comment by troutowicz** [comment]
Yeh my mind is gone. :p I was just trying to think of a way to display a warning when the project is in development, not production.

**Comment by koresar** [comment]
Well, I think stampit should be as good as possible for the production needs. :) The two code samples above can potentially lead to numerous problems in production given that we talk about the `stamp.fixed` in the README: https://github.com/stampit-org/stampit#stampit-1

Thus, I really wanna make stampit as safe as possible to use regardless the usage.

**Comment by troutowicz** [comment]
The README does mention it, but it does not make it clear that `fixed` is internal and should not be modified by the developer. I really think a warning is all that is needed. Developer's should be aware of the public API, and know what should be left alone.

**Comment by koresar** [comment]
I agree.

> I really think a warning is all that is needed.

What sort of warning? a README warning? A runtime console.log warning? An exception in a debug mode?

**Comment by troutowicz** [comment]
The README should mention `fixed` is internal, and some sort of runtime log warning should be introduced.

**Comment by ericelliott** [comment]
> I was just trying to think of a way to display a warning when the project is in development, not production.

Very simple solution: Create a warning function and import it.

During the build process, create two separate builds:

* Dev build - warning logs
* Prod build - warning is a no-op

**Comment by ericelliott** [comment]
Warning = runtime `console.log()`

**Comment by koresar** [comment]
> Create a warning function and import it.

I'm confused. "import" mean the ES `import` keyword? And "create function" means "have a file with function which warns to console"?
Correct?

**Comment by koresar** [comment]
Also, Eric. "two separate builds" means "two separate stampit.js files"? Correct?

**Comment by ericelliott** [comment]
One possible implementation of alternate build is to create two different build entry points and use dependency injection to pass the `warn()` function into stampit:

Dev build with live entry point:

```js
import warn from 'warn';
import main from 'main';

export default main(warn);
```

Prod build with no-op entry point:
```js
import main from 'main';

export default main(()=>{});
```

**Comment by koresar** [comment]
It's easier, simpler and more convenient to use a hook:
```js
import stampit from 'stampit';
stampit.on('collide', console.log);
// or
stampit._collideHook = console.log;
```

**Comment by koresar** [comment]
Or the hook can be implemented on the stamp level (not involving the entire stampit to hold state):
```js
const stamp = stampit({ refs: { hello: 'me' }, onCollide: console.log });
stamp({ hello: 'world' });
```
The code above would print:
`world me hello`

I really don't want stampit the module to hold any state. Stamp is the best place to keep those.

**Comment by koresar** [comment]
In the chat we agreed to not implement `stamp.fixed` safety.
