### ISSUE TITLE
A new module/repo gathering useful general purpose stamps

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#137]
So, we have this awesome [ADVANCED_EXAMPLES.md](https://github.com/stampit-org/stampit/blob/master/ADVANCED_EXAMPLES.md) doc. It's got a bunch of very useful general purpose stamps (like `.getStamp()` or `Cloneable` or the `prevalidate`). I bet many of the users would benefit if they won't need to copy&paste those things to their repos, but simply `require()` them.

Let's create an npm module where we would collect (with help of the community) the useful general purpose stamps.
```js
import Cloneable from 'stamps/cloneable';
import SelfAware from 'stamps/self-aware';
import Prevalidable from 'stamps/prevalidable';

const myStamp = myStamp.compose(Cloneable, SelfAware, Prevalidable);
```

Personally, I'd use it.

How does that sound?

**Comment by troutowicz** [comment]
:+1: A repo to share useful stamps would be cool.

**Comment by ericelliott** [comment]
Do you think we should put them in their own repos? =)

**Comment by koresar** [comment]
@ericelliott maybe sometime later. For now let's start from the simplest way - just like `mout` module.

**Comment by rektide** [comment]
initial link is moved, now https://github.com/stampit-org/stampit/blob/master/docs/advanced_examples.md

**Comment by ericelliott** [comment]
[Hows this?](https://github.com/stampit-org/useful-stamps)
