### ISSUE TITLE
Official package for meteor

### ISSUE THREAD

**Issue by yasinuslu** [stampit-org/stampit#138]
It would be awesome if you guys would provide an official meteor package.

http://meteor.com/

**Comment by koresar** [comment]
It would be even more awesome if you can guide us. :)
I know what Meteor is. Although, have zero experience with it. Do you have any Meteor experience?

**Comment by koresar** [comment]
Ok, here is the guide: https://atmospherejs.com/i/publishing

Our package depends on two other packages. Will meteor grab those two from npmjs if any? @yasinuslu

**Comment by yasinuslu** [comment]
Hi, there is an api to mark your npm dependencies but than the package wouldn't provide stampit on browser. I'm trying to implement a basic package for it, i'll write here when i complete it. Then we can discuss if it's a good way or not, how to automate it :) momentjs provides official package and here is their implementation https://github.com/moment/moment/tree/develop/meteor

**Comment by yasinuslu** [comment]
I used browserify package to make it available on client. On server the package simply exports stampit to global from npm.

**Comment by ericelliott** [comment]
What's wrong with [the existing atmosphere package?](https://github.com/richsilv/meteor-stampit)

**Comment by ericelliott** [comment]
Oh, I see, the existing package depends on the `./dist` folder that no longer exists in the repository. Is there any way to update the existing package instead of modifying this one? This is the first time I've seen a Meteor package wrapper add things to the original npm package instead of creating a wrapper package for atmosphere.

**Comment by ericelliott** [comment]
cc @philcockfield - Is there a better way to handle this?

**Comment by koresar** [comment]
Eric, will you take a lead on this meteor issue please as you are our publish-master. 😀

**Comment by yasinuslu** [comment]
@ericelliott I believe it's more reliable for people to see `stampitorg:stampit` :)

**Comment by ericelliott** [comment]
> I believe it's more reliable for people to see stampitorg:stampit

I am open to that, but I have no interest in maintaining a meteor package. Are you volunteering?

**Comment by ericelliott** [comment]
Move discussion to https://github.com/stampit-org/stampit-meteor/issues/1
