### ISSUE TITLE
Deprecating stampit.mixin() and aliases

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#142]
This is a follow-up issue after [the discussion](https://github.com/stampit-org/stampit/issues/122#issuecomment-118512009).
* [x] Update README to not mention `stampit.mixin()` and aliases.
* [x] Simplify README examples where the `stampit.mixin()` is used.
* [x] Add `@deprecated` JSDoc tag to minxin function and aliases.
* [x] warn about deprecation in console when `.mixin()` is called

**Comment by ericelliott** [comment]
Yay!

**Comment by ericelliott** [comment]
Add [ ] warn about deprecation in console when `.mixin()` is called?

**Comment by ericelliott** [comment]
Feel free to remove "help wanted" and assign to yourself if you're tackling this. =)

**Comment by koresar** [comment]
I'll think about warnings. Thanks.

**Comment by ericelliott** [comment]
:+1:

**Comment by ericelliott** [comment]
Warnings are a nice feature to warn people using it in prod that there will be a breaking change in an upcoming version. (3.0 in our case)

**Comment by koresar** [comment]
Agree.

**Comment by koresar** [comment]
Should we log to console when people are using `state` or `enclose` ?

**Comment by ericelliott** [comment]
> Should we log to console when people are using state or enclose ?

Yes. I think that deserves a separate issue. =)

**Comment by koresar** [comment]
:+1:

**Comment by koresar** [comment]
See #144.
