### ISSUE TITLE
API.md to cover all the API details

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#145]
* [x] The file should be placed in the ne `docs/` dir.
* [x] The file should contain the API description which is in the README.md for now.
* [x] It should cover all the mini details.
* [x] Make a note that `stampit.*` are shortcuts for `stampit().*`

After this issue is done we can strip out API section out of README and leave plentiful of links to the new API.md file.

**Comment by ericelliott** [comment]
:tophat:

**Comment by koresar** [comment]
Done. See #155
