### ISSUE TITLE
Method .init returns nothing after .compose & .convertConstructor

### ISSUE THREAD

**Issue by mdhooge** [stampit-org/stampit#148]
For example, if you take the file `advanced-examples/event-emitter.js` and you call .init() after `.convertConstructor` or `.compose`, the corresponding variable is `undefined`.

I don't believe this is the expected behaviour.

**Comment by koresar** [comment]
Can you please paste a code sample? Otherwise, I'm not quite getting what's wrong. 
Thanks

**Comment by koresar** [comment]
Hold on. I think I know what you mean. Checking it now.

**Comment by koresar** [comment]
I cannot reproduce your issue. The following works as expected.
```js
const stampit = require('../src/stampit');

const EventEmitter = require('events').EventEmitter;
const EventEmittable = stampit.convertConstructor(EventEmitter).init(() => {});

const User = stampit.refs({ name: { first: "(unnamed)", last: "(unnamed)" } });
const EmittableUser = User.compose(EventEmittable).init(() => {});

const user = EmittableUser({ name: { first: "John", last: "Doe" } });
user.on('name', console.log); // Does not throw exceptions like "user.on() has no method 'on'"
user.emit('name', user.name); // correctly handled by the object.
```

Could yuo please paste your code?

**Comment by mdhooge** [comment]
Hello.
This is getting stranger, because your sample code doesn't work for me!

I get the following stack dump:
```
advanced-examples/event-emitter.js:29
user.on('name', console.log); // Does not throw exceptions like "user.on() has
     ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/michel/dev_3rd/stampit_NoBackup/advanced-examples/event-emitter.js:27:6)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:179:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at Object.<anonymous> (/usr/lib/node_modules/babel/bin/_babel-node:112:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I use node v0.12.5, I'm on Debian Unstable.
I checked out your repo yesterday, and I `npm install`-ed the dependencies.
This isn't babel or ES6, because I also have the problem on "real" code that I tried to upgrade vo stampit v2.

Something must be different… :-/

**Comment by koresar** [comment]
Code, mate!!! I need your code!!! :)))

**Comment by mdhooge** [comment]
I copied/pasted **your** code (in your 3rd comment) in a file: it doesn't work for me, with the above stack dump. My sample code is similar.
Explanation of the dump: The method `.on()` is undefined because `EventEmittable` is also `undefined`.

**Comment by koresar** [comment]
Thanks for the info. node v0.12 fails. But node 0.10 does not.

I'll fix that today asap.

**Comment by mdhooge** [comment]
Thanks for your analysis, and sorry for the wasted time about the source code…

I recently switched to node 0.12 because npm kept yelling at me that I was using an outdated version. Not sure it was a smart move! :'-(

I tried to debug the problem with node-inspector but I get a blank page.
And when I try from the CLI, it seems it is the wrong .init method that is called:
```
break in issue148.js:8
  6 
  7 debugger;
> 8 EventEmittable = EventEmittable.init(function() {});
  9 console.log(EventEmittable);
 10 
debug> s
break in events.js:44
 42 
 43 EventEmitter.init = function() {
>44   this.domain = null;
 45   if (EventEmitter.usingDomains) {
 46     // if there is an active domain, then attach to it.
```

**Comment by koresar** [comment]
Yes. That's the issue I have found so far too. Let me dig in few more minutes. I'll get back to you shortly.

**Comment by koresar** [comment]
Sigh. Run this:
```js
const EventEmitter = require('events').EventEmitter;
console.log(EventEmitter);
```
It prints
```
{ [Function: EventEmitter]
  EventEmitter: [Circular],
  usingDomains: true,
  defaultMaxListeners: 10,
  init: [Function],
  listenerCount: [Function] }
```

As you can see they introduced the new `init` "static" function. :) Bummer! It's not referenced in [the docs](https://nodejs.org/api/events.html#events_class_events_eventemitter). This function overrides the stamp's `init` function (that's by design).

@mdhooge Do have a proposal how to fix the example?

**Comment by ericelliott** [comment]
Did you try passing a stamp into a composition after the event emitter stamp? It should override the overridden `.init()` (restoring stampit's `.init()`). However, this raises an important issue: Should we really use a method name as generic as `.init()`? I guarantee that a lot of stampit users have methods called `.init()` on their legacy stamps. One of the benefits of `.enclose()` was that it was unlikely to conflict.

It also underscores the fact that we need to be careful not to expose too many built-in statics, because there is a higher potential to conflict with the stamp author's statics. In fact, now that we have the options object, maybe we should deprecate the built-in static methods?

**Comment by mdhooge** [comment]
What I don't understand is when this `.init()` method gets added.

The following code works as expected (as long as you leave the 3 lines commented out). Normally I removed all ES6 code to be able to debug with node.
```
var stampit = require('./dist/stampit');

var EventEmitter = require('events').EventEmitter;
var EventEmittable = stampit.convertConstructor(EventEmitter);

var User = stampit.refs({ name: { first: "(unnamed)", last: "(unnamed)" } });
User = User.init(function() { console.log('User.init()'); });
var EmittableUser = User.compose(EventEmittable);

//console.log(EmittableUser);
//EmittableUser = EmittableUser.init(function() {});
//console.log(EmittableUser);

var user = EmittableUser({ name: { first: "John", last: "Doe" } });
user.on('name', console.log); // Does not throw exceptions like "user.on() has no method 'on'"
user.emit('name', user.name); // correctly handled by the object.
```

**Comment by koresar** [comment]
> It should override the overridden .init() (restoring stampit's .init()).

Nope. It won't help. `static`s are applied to any new stampt the last.

**Comment by mdhooge** [comment]
OK, just understood the problem -- well, I guess ;-)

**Comment by koresar** [comment]
> maybe we should deprecate the built-in static methods?

No! Never! I use it **a lot**. A huge lot. :)

**Comment by mdhooge** [comment]
This code works:
```
var stampit = require('./dist/stampit');

var EventEmitter = require('events').EventEmitter;
var EventEmittable = stampit.convertConstructor(EventEmitter)
.enclose(function() { console.log('EventEmittable.enclose()'); });

var User = stampit.refs({ name: { first: "(unnamed)", last: "(unnamed)" } });
User = User.init(function() { console.log('User.init()'); });
var EmittableUser = User.compose(EventEmittable)
.enclose(function() { console.log('EmittableUser.enclose()'); });

var user = EmittableUser({ name: { first: "John", last: "Doe" } });
user.on('name', console.log); // Does not throw exceptions like "user.on() has no method 'on'"
user.emit('name', user.name); // correctly handled by the object.
```

But I still don't understand when/where the EvenEmitter.init() method is copied into the stamp.
Maybe we could add a paramter to `convertConstructor` with a list of static methods to copy/exclude...

**Comment by ericelliott** [comment]
Remember how I said it's a priority for the user to be able to produce exactly what they want with stamp instances, and we shouldn't get in the way of that? With the growing importance of statics, I think the same should apply to the stamp. Maybe we should create a separate module:  `stampit/tools` with things like the static shortcuts:

```js
import events from 'events';
import stampit from 'stampit';

import {
  convertConstructor, props, compose
} from 'stampit/tools';

import myProps from './props';
import stamp from 'stamp';

const emitter = convertConstructor(events.EventEmitter);
const defaults = props(myProps);
const enhancedStamp = compose(emitter, defaults, stampit(stamp));
```

Thoughts :question:

**Comment by koresar** [comment]
@mdhooge if you're okay to read code then this is where it happens: https://github.com/stampit-org/stampit/blob/master/src/stampit.js#L256

And the `fixed.static` is being filled here https://github.com/stampit-org/stampit/blob/master/src/stampit.js#L278

**Comment by koresar** [comment]
oh! I agree about `stampit/tools`. I'd move there the `convertConstructor`. But, please, not the `props` or `compose`. These are essential to each LOC I use stampit at. I literally use only `stamp.props` and `stamp.compose`.

**Comment by ericelliott** [comment]
> oh! I agree about `stampit/tools`. I'd move there the `convertConstructor`. But, please, not the `props` or `compose`. These are essential to each LOC I use stampit at. I literally use only `stamp.props` and `stamp.compose`.

Wouldn't it be even less typing to just use `props` and `compose`?

**Comment by ericelliott** [comment]
or `compose(stampit({ props});` ?

**Comment by koresar** [comment]
See my prod code:
`RestClientFactory.props({body: {...}}).methods({...}).init(() => {...}).prevalidate({put: {body: joi.required()}});`

Please, rewrite it with your proposal syntax. :)

**Comment by mdhooge** [comment]
@koresar Thanks for the lines, it's getting clearer.

I don't see how moving the methods into a subpackage will solve the name collision.

If I understand well the problem is with name collision between the converted constructor and stampit. Maybe stampit should provide 2 names for its methods: a short, convenient one  when all is in control; and a longer, unique-guaranteed one when one receives a stamp from unknown origin.

**Comment by koresar** [comment]
@mdhooge You can use `enclose()` function instead of `init()` function. These are aliases. The first [code](https://github.com/stampit-org/stampit/issues/148#issuecomment-119409945) I've written above will work easily if you replace `init` with `enclose`.

**Comment by koresar** [comment]
Eric, there is a way to solve stamp static name collision **with...**

another composable stamp! **ta-dam, dshhhhh...**

**Comment by ericelliott** [comment]
I would argue this is MUCH more readable:

```js
stampit({
  props: {
    body: {...}
  },
  methods: {...},
  init: () => {...},
}).prevalidate({put: {body: joi.required()}});
```
or...
```js
```js
compose(
  props({body: {...}),
  methods({...}),
  init(() => {...}),
}).prevalidate({put: {body: joi.required()}});
```
```

**Comment by ericelliott** [comment]
Starting to really like the idea of that second syntax...

**Comment by koresar** [comment]
Your first code sample, Eric, loses whole point of composability. :)

Whereas the second one looks fine, however you are missing the looong `import` statement on top. :)

**Comment by ericelliott** [comment]
```js
import {
  compose, props, methods, init
} from 'stampit/tools';

compose(
  props({body: {...}),
  methods({...}),
  init(() => {...}),
}).prevalidate({put: {body: joi.required()}});
```

I don't see a problem with this. Looks very readable to me, and was not much typing.

**Comment by mdhooge** [comment]
OK, I leave it to you to find the best solution ;-)
I have a workaround for the time being.
Thanks

**Comment by koresar** [comment]
Compare to:
```js
import stampit from 'stampit';

RestClientFactory
  .compose(Prevailable)
  .props({body: {...}})
  .methods({...})
  .init(() => {...})
  .prevalidate({put: {body: joi.required()}});
```

**Comment by koresar** [comment]
@mdhooge sorry mate we are spamming you here. Have a good day. :)

**Comment by ericelliott** [comment]
> Compare to:

I am.. and that solution has lots more potential to collide with statics. :frowning:

**Comment by koresar** [comment]
As I said, we can compose one more stamp.
```js
RestClientFactory
  .compose(GuardStatics, Prevailable)
  .props({body: {...}})
  .methods({...})
  .init(() => {...})
  .prevalidate({put: {body: joi.required()}});
```

**Comment by mdhooge** [comment]
What will you put in your `GuardStatics`? Aliases?

**Comment by ericelliott** [comment]
See https://github.com/stampit-org/stampit/issues/149

**Comment by koresar** [comment]
@mdhooge Warning! PSEUDO CODE! Not tested I mean :)
```js
var GuardStatics = stampit().static({ static: function(staticProps) {
  return this.static(_.omit(staticProps, ['init', 'props', 'refs', 'methods', 'compose', 'create']));
});
```

**Comment by boneskull** [comment]
fwiw, I was not able to get @koresar 's pseudocode to work, or any other general solution.  I ended up just hacking around this specific issue:

```js
const EventEmittable = stampit.convertConstructor(EventEmitter);
EventEmittable.init = EventEmittable.enclose;
```

This seems to work.  Hopefully this can get someone else w/ the same issue back on track.
