### ISSUE TITLE
Ability to enhance existing Objects

### ISSUE THREAD

**Issue by rektide** [stampit-org/stampit#153]
One of the greatest parts about JavaScript is that we don't have to know ahead of time exactly what our objects are. We might get some JSON in from across the wire and be able to add some additional methods and data on to that objects over time.

At present however, StampIt's API is to create new objects. I would like to see it gain the ability to stamp existing objects with new capabilities. Then StampIt will be the composable-OO toolkit for JS of my dreams. :heart_eyes:

**Comment by koresar** [comment]
Hello there! Timely request my friend.

We do plan to have this in the following stampit release. Like:
```js
var myAwesomeObject = ...whatever...;
if (myAwesomeObject === MyStamp(myAwesomeObject)) { // comparing by reference
  console.log('Yes, baby!'); // this should be printed.
}
```

Is that the feature you're looking for?

**Comment by koresar** [comment]
@rektide hey?

**Comment by koresar** [comment]
Closing as the person is not contacting back.

**Comment by infiniteluke** [comment]
Hi - I'm also interested in this. Any word on when it will be available? Thanks!

**Comment by ericelliott** [comment]
@infiniteluke This is in progress as part of the official [stamp specification](https://github.com/stampit-org/stamp-specification). We're beginning to write prototype implementations now. It will be a little while before the API is officially settled.
