### ISSUE TITLE
1.X -> 2.X and Programming JavaScript Applications examples

### ISSUE THREAD

**Issue by johnthad** [stampit-org/stampit#159]
I am working my way though *Programming JavaScript Applications*. You introduce stampit in Chapter 3 "Prototypal Inheritance with Stamps". I figured out how to make the book's first example work using the CDNJS for stampit 1.2.0. Adapting the first example to 2.X seems to be

```javascript
var testObj = stampit({
  // methods in v1
  methods: {
    delegateMethod: function delegateMethod() {
      return 'shared property';
    }
  },

  // state in v1
  refs: {
    instanceProp: 'instance property'
  },

  // enclose in v1
  init: {
    function () {
      var privateProp = 'private property';

      this.getPrivate = function getPrivate() {
        return privateProp;
      }
    }
  }
}).create();

test('Stampit options object', function () {
...
```

At least that passes the QUnit tests. :) However I'm posting this here (1) to help any folks like myself who have struggled with this, and (2) to ask if there are any gotchas to watch for going forward.

**Comment by koresar** [comment]
Thanks mate. Keep it up!

**Comment by johnthad** [comment]
I'm glad this helps, +koresar. I'm getting a lot out of the book, and I've managed to run all the examples (in Chrome) up to this point. Maybe I'll post more, but I want to stay within the bounds of O'Reilly and Eric's copyrights.

**Comment by ericelliott** [comment]
@johnthad You have my permission to post whatever you want RE: "Programming JavaScript Applications" code samples.

**Comment by ericelliott** [comment]
@johnthad Come to think of it, if you would like to update all the code samples to 2.x, I'd love a pull request. Create a new file called `pjabook-updated-examples.md` in the `docs` folder.
