### ISSUE TITLE
Unexpected reserve word

### ISSUE THREAD

**Issue by aft-luke** [stampit-org/stampit#161]
I'm trying to run mocha with es6 babel compilers across my code, and when I get to the point where my code imports `stampit`, I get:

```console
import stampit from 'stampit'
^^^^^^
Unexpected reserved word
  import stampit from 'stampit'
  ^^^^^^
  SyntaxError: Unexpected reserved word
```

This seems to me like stampit es6 isn't being properly compiled from the `mocha --compilers js:babel/register` command, but I don't understand why. Other third-party libs I use written in es6 don't throw such errors. Thoughts? Is there some npm configuration in your `package.json` that should be setup so that compilers know where to go/what to do?

**Comment by aft-luke** [comment]
Nevermind. The problem is that babel (by default) doesn't reach into `node_modules`, so your code simply wasn't getting transpiled to es5. For those who run into a similar problem:

babel-hook.js
```
require('babel/register)({
  ignore: false // stop ignoring node_modules by default
})
```

And then `mocha -r babel-hook tests/**`

**Comment by koresar** [comment]
Hello.
Stampit is written in ES6 but compiled down to ES5. So when you are doing `import satmpit` you are actually getting the ES5 code, not ES6. This is done for backward compatibility. As many other projects do btw.

Cheers
