### ISSUE TITLE
Chaining stamp calls not working as I expected

### ISSUE THREAD

**Issue by michaelswe** [stampit-org/stampit#162]
Hi.
Am I missing something? Yes, probably.. please tell me. 
setUserData is defined in User.methods() and looks like this:

    setUserData: function(userData) {
      console.log(userData)
      this.data = userData;
    }

Making these two calls separately works fine:

    var user = User();
    user.setUserData(result);

But chaining them doesn't work. Writes to console, but not to "this.data":

    var user = User().setUserData(result);

I suspect that "this" references something else at this stage. But what and why?

**Comment by joshdmiller** [comment]
I'm not sure what you mean by "doesn't work", but if you mean that `user` is not a stamp instance, that's because you didn't return `this` (or anything, for that matter) in your `setUserData` method.

If it's not this, can you provide more info?

**Comment by michaelswe** [comment]
But of course..
I suspected that I'd make a fool out of myself =)
Thank you!

**Comment by koresar** [comment]
No worries @michaelswe 
You're always welcome asking any questions.
Cheers
