### ISSUE TITLE
stampit v3 RFC

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#163]
I'm starting stampit v3_0 branch. This is RFC, not a final decision.

Why 3.0?
- It's gonna be [stamp specifications](https://github.com/stampit-org/stamp-specification) compatible.
- The changes are going to be breaking due to the single reason: factory (aka stamp) arguments.
- The arguments will be an "options object".

As much compatibility as possible.
- The `.props()`, `.init()`, `.refs()`, `.methods()`, `.statics()` will be added by default to each stamp produced by stampit (but not by the utility functions).

Handy functions:
- Stampit will have utility functions. The `compose()` will definitely follow the [specifications](https://github.com/stampit-org/stamp-specification#standalone-compose-function-optional).
- Utility functions [are](https://github.com/stampit-org/stampit/issues/151#issuecomment-120647069): `methods()`, `assign()`,  `merge()`,  `assignStatic()`,  `initialize()`,  `describe()`,  `properties()`,  `set()`, `html()`,  `reactComponent()`, `convertConstructor()`...

This work will help us shape up the specifications as we go.

Comments?

**Comment by ericelliott** [comment]
> The .props(), .init(), .refs(), .methods() will be added by default to each stamp produced by stampit (but not by the utility functions).

Could this be implemented as an optional mixin instead of default behavior? It would be great if the next version of Stampit actually followed the stamp specification, and allowed authors maximum control over both the stamp and object instances.

**Comment by koresar** [comment]
Yeah, but what is "optional mixin"?

The aim is to strictly follow specs, Eric. Although, I would also like to presereve some compatibility. See the code.

Compatible stampit v2 and v3 syntax:
```js
import stampit from "stampit";
let stamp = stampit().props().refs().init().methods();
```

Incompatible syntax:
```js
import stampit from "stampit";
let stamp = stampit().statics({ init: () => console.log("created") });

// stampit v2
stamp.init(); // does not print anything!

// stampit v3
stamp.init(); // prints "created"
```

So, I plan to implement those "props, refs, init, methods" chaning methods as simple *overridable* statics. 
Pros: We would brake as less code as possible.
Cons: the only way to get pure stamps is via utility methods: `import {compose, merge, initialize} from "stampit"`

How does that sound, @ericelliott ?

**Comment by ericelliott** [comment]
> Yeah, but what is "optional mixin"?

A stamp.

```js
import { compose, compat } from 'stampit'; // compat is a stamp containing old stamp methods

const myStamp = compose(compat).props().refs().init().methods();
```

**Comment by koresar** [comment]
So, basically, in stampit v3 we change the stampit API significantly again?

**Comment by ericelliott** [comment]
Yes.

**Comment by koresar** [comment]
I'll change the original post of this issue to reflect our decision then.
Gimme 5 minutes please.
Thanks!

**Comment by ericelliott** [comment]
In fact, we could make a simple shortcut for an API compat version that people can just drop in to replace their 2.0 calls:

```js
import compose, compat from 'stampit';

// export a non-breaking version that adds composables support:
export default compose(compat);
```

**Comment by koresar** [comment]
Sure. I'll reflect it too in the top mesasge.

**Comment by ericelliott** [comment]
Now that I'm thinking about it, I think this would be fine:

```js
import stampit from 'stampit'; // 2.0 compat API
```

And if you just want to use the composables API instead:

```js
import { compose } from 'stampit';
```

**Comment by koresar** [comment]
So, we are going back to my original version. :)
I'm okay with any of the solutions.

**Comment by ericelliott** [comment]
Yeah, I think your original idea is really the best of both worlds. Don't break old call sites, but still give people direct access to the utility functions (including compose).

We'll make the 2.0 compat stamp be the default export.

**Comment by troutowicz** [comment]
Looks good guys. I am planning on making react-stampit spec compliant as well. :)

**Comment by ericelliott** [comment]
:+1:

**Comment by BerkeleyTrue** [comment]
:+1: for not breaking things :shipit:

**Comment by boneskull** [comment]
:+1:

**Comment by koresar** [comment]
For better compatibility of stampit with other modules/frameworks it's better stampit to support the `new` and `instanceof` operators. The compatibility will allow stampit to be used in a wider range of (legacy?) code bases. See #187 for example.

Although, like it is now, we would discourage JS dev to use the `new` and `instanceof` operators as we are doing it now.

Any objections?

**Comment by troutowicz** [comment]
I thought getting away from using `new` and `instanceof` was one of the reasons stampit was created. If a code base insists on using these operators, perhaps that code base should be made more flexible?

**Comment by boneskull** [comment]
@troutowicz Sometimes that codebase happens to be the EcmaScript specification.  For example, you can't:

```js
stampit.convertConstructor(Map)
```

`Map` expects itself to be called with the `new` keyword; it will throw an exception otherwise.

**Comment by boneskull** [comment]
@koresar that said, I'm behind supporting it

**Comment by boneskull** [comment]
@troutowicz though, I'm unsure if we're talking about the same thing.

**Comment by koresar** [comment]
What I mean is that #44 
```js
var Stamp = stampit(bla, bla, bla);
var obj = Stamp(ble, ble, ble);
if (obj instanceof Stamp) {
 // true
}

obj = new Stamp(ble, ble, ble);
if (obj instanceof Stamp) {
 // true
}
```

**Comment by boneskull** [comment]
I'm not sure I understand why supporting that is necessary

**Comment by koresar** [comment]
Yeah. I would need to show an example. So, in the #187 a person would like to replace classes with stamps and supply them to the Aurelia framework. But he can't, because `new AStamp()` returns rubbish.

This is the Aurelia's code which create instances of those classes: https://github.com/aurelia/dependency-injection/blob/master/src/container.js#L83
I wish stampit supported the `new` keyword, it could have gained wider usage.

**Comment by BerkeleyTrue** [comment]
Avoiding the `new` keyword is the point of stamps.

**Comment by boneskull** [comment]
@koresar I think I understand what you mean.  AngularJS does this as well.  You should be able to say, use a Stamp as a controller, but since they are instantiated with `new`, no such luck.

This makes sense.  `new` should be supported; it should not *do* anything, but it shouldn't make the stamp blow up.

**Comment by BerkeleyTrue** [comment]
Would it be easier to add support for factory functions in Aurelia?

**Comment by koresar** [comment]
@BerkeleyTrue Sure. But the world is biased towards the `new`. I don't think Aurelia and AngularJS will support factory functions just because of stampit.

**Comment by BerkeleyTrue** [comment]
That is a good point but I don't think these two worlds are compatible. It really should be one way or the other.

**Comment by koresar** [comment]
Worlds maybe not compatible. But stampit can be easily made compatible with Aurelia.

**Comment by ericelliott** [comment]
If `new` and `instanceof` support is an *optional mixin*, I have no objection. I object strongly to making it core.

**Comment by koresar** [comment]
At the first glance it is doable. Good idea.

**Comment by koresar** [comment]
Stampit v3-rc.0 was just released. `npm i stampit@rc`

**Comment by koresar** [comment]
Mostly done.
Some things are looking for an implementer.
