### ISSUE TITLE
Advanced_examples.md is gone

### ISSUE THREAD

**Issue by michaelswe** [stampit-org/stampit#164]
Unfortunately, I cannot find advanced_examples.md anymore. I can take a look directly in the example code instead, so it's no biggie.

But the link from the npm page should be removed. It currently points to:
https://github.com/stampit-org/stampit/blob/master/ADVANCED_EXAMPLES.md

**Comment by koresar** [comment]
Bummer! @ericelliott could you please publihs the current stampit `master` branch as v2.1.1? That'd fix the problem.

@michaelswe thank you very much!

**Comment by ericelliott** [comment]
Done.

**Comment by koresar** [comment]
Tested. It works.
