### ISSUE TITLE
Is the stamp getting stripped from its methods when inside a Passport strategy?

### ISSUE THREAD

**Issue by michaelswe** [stampit-org/stampit#166]
I'm really confused now. What have I missed?

I have a stamp like this:

    const App = stampit().
      init(function(context) {
        this.setDbUser(dbUtil.getMasterCredentials());
      }).

      methods({ 
        checkAppSecret: function(appSecret) {
            if(!this.secret) return console.log(new Error('No secret data loaded'));
            return appSecret === this.secret.appSecret;
        },

        setData: function(data) {
          if(!data) return this;
          this.data = {
            id: data.id,
            grant_type: data.grantType || data.grant_type,
            name: data.name
          };

          this.secret = {
            appSecret: data.appSecret || data.app_secret
          }
          return this; //return this (stamp) to make the call chainable
        },

        getData: function() {
          return this.data;
        },
      }).compose(
        DbLayer.use(appDbSchema)
      );

    module.exports = App;

The stamp works like a charm when I test it like this:

    model.App().loadFromDb({id: '1b12c4b2-2444-47a2-8a59-2c611c5c7493'})
      .then(function(app) {
        var isValid = app.checkAppSecret('secretCode');
        console.log(isValid);
      });

But when I use the stamp in a Passport strategy like this: 

    passport.use('client_password', new ClientPasswordStrategy(
      function(appId, appSecret, done) {
        model.App().loadFromDb({id: appId})
          .then(function(app) {
            if (!app) { return done(null, false); }
            if (!app.checkAppSecret(appSecret)) { return done(null, false); }
            return done(null, app);
          }).catch(function(err) {
            return done(err);
          });
      }
    ));

I get an error saying: *'app.checkAppSecret is not a function'*
I don't get it. I have probably misunderstood something.

**Comment by koresar** [comment]
You probably did missed something.

Show us the `DbLayer.use` function contents. It returns garbadge in the second case.

P.S. To debug I'd recommend you to insert the following into your `init` function:
```js
console.log(context.stamp.fixed);
```

**Comment by michaelswe** [comment]
Here is DbLayer.use:

    const DbLayer = stampit().
      static({
        use(dbSchema) {
          //dbSchema = {tableName: 'xyz', idField: 'id'}  //idField can be a string or array

          if(!Array.isArray(dbSchema.idFields)) {
            dbSchema.idFields = [dbSchema.idFields];
          }

          if(!dbSchema.selectFields) {
            dbSchema.selectFields = ['*']
          }

          if(Array.isArray(dbSchema.selectFields)) {
            dbSchema.selectFields = dbSchema.selectFields.join(', ');
          }

          return this.props({dbSchema: dbSchema});  
        }
       }).

**Comment by koresar** [comment]
Okay, then could you please show use the `loadFromDb` function contents?

**Comment by koresar** [comment]
The issue can be this line:
`return this.props({dbSchema: dbSchema});`

The `props` will **deep** copy the `dbSchema` to each new object. You probably wanted to use `refs`?

**Comment by michaelswe** [comment]
I changed to refs.. same problem.

Here is loadFromDb

    loadFromDb: function(options) {
      var instance = this;
      var db = pgp(instance.db);
      var whereClause = instance.generateWhereClause(options);
  
      let sql = 
      `
        SELECT ${instance.dbSchema.selectFields}
        FROM ${instance.dbSchema.tableName}
        ${whereClause}
      `;

      return db.one(sql).then(function(data) {
       return Promise.resolve(instance.setData(data));
      }).catch(function(err) {
        console.log('loadFromDb, err')
        console.log(err)
       return Promise.reject(err);
      });
    },

**Comment by koresar** [comment]
Side note: you don't need `Promise.resolve()`. Simple `return instance.setData(data);` does the same job.

**Comment by koresar** [comment]
Is there a chance something overwrites the `loadFromDb` function at some point?

**Comment by michaelswe** [comment]
No, I did a search to be sure. LoadFromDb is called from a couple of places, but only defined once.

About the promise.. I wanted to be sure to return a promise even after an error. I did the same thing at resolve to be sure. I do need it at error, don't I?

**Comment by michaelswe** [comment]
I "ported" the stamps to a hierarchical ES6 class structure where *App* extends *DbLayer*. A factory function makes the class work as a drop in replacement for the stamp. Everything works as it should when I use the "class" instead of the stamp. I don't quite understand the inner workings of stamps, which increase the risk of me using them wrongly. Maybe they are too complicated for me..

**Comment by koresar** [comment]
Re the Promises: yes you need in in the `.catch()` handler because you have some code using the error object before moving it forward.

**Comment by koresar** [comment]
IMO your stamp understand it right. It is a simple concept. What you lack is some JS debudding skills.
Why don't you put `console.log(app)` and see what it prints just before the crash?

I wanted to tell that before but hesitated. Please, do not take it as an offence, but you have overcomplicated your code.

0) This sounds like OMG:
> I "ported" the stamps to a hierarchical ES6 class structure where App extends DbLayer.

People are usually [doing vice-versa](https://medium.com/javascript-scene/how-to-fix-the-es6-class-keyword-2d42bb3f4caf).
1) You don't need the `DbLayer` stamp at all. Make it a pure function: `getStampForSchema(Schema)`.
2) You are nesting the composition instead of making it flat. This code is complicated too much:
```js
return db.one(sql).then(function(data) {
   return Promise.resolve(instance.setData(data));
})
```
3) Make your behaviours having minimum logic. For example:
```js
let SecretValidator = stampit().methods({ checkAppSecret(secret) { ...
let DbUserCredentials = stampit().props(dbUtil.getMasterCredentials());
let DbReader = WhereClauseGenerator.methods({ loadFromDb(options) { ... return data; });
let DbInstance = DbUserCredentials.init(({instance}) => { instance.pgp = pgp(instance.db); });
let Else...

// in the passport callback
let app = model.App();
app.loadFromDb({id: appId}).then((data) => {
  if (!app.checkAppSecret(data)) { return false; }
  return PassportDropInReplacement(data); // <- object the Passport requires
}).nodeify(done); // <- assuming you are using Bluebird promises implementation
```

**Comment by michaelswe** [comment]
This is NOT taken as an offence!  I take it as a great source of knowledge. I really appreciate you writing this up for me. Thank you for your time!

I fight day and night to learn proper Java Script (Last couple of years has been all SQL for me and before that, Delphi). My biggest problem with Java Script is that there are so many ways to do one thing and every blogg/book says to do it differently. 

About the OMG :)
I wasn't actually resorting to hierarchical, but did it as a test to make sure I hadn't made a mistake elsewhere.

At the first glance I don't quite follow you on 1-3. I'll make a cup of coffee and look closer. Also, I'd love to use arrow functions, but I'll wait until I can install node v4 with nvm. Don't want to fiddle with a global node install on my dev machines. iojs 3.3 for now..

**Comment by koresar** [comment]
Re the nvm. Try: `$ nvm install 4`
See here: https://github.com/creationix/nvm/issues/821#issuecomment-139025122

**Comment by koresar** [comment]
Also, people are not using pure node but babel to run ES6 code:
```
$ npm i babel -g
$ babel-node my-app.js
```

**Comment by koresar** [comment]
@michaelswe if you have any questions and you want the answers fast ask them in the gitter: https://gitter.im/stampit-org/stampit

**Comment by michaelswe** [comment]
Supermystierium solved. Unfortunately I don't know how.

I develop locally, but have all changes sent directly via SSH to a development server (with Sublime SFTP). I decided to wipe the server and reinstall. Made a copy of the old version at the server and sent all files to a new directory. Npm install to get the modules... And then everything worked :-/

I diffed the old and new directory and found no differences in my source code.

I diffed npm ls to find differences in module versions. The biggest differences where that Mongoose was still installed on the server, and some small version differences. Also Supermixer is installed separately in the new version, but it's the same version as used by Stampit. I can still reproduce the error in the old directory. I'd rather not leave this without understanding what happened. Do you have any ideas of how to understand the differences?

    105,127c105
    < ├─┬ mongoose@3.9.7
    < │ ├── async@0.9.0
    < │ ├── hooks@0.3.2
    < │ ├── kareem@0.0.4
    < │ ├─┬ mongodb@1.4.12
    < │ │ ├─┬ bson@0.2.22
    < │ │ │ └── nan@1.8.4
    < │ │ ├── kerberos@0.0.4
    < │ │ └─┬ readable-stream@2.0.2
    < │ │   ├── core-util-is@1.0.1
    < │ │   ├── inherits@2.0.1
    < │ │   ├── isarray@0.0.1
    < │ │   ├── process-nextick-args@1.0.3
    < │ │   ├── string_decoder@0.10.31
    < │ │   └── util-deprecate@1.0.1
    < │ ├── mpath@0.1.1
    < │ ├── mpromise@0.5.4
    < │ ├─┬ mquery@1.0.0
    < │ │ └── debug@0.7.4
    < │ ├── ms@0.1.0
    < │ ├── muri@0.3.1
    < │ ├── regexp-clone@0.0.1
    < │ └── sliced@0.0.5
    ---
    > ├── UNMET DEPENDENCY mongoose@^3.8.23
    172c150
    < │ ├─┬ request@2.62.0
    ---
    > │ ├─┬ request@2.61.0
    209c187
    < │ │ │ ├── hoek@2.16.2
    ---
    > │ │ │ ├── hoek@2.15.0
    221c199
    < │ │ ├── qs@5.1.0
    ---
    > │ │ ├── qs@4.0.0
    232c210,211
    < ├── stampit@2.1.1
    ---
    > ├─┬ stampit@2.1.1
    > │ └── supermixer@1.0.2
    234c213
    < ├── validator@4.0.6
    ---
    > ├── validator@4.0.5

**Comment by koresar** [comment]
This can be anything. Most likely you did `nvm use ...` but didin't reinstall modules (you should wipe node_modules if you change node version). Am I correct?

**Comment by michaelswe** [comment]
Yes, you are probably right. It was a long time ago, but I don't recall wiping node_modules when I switched iojs version. Big lesson learned.. Thanks!

At last I can get back to some productive work.. 

Btw, why would I need Babel when I can use most of ES6 in v4?

**Comment by michaelswe** [comment]
Hmm. I wiped node_modules in my *faulty* project and did *npm install*. Problem is still there. Is there anything else to wipe, but node_modules?

**Comment by koresar** [comment]
Babel JS implemented more ES6 features than V8 v4.5 (node v4).
http://kangax.github.io/compat-table/es6/

**Comment by koresar** [comment]
Could be request.js bug fix. Who know! :)

**Comment by michaelswe** [comment]
I found it.. But I'm too ashamed to tell you what it was :)

**Comment by koresar** [comment]
Now worries. :) Keep it secret.

**Comment by michaelswe** [comment]
There was actually a diff between the directories that I missed (yes, it was reported by the diff command).

I had a really old version of my app stamp file laying around at the server without the .js extension. I usually don't include .js when I require files, so the old file was picked up by require.

Lesson #2 learned: If a file is renamed in Sublime the new file is sent of to the server via SFTP, but the old file still remains at the server.

**Comment by koresar** [comment]
Feel free to close this issue any time. Cheers
