### ISSUE TITLE
Question regarding stamp construction

### ISSUE THREAD

**Issue by tcrosen** [stampit-org/stampit#167]
In your example document, you have the following code:

```js
// The connection object.
const DbConnection = 
  stampit().refs({ // Assigns the mongoose connection object.
    dbConnection: mongoose.connection
  })
  .init(function () { // Connecting to the DB upon creating an object.
    if (!this.dbConnection.readyState) {
      this.connection.open(this.connectionConfig);
      this.log('Opening a DB connection');
    }
  })
  .methods({ // A method to close the connection.
    close() {
      if (this.dbConnection.readyState) {
        this.dbConnection.close();
        this.log('Closing the DB connection');
      }
    }
  })
  .compose(
    Logger, // add logging capability via this.log() 
    DefaultConnectionConfig // add the default this.connectionConfig value
  );

const conn = DbConnection(); // Open a DB connection
const conn2 = DbConnection({ connection: conn.dbConnection }); // reusing existing
```

how does the following line execute for `conn` when you don't supply `connection` in the constructor?

```
     this.connection.open(this.connectionConfig);
```

Also is there a way to use Destructuring to enforce certain values in constructors?

Thanks for your time.

**Comment by koresar** [comment]
Could you please elaborate a little. What is "values in constructors"?

**Comment by koresar** [comment]
@tcrosen There is no "construtors" in stampit. There can be "intitializers". The only difference is that a stamp can have multiple initializers, which addup during composition (see `.compose()` functions).

Answering your question: take a look at the `.compose(Logger, DefaultConnectionConfig)` piece. As you can see we **compose** the `DbConnection` stamp with two more stamps. The latter one have single purpose - to set the `connectionConfig` string property to the instantiated objects: https://github.com/stampit-org/stampit/blob/master/docs/API.md#example
Thus, each time we create an object - `DbConnection()` - the object will have the `connectionConfig` set.

Does that answer your question?

**Comment by BerkeleyTrue** [comment]
The confusion lies around this line:
```js
this.connection.open(this.connectionConfig);
```
`this.connection` is never defined and in the creation of `conn` `connection` is not passed in the refs argument.

There are two typos in this document.

The line above should be `this.dbConnection.open(this.connectionConfig);`

And the following:
```js
const conn2 = DbConnection({ connection: conn.dbConnection }); // reusing existing
```

Should be:
```js
const conn2 = DbConnection({ dbConnection: conn.dbConnection }); // reusing existing
```

**Comment by koresar** [comment]
omg. :) Thank you.

**Comment by koresar** [comment]
@tcrosen I've just merged @BerkeleyTrue fix. Take a look now:
https://github.com/stampit-org/stampit/blob/master/docs/API.md#example

Does it look right to you now?

**Comment by BerkeleyTrue** [comment]
That was fast. You're welcome!

**Comment by tcrosen** [comment]
Wow thanks guys, I guess it was a simple typo.  I think I grok the whole concept. @koresar when I was writing "constructor" it crossed my mind I'd get yelled at :)  I loosely used it to describe an object "creator" or "initializer" method.

Thanks @BerkeleyTrue for clarifying my question.

**Comment by tcrosen** [comment]
PS. I fucking love this library :+1:

**Comment by BerkeleyTrue** [comment]
@tcrosen I'm glad I could help.

**Comment by ericelliott** [comment]
> I fucking love this library

I'll throw in another :+1: for the user community. You guys rock. :guitar: :fire: :notes:

**Comment by koresar** [comment]
@tcrosen You probably would like this effort as well: https://github.com/stampit-org/stamp-specification
We are trying to make the "stamp" a universal concept, so that other stamps from other libraries could be compatible with stampit's stamps.

**Comment by tcrosen** [comment]
> I'll throw in another  for the user community. You guys rock.

I discovered this from reading your articles, @ericelliott.  I tried implementing raw POO in a real application and quickly found it difficult to manage the subtleties -  instantiation, privatization, etc. and boilerplate code started to pile up.  This library solved most of my problems, to me it's become a necessity to use stamps seriously.

I'm planning on going full steam ahead with it and will be tackling real-world business problems.  I'll keep you guys posted with progress and contribute to contribute fixes and hopefully new documentation (eg. recipes/examples) I might discover.  

Thanks again.

**Comment by ericelliott** [comment]
This is the first time I've noticed seeing prototypal OO written as POO. I almost fell out of my chair.

Glad to have you with us. I'm confident that once everything clicks, you'll never want to inherit from another class again.

Stamps have spoiled me. I wouldn't want to code a major app without them. =)

**Comment by tcrosen** [comment]
> This is the first time I've noticed seeing prototypal OO written as POO

Dude I've been totally referring to it as POOP(rogramming) since I read about it in your articles.

**Comment by ericelliott** [comment]
![](http://38.media.tumblr.com/a184a54d2f35f1ea06501bfb949c436c/tumblr_neo8hxZmak1tes1e8o4_r1_500.gif)

**Comment by koresar** [comment]
Sorry guys. I had to tweet that. :)
https://twitter.com/kore_sar/status/645793395957338112

**Comment by ericelliott** [comment]
haha
