### ISSUE TITLE
Recommendation for importing/exporting Stamps?

### ISSUE THREAD

**Issue by tcrosen** [stampit-org/stampit#169]
Open-ended question here, but would this be a reasonable pattern for Stamp-based modules?

**api.js**
```js
export default const Api = stampit({
  // some API logic
});
```

**usersApi.js**
```js
import Api from 'api'

export default const usersApi = stampit({
  // some user-specific API logic
}).compose(Api);
```

Also: Are `Api()` and `Api.create()` the same?

Cheers.

**Comment by troutowicz** [comment]
Yes, it is reasonable. You don't even need to assign the stamp to a variable.

```js
export default stampit({})...
```

And yes, they are the same.

**Comment by tcrosen** [comment]
Thanks for the prompt reply.  Are there any recommendations for using `()` vs. `.create()`?  Personally I like the simplicity of `Api()` but it seems too easily misinterpreted as a class.  Using `Api.create()` makes it pretty clear you are dealing with a factory.

Just as an aside, after re-reading the `DbConnection()` example I should probably have done this instead:

```js
import Api from 'api'
export default const usersApi = Api({ ... });
```
since `usersApi` would be the final static object, it should probably not be a Stamp.

**Comment by troutowicz** [comment]
It's personal preference. `Api` is a factory function, there should be no misinterpretation. Classes get instantiated with the reserved word `new`.

**Comment by tcrosen** [comment]
> Classes get instantiated with the reserved word new

Totally fair point.  I guess I always have this in my mind as something people currently do to avoid/protect against omitting `new` for standard `function`-based classes.

```js
function Foo() {
   if (!(this instanceof Foo)) return new Foo();
   // ...
}

**Comment by troutowicz** [comment]
You shouldn't account for other people's shortcuts. Stick with the language's specifications. :)

**Comment by tcrosen** [comment]
> You shouldn't account for other people's shortcuts. Stick with the language's specifications. :)

Touché

**Comment by ericelliott** [comment]
```js
function Foo() {
   if (!(this instanceof Foo)) return new Foo();
   // ...
}
```

This effectively turns `Foo()` into a factory, as well, albeit with some weird side-effects related to `this` and `instanceof`.
