### ISSUE TITLE
XZXCVBVCXZXCVBNM,./

### ISSUE THREAD

**Issue by astanciu** [stampit-org/stampit#174]

**Comment by koresar** [comment]
@astanciu 
Hey, mate. WTF?

**Comment by astanciu** [comment]
oh man, my bad... I accidentally mashed the keyboard and didn't even catch that this happened. :(

**Comment by ericelliott** [comment]
:smile: )))))

**Comment by koresar** [comment]
haha! GitHub keyboard shortcuts rock :)
