### ISSUE TITLE
question: initialization function repetition

### ISSUE THREAD

**Issue by boneskull** [stampit-org/stampit#177]
```js
var stampit = require('stampit');

var foo = 0;

var A = stampit({
    init: function() {
        foo++;   
    }
});

var B = stampit().compose(A);
    
var C = stampit().compose(A).compose(B);
foo // 2
```

Granted, one would probably not do this, as `C` should probably be:

```js
var C = stampit().compose(B);
```

Regardless, I'm wondering if `Stampit.fixed.init` should be a `Set` instead of just an `Array`... I could see it going either way.

[Tonic Repl](https://tonicdev.com/boneskull/stampit-init-question)

**Comment by BerkeleyTrue** [comment]
You are composing `A` in twice, so the init function would happen twice. Is there a use case that this is causing an issue for you?

**Comment by ericelliott** [comment]
This is a perfectly valid composition, and there are use cases that may require it. Not a bug.

**Comment by boneskull** [comment]
fair enough

**Comment by koresar** [comment]
You can create a stamp (aka behavior) which would remove duplicate initializers if you really need that kind of thing.

```js
const RemoveDuplicateInitializers = stampit().init(({stamp}) => {
  stamp.fixed.init = _.uniq(stamp.fixed.init);
});

const C = RemoveDuplicateInitializers.compose(A, B); // it must be composed the first
```

**Comment by ericelliott** [comment]
:+1: 

I wouldn't consider this boilerplate that you should apply to all your stamps, though. It could introduce bugs instead of  avoid them, because some stamps may depend on the designed behavior.
