### ISSUE TITLE
Second object creation throws "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by sggt** [stampit-org/stampit#180]
I have created a stamp and need two objects from it. But wenn i create the second one i get a "Uncaught RangeError: Maximum call stack size exceeded" Exception in Chrome.

The problem from my sight is in that two lines and throws from line 173:
```javascript
 172   var instance = (0, _supermixer.mixin)(create(fixed.methods), fixed.refs, refs);
 173  (0, _supermixer.mergeUnique)(instance, fixed.props); // props are safely merged into refs
```

On the second call 'fixed.refs' is already merged with fixed.props.

**Comment by koresar** [comment]
Oh, wow.
Can you please help us to reproduce the bug?
What's the version of the node/browser, stampit version, supermixer
version, and most importantly the code which lead to this.
Thanks

**Comment by koresar** [comment]
@sggt Hey, thanks for closing it.
Would you please share what has happened? We need that info in case someone else steps on the same problem. :)
Cheers
