### ISSUE TITLE
[question] best approach to share properties ?

### ISSUE THREAD

**Issue by lorenzofox3** [stampit-org/stampit#181]
Let's say I start by creating a customer list stamp

```Javascript
var customerListStamp=stampit()
      .props({customers : []}) //note property is called "customers"
      .methods({
        updateCustomer: function (customer) {},
        deleteCustomer:function(customer){},
        refreshList: function () {
          callServerForRefresh()
            .then(function  (newList) {
              this.customers = newList //note it changes the reference
            }.bind(this))
        }
      })
```

Later I create generic selectable list behaviour

```Javascript
var selectableItemListStamp = stampit()
        .props({items: [], isAllSelected: false}) //note here the generic properties is "items"
        .methods({
          getSelectedItems: function getSelectedItems () {
            return this.items.filter(function (item) {
              return item.isSelected === true;
            })
          },
          toggleSelectAll: function toggleSelectAll () {
            this.isAllSelected = !this.isAllSelected;
            this.items.forEach(function (item) {
              item.isSelected = this.isAllSelected;
            }, this);
          },
          toggleSelectItem: function (item) {
            if (this.items.indexOf(item) !==-1) {
              item.isSelected = item.isSelected !== true;
              this.isAllSelected = this.getSelectedItems().length === this.items.length;
            }
          }
```

Now I create a selectable customer list by composing the behaviour
```Javascript
var customers = [{name:'Bob'},{name:'Ed'}]; 
var selectableCustomersStamp = stampit.compose(selectableItemListStamp,customerListStamp);
var instance = selectableCustomersStamp({items:customers, customers:customers});
```

Everything works fine until I call a refresh and the reference this.customers and this.items are pointing to is not the same anymore. 

It is easy to workaround: 
* change property name in customerListStamp to be "items" but it create somehow a coupling between the two stamps
* add a sync decorator on refreshList when creating a selectableCustomersList but it's somehow code to add which is not really related to functionality but more to composition mechanism 
* empty this.customers in refreshList instead of changing reference 
```Javascript
this.customers.splice(0,length).concat(newList);
```
but it is less readable and obvious (an habit to take maybe)

I wanted to know you thoughts on the topic ? maybe adding a way to say customers and items is the same thing (when Object.observer is out) when creating an instance would be a good thing ? etc

**Comment by koresar** [comment]
You are using `props`. These are for deep copying. If you want to keep references use `refs` instead (stampit v2 only).

I believe this will solve all your problems.

PS: in stampit v3 `props` will be an alias to `refs`, i.e. it will work as you expected.

**Comment by koresar** [comment]
Also, your code can be shortened and optimised. Poke me if you are interested. :)

**Comment by lorenzofox3** [comment]
Yes, please go ahead :), show me how you would do that. 

Actually I don't understand what refs are, I thought it would be references shared between all the object created by a given stamp.

**Comment by koresar** [comment]
> I thought it would be references shared between all the object created by a given stamp.
That is correct. Although, (in stampit v1 and v2) you can pass the refs to the stamp.

I'll rewrite some code using ES6. I'm surprised some people are still using ES5. :)
```js
import {methods, init} from 'stampit';

// Behaviour which demands the "this.items[]" reference to be set from the beginning
const ItemsContainer = init(function () {
  if (!Array.isArray(this.items)) throw new Error('this.items[] was not supplied');
});

// Behaviour which makes the items selectable.
const SelectableItemList = ItemsContainer.methods({
          getSelectedItems() { return this.items.filter(i => i.isSelected); },

          isAllSelected() { return this.items.every(i => i.isSelected); }
        });

const ToggleSelectableItemList = SelectableItemList.methods({
          toggleSelectAll() {
            const isAllSelected = this.isAllSelected();
            this.items.forEach(item => {
              item.isSelected = !isAllSelected;
            });
          },

          toggleSelectItem(item) {
            const foundOne = this.items.find(i => i === item);
            if (foundOne) {
              foundOne.isSelected = !foundOne.isSelected;
            }
          }
        });

// Behaviour which refreshes the the items list with the new customers list from server
const RefreshCustomerList = methods({
        refreshList() {
          callServerForRefresh().then(newList => {
              this.items = newList;
          })
        }
      });

const SelectableCustomers = ToggleSelectableItemList.compose(RefreshCustomerList);
const selectableCustomers = SelectableCustomers({ items: [{name:'Bob'}, {name:'Ed'}] });
```

1. Premature optimisation is the root of all evil. I've removed the `this.isAllSelected`.
2. I split items container, selection logic, and toggling logic.
3. I removed the `customers` property. Can't find any reason to keep it.
4. Most importantly, I remove the "stubs" you introduced for methods and properties.

Questions? :)

**Comment by lorenzofox3** [comment]
> Premature optimisation is the root of all evil. I've removed the this.isAllSelected.

It is actually required: this code is for UI (using Angular) and isAllSelected is boolean which is bound to a control. I could use the method isAllSelected() method but it is easier for debug purpose and testability to have a boolean that reflect the state.

> I split items container, selection logic, and toggling logic.

great, more readable

> I removed the customers property. Can't find any reason to keep it.

That was actually the purpose of my initial question. But you lack a bit of context:

First I had a customers list, products list, etc holding "items" as "customers", "products" which make in more explicit than a generic "items" especially for binding in the views. So important to realise is that theses properties are bound to view:

```Markup
<h2> Customer list </h2>
<ul>
   <li ng-repeat="customer in customerList.customers>{{customer.name}}</li>
</ul>
<h2> Product list </h2>
<ul>
   <li ng-repeat="product in productList.products>{{product.sku}}</li>
</ul>
```

Later I want to add selectable behaviour to this list. This behaviour is actually independent and can work on generic items so it could be reused . 

But with your solution I have introduced a coupling between customers (and products, and offers, and bank account, etc) related behaviour and the more abstract selectable behaviour.

So 
1. I have first to update CustomersStamp to use this.items instead of this.customers etc
2. I have to update all the binding in the views.

And again if later I decide to rename "items" to "itemsList" in the generic selectable behaviour then again I have to re do 1) and 2) ...

So this coupling can be very painful at the end. 

>Most importantly, I remove the "stubs" you introduced for methods and properties.

I don't understand, can you be more specific

**Comment by koresar** [comment]
Here are the stubs: 
![_question__best_approach_to_share_properties___ _issue__181_ _stampit-org_stampit](https://cloud.githubusercontent.com/assets/1622575/10930336/49b5a562-8311-11e5-9eff-293725c9be0e.png)

**Comment by koresar** [comment]
Lately Angular started to promote one-way binding. I think it's better to bind to functions that to properties. :) Although, it's up to you to decide.

If you struggle with anything - feel free to ask here. Or even in the gitter chat: gitter.im/stampit-org/stampit

**Comment by koresar** [comment]
I forgot to add. :)
`customerList.customers` - are saying "customers" word twice. I think `customerList.items` would read better. Same for `productList.products` -> `productList.items`.

**Comment by lorenzofox3** [comment]
yes you are right, thanks a lot ! 
Forcing the abstraction by 
```Javascript
const ItemsContainer = init(function () {
  if (!Array.isArray(this.items)) throw new Error('this.items[] was not supplied');
});
```
is a smart move.

Although I still feel frustrated that behaviours remain coupled due to property naming, it somehow breaks the beauty of composition.

And for the side notes :

``customerList.customers`` was only for the issue readability, behaviours are actually blended to a controller ``ctrl.customers``. 

``isAllSected`` is a one way binding (readonly). just make it easier when in debugger the var is evaluated directly and when comparing states in assertions  

But thanks again for the tips I really appreciate. Nice library to work with (a pity it keeps a big size when used in the browser)

**Comment by koresar** [comment]
> Although I still feel frustrated that behaviours remain coupled due to property naming, it somehow breaks the beauty of composition.

Fully agree. Any ideas how to avoid that?

**Comment by lorenzofox3** [comment]
Nope, hence my question :) . Maybe with Object.observe when creating object from a stamp you could say

```Javascript
   var customerSelectableList = stampit
    .compose(customerStamp, selectableStamp)
    .share('customers', 'items')
    ({customers:['bob']});
```

which would basically tells to update "items" whenever the "customers" reference changes. But yet, watchers and eventListeners can be tricky to deal with

**Comment by koresar** [comment]
1) `Object.observe` was dropped from ES7. :)
2) You could use ES6 [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get).

**Comment by lorenzofox3** [comment]
you are right. 

```Javascript

var selectableCustomers = stampit.compose(customers, selectable)
  .init(function(){
       var customers = [];

       Object.defineProperty(this,'customers',{
           get:function(){
                 return customers
           },
           set:function(values){
                this.items = values;
                customers = values;
           }
       }
   })
```

made the job :+1:

**Comment by koresar** [comment]
Yep. :) In stampit v3 this is going to be even simpler. :)

**Comment by lorenzofox3** [comment]
looking forward !
