### ISSUE TITLE
Link behind "learning about prototypal inheritance" is broken

### ISSUE THREAD

**Issue by dwiyatci** [stampit-org/stampit#182]
http://ericleads.com/2013/02/fluent-javascript-three-different-kinds-of-prototypal-oo/ currently unavailable.

**Comment by ericelliott** [comment]
Oops. Yeah, that's not coming back. We'll need to replace it. =)

**Comment by ericelliott** [comment]
PR is welcome.

**Comment by dwiyatci** [comment]
Done. =)
