### ISSUE TITLE
Accidentally overriding instance methods when passing `properties`

### ISSUE THREAD

**Issue by dwiyatci** [stampit-org/stampit#184]
Hello, 

this morning I accidentally override (or rather, hide?) one of my instance methods when passing `properties` to the factory function. It goes something like:

```javascript
var Person = stampit({
    methods: {
        greet: function() {
            console.log('hello, world');
        }
    }
});

var foe = Person({
    greet: function() {
        console.log('goodbye, world');
    }
});
foe.greet(); // goodbye, world

var friend = Person();
friend.greet(); // hello, world
```

I know the `greet` method in the prototype will be safe, but just wondering if there is any way to prevent this kinda thing from happening?

**Comment by ericelliott** [comment]
Why would you want to prevent this from happening? This is expected behavior. This is the canonical way to override delegate prototype methods...

**Comment by dwiyatci** [comment]
I guess you're right. This behaviour should be expected. I think I got mixed up a bit between concatenative and delegative prototyping. Thanks for the justification.
