### ISSUE TITLE
stampit v3 rfc: thru

### ISSUE THREAD

**Issue by boneskull** [stampit-org/stampit#188]
(examples used reflect Stampit v2 API)

Stampit currently has support for `init`, which allows you to chain initialization functions together when composing stamps:

```js
const Stamp = stampit({
  // "option" form
  init() {
    this.foo = 'bar';
  }
})
  // function-chain form
  .init(function() {
    this.foo = `${this.foo}-baz`;
  })
  // function-chain form
  .init(function() {
    this.foo = `${this.foo}-quux`;
  });

const obj = Stamp();
obj.foo // 'bar-baz-quux'
```

Each `init` function is called in the order it was defined.  Note that there are *three* stamps being created above; each function-chain call to `init()` returns a new stamp.

`init` is called with a "context" object, containing properties `instance`, `args`, and `stamp`, which are an `Object`, `Array`, and `Function`, respectively.

`init` *only applies* to object instantiation.  What Stampit currently lacks is a (convenient) way to assert control over the composition of stamps.

An example use case is *non-enumerable static properties*.  e.g.:

```js
const fooKey = Symbol();
const Stamp = stampit({
  static: {
    [fooKey]: 'bar'
  }
});
```

When the above stamp is used to compose another stamp--in any way--the property keyed on the `Symbol` `fooKey` is lost, because functions such as `Object.assign()` and the like *ignore* non-enumerable properties by definition.

```js
const fooKey = Symbol();
const Stamp = stampit({
  static: {
    [fooKey]: 'bar'
  }
});
Stamp[fooKey] // defined

const AnotherStamp = Stamp.refs({
  baz: 'quux'
});
AnotherStamp[fooKey] // undefined
```

Indeed, the only way to ensure the property keyed on `Symbol` `fooKey` makes it into composed stamps is to monkeypatch *each* of the following properties in the stamp's `fixed` property: `static`, `init`, `props`, `refs`, `methods`, `create` *and* `compose` to explicitly add the property to the new stamp:

```js
// untested, but something like this
_(Stamp.fixed)
  .filter(_.isFunction)
  .forEach((func, key) => {
    Stamp.fixed[key] = function(...args) {
      const retval = func.call(this, ...args);
      retval.fixed.static[fooKey] = 'bar';
      return retval;
    });
  })
  .value();
```

I assert the above is not user-friendly, and probably doesn't scale well.  This leads me to the following proposition:

### thru

`thru` is an option and a chainable function.  In "option" form, the property name is `thru` and the value is a user-defined function.

This user-defined function is called whenever a new stamp is composed from the stamp in which `thru` is defined.  The user-defined function is called with a single parameter, `stamp`, which is the factory function.  It should be called with the context of the stamp itself; much like in functions defined by `static`.

> The user-defined function should be called *after* the call to the method which creates a new stamp; if `methods()` is called, the user-defined function would be called with the stamp *after* a new stamp is created with the new methods.  However, I could envision a scenario in which a user wanted to run the function *before* `methods()` is called; to that end, perhaps `thruBefore()` and `thruAfter()` are appropriate.

`thru` simplifies the above two examples into something like this:

 ```js
const fooKey = Symbol();
const Stamp = stampit({
  thru() {
    this[fooKey] = 'bar'; // or maybe this.fixed.static[fooKey] = 'bar'; not sure
  }
});
```

* * *

I have the following questions:

- Is `thru` an appropriate method name?
- Should we have `thruBefore` and `thruAfter` instead?
- Should `thru` expect a returned value?

### vs ES2015 Classes

ES2015 classes are not particularly friendly to static properties, but the following still works:

```js
const symbol = Symbol();
class Foo {}
Foo[symbol] = 'bar';

class Bar extends Foo {}
Bar[symbol] // 'bar'
```

I believe `thru`--or a similar proposal--is necessary for stamps to offer an equivalent feature set to ES2015 classes.

The above may illustrate handling of non-enumerable properties is a weakness of Stampit and/or composable object factories in general.  I believe at the very least, more consideration around the topic is necessary.

**Comment by boneskull** [comment]
@ericelliott will probably spit up his coffee at this idea, but the most direct route from *A* to *B* might actually be to leverage ES2015 classes in some capacity under-the-hood to ease working with non-enumerable properties.  :imp:

**Comment by koresar** [comment]
I had a proposal to accept ES6 classes as stamps to the "compose" function:
```js
class C {};
const Foo = SomeStamp.compose(C);
```
But that's a hard task.

**Comment by koresar** [comment]
First of all, I really-really like the `thru` idea. I will add up my thoughts later.

But first, I'd like to say that [stamp specs.](https://github.com/stampit-org/stamp-specification) should support Symbols out of the box. I.e. Symbols should be treated as usual properties. @troutowicz your thoughts?

**Comment by koresar** [comment]
`thru` can be useful in some scenarios. I met so far:
1) debugging, understanding which stamps my object consists of (I got very confused once, accidentally composed same stamp twice).
2) debugging, finding out which stamp overrode my property and why (solves some other people "complains").
3) statistics - finding out how many times a stamp gets composed.
4) deprecation warnings.
5) validation (incompatibility warnings/errors, etc).

This is what [composables specs.](https://github.com/stampit-org/stamp-specification) lack. I truly believe that `thru` has to be part of the specs.

#### Proposed syntax.
Another more readable name for the `thru` method can be `postCompose`.
Similar to the `init` methods, the `postCompose` should be able to override the resulting stamp.
```js
const FooStamp = compose({ postCompose({left, right, result}) { // all three are stamps
  // logic goes here
  console.log(left, right, result);
  // ...
  return thisWillOverwiteTheResultingStamp;
} });

const AStamp = compose({ methods: { a(){} } });
const ResultStamp = FooStamp.compose(AStamp); //prints all: FooStamp, AStamp, ResultStamp
```

@troutowicz @unstoppablecarl @JosephClay @sethlivingston @yasinuslu @zebulonj thoughts?

**Comment by troutowicz** [comment]
I think a post-compose method could be useful. A use that comes to mind is logging/debugging. Right now, composition is a black box. We throw some stamps in and a new stamp might pop out if used correctly. Being able to step through each step of the composition process could make the process more verbose and easier to troubleshoot. I don't particularly care for `thru`, `postCompose` is more readable IMO.

I don't see a problem with supporting Symbols in the stamp spec.

**Comment by unstoppablecarl** [comment]
### Symbols

I have not used symbols much so I am not very familiar with the way they are used by others. Not knowing of a universal intended use, my first thought is that symbol assignment should be left up to the user. The fact that classes in js inherit symbols (including statically) should probably not be relevant in our decision to include them automatically when composing. If it is decided that they are included automatically when composing, there should be a way to disable this behavior. How much performance overhead would including symbols cause?

How should symbols be handled when creating a stamp from a constructor (are we still supporting that?). That object may have symbols that you may or may not want to carry over. 

The most strait forward solution that covers all use cases:
 - Add an (inheritable?) way to set a stamp to copy all symbols as if they were enumerable
 - Add `.symStatic()` `.symProps()` `.symRefs()` for a way to directly specify and control which symbols are set

With these two things users can use symbols in an inclusive or exclusive way.

I don't feel strongly about the symbol stuff. I have not used them extensively. Just sharing my thoughts. I do think symbols should have their own tools and not have a composition function be the only way to handle them.

### Stamp Composition Functions

I could see many use cases for this and it is worth including in the spec. The name `thru` is not very communicative of what it does `postCompose` is much better but I would prefer `.initStamp()` or `.afterComposed()`

In the examples given so far the `.postCompose()` method is not composable itself right? It is only called on the first stamp in the list to be composed. So you would not be able to compose or inherit that behavior. Is this intended? Maybe I am not understanding.

What would the before / after functions do exactly? I can only think of use for a function that has a chance to make changes to the stamp before returning it when creating / composing stamps.

### Composable Stamp Composition Functions (Proposal)

Add `.initStamp()` method to stamps. It behaves exactly the same as `.init()` as far as setting, storing, and composing goes (internally stored as an array of functions, these arrays are concatenated when composing stamps). When a stamp is composed / created, after all other composition behavior (including merging the `initStamp` array), each function in the `initStamp` array is called on the resulting composed stamp. Each function is expected to return the same or new stamp to be passed to the next function in the array etc. No intermediate stamp objects are created maintaining non-enumerable properties on the stamp.

**Comment by unstoppablecarl** [comment]
I just did some experimenting. In node `v5.0.0` `Object.assign()` **does** merge symbol properties.

**Comment by boneskull** [comment]
If the purpose of stamps is to allow you to use them wherever you would otherwise use ES2015 classes, then what ES2015 classes do with objects (including how they handle Symbols) is relevant to the conversation.  

However, it's not really about Symbols per se--it's about *any* non-enumerable property.

**Comment by boneskull** [comment]
I am curious about just what the hell `Object.assign()` is up to in v5, however.

**Comment by boneskull** [comment]
I haven't looked at the spec there, but I imagine that's what `Object.assign()` is supposed to do.  

```js
const obj = {
  [Symbol.iterator] = function *() {
    // ..
  }
}
Object.assign({}, obj) // I would expect the iterator to work
```

**Comment by koresar** [comment]
I believe in node v5 is working according to the standard
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by unstoppablecarl** [comment]
@boneskull 
> If the purpose of stamps is to allow you to use them wherever you would otherwise use ES2015 classes, then what ES2015 classes do with objects (including how they handle Symbols) is relevant to the conversation.

I do not know if that is the intent or not. I do not have a strong opinion one way or the other to be honest. The intent should be decided and written in the docs somewhere to keep everyone on the same page and be consistent.

As I said above I am not sure **what** the universal / general intended use case for symbol properties is (static or instance). I suppose if it is intended to be inherited when extending classes, and copied when using `Object.assign()`; it would seem the intent is for them to behave the same as normal properties as far as object creation is concerned. Then again if that were the intent, why are they specifically excluded from `Object.getOwnPropertyNames()` and `Object.keys(obj)` and `for(var key in foo)`. The more I dig into symbols the less I understand how you would use them. I get that they are a unique key which is nice but why do they behave differently from string property keys?

**Comment by koresar** [comment]
> why are they specifically excluded from `Object.getOwnPropertyNames()` and `Object.keys(obj)` and `for(var key in foo)`.

Because TC39 do not want to break the web. In other words: because compatibility

**Comment by JosephClay** [comment]
@unstoppablecarl What I understand of symbols is that they're a way to make properties "private" in javascript's class-ish-based programming, since privacy via encapsulation is lost. It's privacy via obscurity.

**Comment by koresar** [comment]
yep. Quoting the link above about the `Object.assign`:
> Both String and Symbol properties are copied.

**Comment by boneskull** [comment]
@JosephClay That is one thing that you can (sort of; see below) use a `Symbol` for, but they also allow you to define the iteration behavior of an object (the `for ... of` syntax), among other things.  I think that may be the "main" purpose of a `Symbol`.

If an object has a `Symbol` property, it can be accessed via `Object.getOwnPropertySymbols()`, so it doesn't really make anything private.  

AFAIK, the only way to achieve privacy is still via scope, whether that be a closure or use of a `WeakMap`.

**Comment by koresar** [comment]
This is being further discussed (and then implemented in stampit v3) here: https://github.com/stampit-org/stamp-specification/issues/63

Feel free to discuss if any.

**Comment by koresar** [comment]
The same goal can be achieved using this new feature: https://github.com/stampit-org/stamp-specification/pull/71
```js
  let counter = 0;
  function newCompose(...args) {
    counter++;
    return compose({staticProperties: {compose: newCompose}}, this, ...args);
  }
  newCompose().compose().compose();
  console.log(counter); // 3
```
