### ISSUE TITLE
jsnext:main

### ISSUE THREAD

**Issue by boneskull** [stampit-org/stampit#189]
maybe include a `jsnext:main` field in `package.json` which points to `src/stampit.js`?

[explanation](https://github.com/rollup/rollup/wiki/jsnext:main)

**Comment by koresar** [comment]
Easy! will you submit a PR?

**Comment by boneskull** [comment]
k

**Comment by BerkeleyTrue** [comment]
If it is for the purpose of Tree Shaking with Rollup/webpack 2, then it will need to be more than just point to original ES2015 code. You'll need to create a new directory were all the ES2015 code is transpiled with the exception of ES2015 modules.

**Comment by boneskull** [comment]
I think I'm going to pass on this.  I was trying to get rollup to work for me, but it was too painful.

**Comment by koresar** [comment]
Feel free to create new issue. Thanks for the attempt Christopher

**Comment by boneskull** [comment]
> If it is for the purpose of Tree Shaking with Rollup/webpack 2, then it will need to be more than just point to original ES2015 code. You'll need to create a new directory were all the ES2015 code is transpiled with the exception of ES2015 modules.

Anyway, if I *did* look at this, I'm not understanding what @BerkeleyTrue is saying here.   Create a new directory? Put what there? There's only one source file.
