### ISSUE TITLE
Contribution Protocol

### ISSUE THREAD

**Issue by recursivefunk** [stampit-org/stampit#190]
Didn't see any docs or anything that addresses how to propose new features. Will a PR suffice? Thanks in advance!

**Comment by koresar** [comment]
Hello.
We do usual "github way". Just create an issue. :)

**Comment by recursivefunk** [comment]
Haha cool just wanted to make sure. Thanks :+1:

**Comment by koresar** [comment]
If you feel the contribution protocol should be reflected somewhere then a PR is fine. Somewhere at the end of README is the proper place to have it I think.
