### ISSUE TITLE
Interface Adherence Feature

### ISSUE THREAD

**Issue by recursivefunk** [stampit-org/stampit#191]
I've been spending some time working on a JS [interface adherence utility](https://github.com/recursivefunk/nyce). I've been using stampit for a few months now and it occurred to me that an optional interface adherence enforcement feature could perhaps be useful. Maybe look something like this:

```javascript
import someComponent from './someComponent';
import anotherComponent from './anotherComponent';

stampit({
  foo(),
  bar()
})
.adhere(myInterface)
.compose(
  someComponent, 
  anotherComponent
);
```

**Comment by koresar** [comment]
Hey, you can use "static" feature to compose that behavior into your stamps. No need to change stampit. :)

e.g.:
```js
stampit(foobar).compose(Adhere).adhere(myInterface).compose(someComponent)
```
or even
```js
Adhere.compose(foobar, someComponent)
```

**Comment by koresar** [comment]
We call stamps like that "an utility stamp". We even have a early stage project for them: https://github.com/stampit-org/stamp-utils

**Comment by recursivefunk** [comment]
Very cool! Yep that's definitely a better approach than hacking at core. Thanks for the feedback! @koresar I'll close this out!

**Comment by koresar** [comment]
A sample composable stamp could look like this (please, feel free to expand it):
(stampit v2 only)
```js
const Adhere = stampit()
.static({
  adhere(myInterface) {
    this.fixed.refs.nyceSchema = myInterface;
  }
}).init(() => {
  if (this.nyceSchema && !nyce.validate(this, this.nyceSchema)) {
    throw new Error("Bad object :(");
  }
});
```

It will be even better in stampit v3.

More insight in the [advanced examples](https://github.com/stampit-org/stampit/blob/master/docs/advanced_examples.md#validate-before-a-function-call).

**Comment by recursivefunk** [comment]
Ah that's very helpful! :+1:
