### ISSUE TITLE
A few questions regarding encapsulation

### ISSUE THREAD

**Issue by eshansingh** [stampit-org/stampit#193]
**Disclaimer**: I am completely new to JavaScript and come from a classical OO language (C#), so that could be confusing me.

I understand that you can make a private variable like this:

```js
var someObj = stampit().init(function() {
    var privateVar = true;
}).create();
```

And I can make a private method like this:

```js
var someObj = stampit().init(function() {
    var getIt = function privateMethod() {
        return "Stamp{it}";
    }
}).create();
```

But how do I access a private variable or function from a "public" function? As in:

```js
var someObj = stampit().init(function() {
    var getIt = function privateMethod() {
        return "Stamp{it}";
    }
    var hellaImportantVar = "yes!";
})
.methods({
    getTheThing: function getCoolThing() {
        return getIt(); // This part doesn't work - it isn't defined.
    }
    explode: function expolde() {
        return hellaImportantVar; // Again, this doesn't work.
    }
})
.create();
```

**Comment by maiermic** [comment]
Only privileged methods have access to private variables or functions. A privileged method is a function that is assigned to `this` in `init`. For further information see [What's the Point](https://github.com/stampit-org/stampit#whats-the-point). I suggest to read [Private Members in JavaScript](http://www.crockford.com/javascript/private.html) by Douglas Crockford to get a better understanding.

**Comment by eshansingh** [comment]
But then I'm forced to write behaviour methods in what is supposed to be analougous to a 'constructor', if I'm correct.

**Comment by BerkeleyTrue** [comment]
@eshansingh 

```js
var someObj = stampit().init(function() {
    var privateVar = true;
}).create();
```
This variable is private, but it is also completely isolated. Once the init function is called, it will be lost. 

```js
var someObj = stampit().init(function() {
    var getIt = function privateMethod() {
        return "Stamp{it}";
    }
}).create();
```
Same goes for this function. It is lost because its reference is not assigned to anything other then a scoped variable inside the init function.

To create a private variable accessible to a method do something similar to the following:

```js
const a = stampit().init(function() {
  const priv = 'a'; 
  this.getA = () => { // method is assigned to the instance of this stamp
    return priv; // now variable is part of the closure of this method
  };
});
```

You can extend this example to include private methods:

```js
const a = stampit().init(function() {
  let count = 0;
  function resetCount() {
    count = 0;
  }
  this.incCount = () => {
    count = count + 1;
    if (count > 10) {
      resetCount();
    }
    return count;
  };
});
```

If you're feeling fancy, you can use ES2015 Symbols to create private variables:
```js
var count = Symbol('count');
var a = stampit({
  init: function() {
    this[count] = 0;
  },
  methods: {
    incCount: function() {
      this[count] = this[count] + 1;
    },
    printCount: function() {
      console.log(this[count]);
    }
  }
});
``` 

or ES2015 WeakMaps:
```js
var count = new WeakMap();
var a = stampit({
  init: function() {
    count.set(this, 0);
  },
  methods: {
    incCount: function() {
      count.set(this, count.get(this) + 1);
    },
    printCount: function() {
      console.log(count.get(this));
    }
  }
});
```
Here is a [JSBin](http://jsbin.com/yiluqe/1/edit?js,console)
Showing both of this methods in action. I wrap them in IIFE's there so that the variable holding the count symbol/map is inaccessible but you could do without if you use CJS/ES2015 modules.

Here is a great article on private data using these new methods http://www.2ality.com/2016/01/private-data-classes.html

**Comment by ericelliott** [comment]
Related: ["Master the JavaScript Interview: What is a Closure?"](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-closure-b2f0d2152b36#.7y59iaduy)

**Comment by eshansingh** [comment]
Wow, thanks! The Symbols thing is really good for this.

**Comment by ericelliott** [comment]
We should probably add the symbols example to the docs, and link to ["Master the JavaScript Interview: What is a Closure?"](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-closure-b2f0d2152b36#.7y59iaduy) so people can easily read up on how data privacy works in JS.

**Comment by BerkeleyTrue** [comment]
@ericelliott I'm happy to add it. Where in the docs do you want it added? Do you also want to include the WeakMap version?

**Comment by koresar** [comment]
I'd love to read an article on: "Several ways to implement privacy in ES2015".
@ericelliott I reckon it'll get a lot of traffic. It's a very hot topic currently.

**Comment by eshansingh** [comment]
@koresar Agreed. To a lot of people, it's still not clear. And the `class` keyword just adds more confusion to the mix.
