### ISSUE TITLE
Creating instance does not call setters defined within init

### ISSUE THREAD

**Issue by lorenzofox3** [stampit-org/stampit#195]
I am creating a dummy validation decorator like so:

```Javascript
function decorator (validationSchema) {

  const symbols = {};
  const schemaKeys = Object.keys(validationSchema);

  schemaKeys.forEach(prop => {
    symbols[prop] = Symbol(prop);
  });

  return stampit()
    .init(function (ctx) {
      schemaKeys.forEach(prop => {
        Object.defineProperty(this, prop, {
          enumerable:true,
          get: function () {
            return this[symbols[prop]];
          },
          set: function (value) {
            const validationFunc = validationSchema[prop];
            this.isValid = validationFunc(value);
            this[symbols[prop]] = value;
          }
        });
      });
    });
}
```

the problem is that an object created by the returned stamp does not call the setter when creating the object

```Javascript
const stamp = decorator({
    foo:function(input){ 
        return input === 'foo';
    }
})

const instance = stamp({foo:'blah'})

instance.foo // undefined -> not ok
instance.isValid // undefined -> not ok

instance.foo = 'boom' 

instance.foo // 'boom' -> ok
instance.isValid // false -> ok
```

I managed to workaround the problem with another init stamp manually assigning property based on context.instance but it is not ideal. 

Do you think we could work on improving the merge strategy when creating a new object ?

**Comment by koresar** [comment]
Hi @lorenzofox3 
That's an extraordinary new finding!

Do you have a code sample on how one would improve the merge strategy? The PR would be ideal, but a tip on how you see it implemented would work too.

Btw, looks like stampit v3 will have that issue solved in a bit different way. Here is the [LOC related](https://github.com/stampit-org/stampit/blob/v3_0/src/compose.js#L24).

**Comment by ericelliott** [comment]
Init functions run after assignments by design. Usually, you need the properties to be set to have data available for the init functions to do things with.

This use-case seems like a valid argument for `propertyDescriptors` to be attached to the instance *prior to* `properties` and `deepProperties`.

How far are we away from a 3.0 release, @koresar?

**Comment by koresar** [comment]
The code is ready. It's working. It lacks couple of tests for some corner cases.
Also, it lacks utility functions like convertConstructor, and the rest from #163.

I want to publish first beta (but do not tag it as `@latest`). Then make sure it's stable. Then publish stampit v3.0. Then add the utility functions one by one and publish 3.1, 3.2, 3.3, and so on.

**Comment by lorenzofox3** [comment]
yes you are right it is actually more about assignment and merge timing rather than the merge strategy.
Giving the ability of defining property descriptors on a stamp (ie before any instance is created) could solve the problem. Maybe by defining getter/setters on the methods object although I am not sure defining properties on the prototype is a good idea
