### ISSUE TITLE
unexpected "props" behavior

### ISSUE THREAD

**Issue by boneskull** [stampit-org/stampit#198]
Given `graphable.js`:

```js
import stampit from 'stampit';
import {DepGraph} from 'dependency-graph';

const Graphable = stampit.convertConstructor(DepGraph);

export default Graphable;
```

and:

```js
import stampit from 'stampit';
import Graphable from './graphable';

const Thing = stampit({
  init() {
    this.depGraph = this.depGraph || Graphable();
    this.depGraph.addNode('foo'); // <--
  }
});

const thing = Thing();
```

The line marked with the arrow will *not* throw an exception.

However, changing the second snippet to the following will throw an exception at the line marked with the arrow (`this.depGraph.addNode is not a function`):

```js
import stampit from 'stampit';
import Graphable from './graphable';

const Thing = stampit({
  props: {
    depGraph: Graphable()
  },
  init() {
    this.depGraph.addNode('foo'); // <--
  }
});

const thing = Thing();
```

`this.depGraph.addNode` evaluates to `undefined`.  Properties set by the original `DepGraph` constructor function *are* present.

A different "deep cloning" method results in an object with such a function:

```js
typeof require('lodash').cloneDeep(Graphable()).addNode // function
```

Where'd the prototype go, and why?

**Comment by koresar** [comment]
stampit is using `_.merge` not `_.clone`.
```
$ node
> function F(){}
undefined
> _.merge({}, {foo: F});
{ foo: { [Function: F] } }
> var f = new F();
undefined
> _.merge({}, {foo: f});
{ foo: {} }
```

Anything you believe can be improved in this regards?

P.S. Sorry for the late reply. Was on a business trip.

**Comment by boneskull** [comment]
@koresar from the API docs:

> @param {Object} [options.props] An object to be deeply cloned into each newly stamped object.

So, yeah, it should do what it says it does. :smile:

**Comment by koresar** [comment]
Oh, bloody wording! I'll fix that doc. ☺

**Comment by ericelliott** [comment]
My bad.

**Comment by boneskull** [comment]
Lame.  I wanted it to deeply clone.  Maybe move any further chatter to stampit spec org?

**Comment by koresar** [comment]
@ericelliott while you are online, could you please jump to the Gitter chat or Twitter DM? There is a question for you there. Thanks!

**Comment by boneskull** [comment]
(is it a *shallow* clone at this point?)

**Comment by koresar** [comment]
It's a deep merge as in `_.merge`.

**Comment by koresar** [comment]
Fixed https://github.com/stampit-org/stampit/blob/master/docs/API.md
