### ISSUE TITLE
Object.defineProperty

### ISSUE THREAD

**Issue by wladimiiir** [stampit-org/stampit#200]
Hi,
I am using BabylonJS library and I would like to create Scene object with some extensions. I am trying to use stampit to create a factory and extend the Scene. The Scene has constructor with parameter and also it uses Object.defineProperty to define some getters and setters.
I tried to use convertConstructor function, but this seems to not copy the properties defined by Object.defineProperty.

I have created a JSFiddle which mimics the problem so you can see for yourself:
[Fiddle](http://jsfiddle.net/6bkeejtd/1/)

I am not sure if this a bug or this is correct behavior and what I am trying to achieve is not possible using stampit. Therefore I would appreciate any inputs from creators and more experienced users :)

Thank you.

**Comment by koresar** [comment]
Hello mate.

Bad news - latest stampit does not support Property Descriptors.
Good news - it is possible with stampit v3 (not yet released). Even though v3 is not released, you can have all features of it using the [stamp-specification](https://www.npmjs.com/package/stamp-specification) module. Few words about it.

Stampit will be based on the small [60 LOC code](https://github.com/stampit-org/stamp-specification/blob/master/compose.js) *core* which is called `stamp-specification`. And stampit itself will be "stamps on steroids" bringing nice end-user API similar to the current.

Using the `stamp-specification` as the base you can implement the `Car` example like so:

```js
import compose from 'stamp-specification';
const Car = compose({
    initializers: [function({engine}) {
        this._engine = engine;
    }],
    propertyDescriptors: {
        engine: {
            get() {
                return this._engine;
            }
        }
    }
});

const car = Car({engine: 'ENGINE!'});
console.log("Engine OK: " + car.engine);
```

In stampit v3 it would look like so:
```js
import stampit from 'stampit';
const Car = stampit
    .override({_engine: 'engine'})
    .defineProperties({
        engine: {
            get() {
                return this._engine;
            }
        }
    });
```

**Comment by wladimiiir** [comment]
Hi,

thanks for the answer, but I didn't make it clear enough. 

The Car constructor from the [Fiddle](http://jsfiddle.net/6bkeejtd/1/) is example of Scene object from BabylonJS. So that means I cannot change the Car in a way of using stampit :(
That`s why I relied on convertConstructor function. The question is if convertConstructor in v3 will also be able to support Property Descriptors or maybe there is some other way?

Thanks.

**Comment by koresar** [comment]
Ah, I see. Sorry for the confusion.

The `converContructor` of the stampit v3 is going to support Property Descriptors.

Another way to convert the Car to a stamp would be this:
```js
var Car = (function () {
    function Car(engine) {
        this._engine = engine;
    }

    Object.defineProperty(Car.prototype, "engine", {
        get: function () {
            return this._engine;
        }
    });
    return Car;
})();

var stampit = require('stampit');

var carConstruct = stampit.convertConstructor(Car).init(function () {
    Object.defineProperty(this, "engine", {
        get: function () {
            return this._engine;
        }
    });
});
var constructCar = carConstruct(null, {power: 15});
console.log(constructCar.engine);
```

**Comment by wladimiiir** [comment]
Thank you.
