### ISSUE TITLE
EventEmitter and stampit object

### ISSUE THREAD

**Issue by eddyLazar** [stampit-org/stampit#201]
What is the best "stampit" way to mixin stamp with node EventEmitter ?

I tried using `convertConstructor` feature, but resulting object doesn't works properly

**Comment by JosephClay** [comment]
We have an example of using EventEmitter with `convertConstructor` [here.](https://github.com/stampit-org/stampit/blob/ef79e4fbd1570648eb86c9b1604eb12fafe9a837/advanced-examples/event-emitter.js) 

There is also [stampit-event-bus](https://github.com/Cloud-Automation/stampit-event-bus) as an alternative.

**Comment by koresar** [comment]
There was a similar problem a while ago. https://github.com/stampit-org/stampit/issues/148
The issue was that with node 0.12 they introduced the `init()` static function to the `EvenEmitter` class which collides with stampit's `init()` static method.

@eddyLazar can you show us your error?

**Comment by eddyLazar** [comment]
It seems i've been using some other emitter library, with node 'events' everything works properly. Thanks for reply.
