### ISSUE TITLE
Stamp Check

### ISSUE THREAD

**Issue by namirsab** [stampit-org/stampit#202]
Hello everybody
I'm not sure if this is the channel to post questions, but I have one :smile: 
Is it possible to check if an object is "implementing" or "composed by" or "whatever" a given stampit?
```javascript
// Something ike this
stampit.isComposedBy([stamp1, stamp2]);
```

**Comment by ericelliott** [comment]
You should prefer duck typing over checks like this. `instanceof` is not trustworthy (even if you use classes), and name-flagged checks can give you false negatives when an object is structurally compatible. Duck typing solves those issues.

**Comment by koresar** [comment]
Hello @namirsab. Eric is correct. The best way is to do ducktyping. Like:
```js
if (rabbit.run) rabbit.run();
```

Although, I understand it's very hard to do that kind of mind shift from `instanceof` to ducktyping. You might find few examples for yourself in Advanced Examples: https://github.com/stampit-org/stampit/blob/master/docs/advanced_examples.md

**Comment by koresar** [comment]
Feel free to ask further questions mate. :) 
I'll close this issue now since this repo is not the best place to ask that kind of questions.

Cheers

**Comment by namirsab** [comment]
@ericelliott @koresar thanks  a lot. I was wondering if there was any "duck typing" check for stampits (I mean internally using duck typing checks or something like this). Anyway, thanks for your answers
PS: I will be using your library sooner than later in my company, so i would like to know where is the best place to ask some (i hope not many) questions :smile:

**Comment by koresar** [comment]
The best and fastest way would be the gitter chat: https://gitter.im/stampit-org/stampit

I'm closing this one. Feel free to open new issues in https://github.com/stampit-org/stampit though.
