### ISSUE TITLE
How to describe the contract between separate stamps?

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stampit#203]
Ok so I decided to give this a try, but I have some questions. Currently I am trying to create small library with some public API. There will be some separate concerns, but everything is exported under single factory function. I went to it like this

```
import stampit from 'stampit';

import Tree from './tree';
import Subject from './subject';

export default stampit().compose(
    Tree, Subject
);
```

I like this as the entry file, it looks so nice and tidy. Now about those separate stamps. The top factory function is supposed to receive a single argument with _persistence adapter_. This will be used in all those stamps. How should I handle that? Should I simply assume in a stamp it's present there?

```
export default stampit().methods({
    importTree(treeDefinition) {
        // do the import
        this.adapter.storeTree();
    }
});
```

I don't like much the fact, that stamp suddenly expects some `this.adapter` which isn't clearly specified anywhere in there. It makes the contract somewhat fragile. I am thinking if it's alright to have the Adapter stamp and compose it multiple times into the mix so it would be defined on level of separate stamps that are actually using the adapter.

**Comment by FredyC** [comment]
So I essentially tried to do this:

    const Tree = compose(Persist);
    const Subject = compose(Persist);

Each in separate file so I can clearly see in that file dependencies. However there is a problem with `init`.

    const Persist = init(({ instance, args: [adapter]}) => {
	instance.adapter = ensureAdapter(adapter);
    });

This causes it to be run twice or even more times when required in other stamps. How else I can solve it? It doesn't make much sense to me to have everything in entry point stamp only. It even makes tests harder as I have to add dependent stamps into the mix when testing them separately.

**Comment by koresar** [comment]
Hi Daniel. Sorry for the late reply.

There was a proposal to remove duplicate initializers. Although, removing duplicate initializers have side effects.

That's how I do it currently:
```js
const HaveAdapter = init(({ instance, args: [adapter]}) => {
    instance.adapter = instance.adapter || ensureAdapter(adapter);
});

const Tree = stampit()
  .compose(HaveAdapter)
  .methods(...);

const Subject = stampit()
  .compose(HaveAdapter)
  .methods(...);
```

**Comment by FredyC** [comment]
Thanks, I guess that will work, although it's gonna be ugly for initializer which are not supposed to remember anything. It will create unnecessary clutter.

**Comment by koresar** [comment]
@FredyC One last thing.
On that "initializers which are not supposed to store anything on instance" do you have any real world example? If so, could you please share it? We'd love to solve it in one of our future releases.

**Comment by FredyC** [comment]
@koresar For example initializer which does asynchronous call and returns a promise. You don't need to store anything on instance in that case.

**Comment by koresar** [comment]
In stampit if an initializer returns a value then this value overrides the instantiated object. See this example:
```js
const Stamp = stampit()
.refs({ a: 1 })
.init(function () {
  return "1234";
});

console.log(Stamp()); // Prints the string "1234", but a usual object
```

One can override the instantiated object by retuning a value from an initializer. So, the Promise example you have in mind can be implemented like this:
```js
const ComposeMeMultipleTimes = stampit().init(function() {
  if (typeof this.then === 'function') return;
  return new Promise(function (resolve, reject){ ... });
});

const Stamp = stampit().compose(ComposeMeMultipleTimes, ComposeMeMultipleTimes, ComposeMeMultipleTimes, ComposeMeMultipleTimes);

Stamp().then(...).catch(...);
```

If you have any other example of "initializers which are not supposed to store anything on instance" I'd be glad to hear it. Thanks!

**Comment by FredyC** [comment]
Hm, if I understand correctly, this won't work if there is actually more initializers where each runs its own async operation and returns promise, right? With that condition it would just run first one, right? Unfortunately I will surely need multiple async initializers.

**Comment by koresar** [comment]
> Hm, if I understand correctly, this won't work if there is actually more initializers where each runs its own async operation and returns promise, right? With that condition it would just run first one, am I correct? Unfortunately I will surely need multiple async initializers.

Apologies. I should have mentioned that stampit v2 actually natively supports Promises in multiple initializers (here is the [API link](https://github.com/stampit-org/stampit/blob/master/docs/API.md#examples)). See these tests for example: https://github.com/stampit-org/stampit/blob/master/test/promise-init.js#L163

But, upcoming stampit v3 won't support Promises natively due to following reasons:
1) None is using that async feature of stampit v2. So we're dropping the support and removing that huge chunk of useless code.
2) In stampit v3 one can easily overcome the missing feature with few additional lines of code. Show me your example, I'll show you how to easily implement the limitation using few different approaches. :)
3) Classes do not natively support multiple promises in constructor. Let's know the difference between chalk and cheese. Sync is sync, async is async.

I am eager to see your real world example of "more initializers where each runs its own async operation and returns promise". Your example could help us to shape up the stampit's future. Thanks for your help!

-----

In regards to the `instance.then` vs `this.then`.
Actually, the `instance` and `this` is the same object reference. See [examples on the API](https://github.com/stampit-org/stampit/blob/master/docs/API.md#example) page.

**Comment by FredyC** [comment]
> None is using that async feature of stampit v2. So we're dropping the support and removing that huge chunk of useless code.

I am certainly using it! I kinda like an idea of calling a factory, obtaining promise that will tell me when everything is ready and giving me the actual API object that way. This is great as you cannot actually use any methods till init promises are finished so you don't need to do any checking in those methods. In my opinion much less error prone approach than creating object with factory and then calling some manual `init` method to start async operations.

> I'll show you how to easily implement the limitation using few different approaches. :)

For now it's quite simple, essentially sort of ORM. Bunch of separate stamps like Tree, Subject, Node and each one wants to load it's data from the persistence adapter upon initialization. It will be memory first approach, so it will load everything, work with data in memory and persist in background. Thus it's only needed to wait during initialization, not anytime later.

> Classes do not natively support multiple promises in constructor. Let's know the difference between chalk and cheese. Sync is sync, async is async.

And is that wrong ? These are not classes, so why it cannot offer something extra that classes cannot possibly offer? Is there any chance to support that functionality through the stamp? If not, I strongly object against removing it unless you convince me there is 'easy' way how to do it with all that requirement I have.

**Comment by koresar** [comment]
> If they are truly the same, why to have the instance there?

For convenience with ES6 fat arrow syntax.

> Is there any chance to support that functionality through the stamp?

Easy.
I'll add this to the feature requests list I have. Your example proved that the feature is actually needed. Thank you very much.

**Comment by rickmed** [comment]
@koresar I'm having similar needs. Maybe adding an asyncInit descriptor to keep things explicit/lean? or providing a separate plugin that overrides the standard sync init?

cheers

**Comment by ericelliott** [comment]
I handle situations like this with dependency injection or shared module imports. You don't have to do everything with stamps.

**Comment by koresar** [comment]
@rickmed it can definitely be a composable behaviour. But I have no free cycles to implement that in the coming month or so. Sorry about that.

**Comment by koresar** [comment]
@rickmed if you need that feature, please tell people about it here: https://github.com/stampit-org/stamp-specification/issues/109
The more opinions we have there the better. Thanks!

**Comment by koresar** [comment]
Done
