### ISSUE TITLE
Alternative to `instanceof` check ?

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stampit#204]
I am wondering how this could be approached with stamps. I have created something like simple models with stamps:

	export default Model.compose(
		Getter('id'),
		Property('treeId'),
		Property('active', true)
	);

I kinda like it this way, it automatically creates getter/setter methods for me with actual data hidden in property identified by the Symbol ([see current implementation](https://gist.github.com/FredyC/3a1bac834c971f604b8bfac4a6f813c4#file-model-stamp-js))

I would like to add some invariant checks for development to verify that correct model is passed in. I suppose that I have to create and store some identifier of that object along with custom method. Is there some other way?

**Comment by FredyC** [comment]
Alright, I've got it. Luckily I noticed that v2 supports statics too, that helped a lot. Now I can simply write `invariant(TreeModel.isCreatorOf(tree), 'tree model expected')` and it works like magic :) [Here it's implemented](https://gist.github.com/FredyC/3a1bac834c971f604b8bfac4a6f813c4#file-model-stamp-js-L11)

**Comment by koresar** [comment]
Well done! 👍 

Here is another way to implement it: https://github.com/stampit-org/stampit/blob/master/docs/advanced_examples.md#attach-function-to-prototype-memory-efficient

**Comment by FredyC** [comment]
Thanks, but I am not sure how could that help me. At first I was thinking in that direction too, storing stamp reference in `init` a using instance method to check it. However usually I just have an object which might be even null or something and I would need to check if it actually has that checking method before invoking it. 

In the end I had to go with static method. That doesn't have access to final stamp object thus creating private Symbol to identify this was only good way to go. That's also the spot where I found out about [supermixer issue](https://github.com/stampit-org/supermixer/issues/6) and instead simple `refs({ [mySymbol]: true })` I had to go with that ugliness `init(({ instance }) => { instance[mySymbol] = true; })`.

**Comment by koresar** [comment]
I would highly recommend to avoid `instanceof` checks in your code altogether. This is an often asked feature, we deliberately [not implementing](https://github.com/stampit-org/stampit/issues/163#issuecomment-166116943) `instanceof`. Every time people ask it - we [suggest](https://github.com/stampit-org/stampit/issues/202#issuecomment-211618494) duck typing as more robust solution. And [here](https://medium.com/javascript-scene/common-misconceptions-about-inheritance-in-javascript-d5d9bab29b0a#.3yu8lpyah) is why.

If you really-really sure you need it, then you can implement a simpler `isInstanceOf` static function without any need for Symbols.

stampit v2:
```js
const IsInstanceOf = stampit({ static: {
  isInstanceOf(obj) {
    return this.fixed.methods === obj.__proto__;
  }
}});
```
stampit v3:
```js
const IsInstanceOf = stampit({ static: {
  isInstanceOf(obj) {
    return this.compose.methods === obj.__proto__;
  }
}});
```

**Comment by FredyC** [comment]
I like my approach with Symbol because it's universal. With so much changes coming in v3, I don't want to end up rewriting everything. Actually how close we are you to releasing v3? Is it matter of weeks or something much longer?

Duck typing is nice - sometimes, but in my case would be horrible. Since all my models have the ˙id˙ property, I would need to check for some other property. I would need to do something like `invariant(obj && obj.getTreeId)`. Anybody looking at that code would think all but nice things about me :) Since I am doing this check purely for validating input into method, there isn't really any relevant method or property to check.

**Comment by koresar** [comment]
Thanks for the explanation.

Stampit v3 was the matter of weeks few months ago. I can an RC0 any day now though.

**Comment by FredyC** [comment]
That would be nice, I am more willing to change to v3 now before I write most of stuff in v2 so I can help out with polishing it.

**Comment by koresar** [comment]
Stampit Release Candidate v3-rc.0 was just released. `npm i stampit@rc`
https://github.com/stampit-org/stampit/tree/v3_0
