### ISSUE TITLE
Examples and use cases gathering

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stampit#205]
Let's use this issue to gather intelligence and one day it can become a comprehensive list of organized resources.

https://github.com/stampit-org/stampit/blob/master/docs/API.md
https://github.com/stampit-org/stampit/blob/master/docs/advanced_examples.md#mocking-in-the-unit-tests
https://gist.github.com/FredyC/3a1bac834c971f604b8bfac4a6f813c4
https://medium.com/@koresar/fun-with-stamps-episode-1-stamp-basics-e0627d81efe0#.czz7jonly

**Comment by koresar** [comment]
Closing this one as not an issue.

Basically, 
* for news please follow [stampit_org](https://twitter.com/stampit_org) on Twitter.
* for new development news and some examples follow [Fun With Stamps](https://medium.com/@koresar) (my medium.com blog)
* for some variety of examples read the official [API](https://github.com/stampit-org/stampit/blob/master/docs/API.md) doc.
