### ISSUE TITLE
Stampit shortcut methods -> ES6 separate exports?

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#206]
Multiple people are asking the same question: 
> Why is the coding style so inconsistent - `stampit({methods: ...})` in some places, and `stampit.methods({ ... })` in other places?

Cons:
 - Confusing! Poor docs in general.

Pros:
 - these are shortcut methods. Here is the sample usage:
```js
var methods = require('stampit').methods;
var Stamp = methods({ myMethod() {} });
```
But with ES6 import/export feature we might want to detach them from `stampit` object and export separately.
```js
export default stampit;
export const methods = (...args) => stampit().methods(...args);
```
And usage:
```js
import {methods} from 'stampit';
const Stamp = methods({ myMethod() {} });
```

Thoughts?

**Comment by ericelliott** [comment]
My vote is the ES6 import.

**Comment by koresar** [comment]
Released in stampit v3 RC9.
