### ISSUE TITLE
[v3] compose() should accept descriptor according to spec

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stampit#207]
Or did I misunderstood how is that meant? https://github.com/stampit-org/stamp-specification#composable

I tried this, but initializer is never invoked.

```
export default Model('Tree').compose(
	Property('name'),
	Property('description'),
	{
		initializers: () => console.log('ok');
	}
)
```

**Comment by koresar** [comment]
Initializers must be an array. The specs should mention that though.

This will work:
```js
initializers: [() => console.log('ok')]
```

**Comment by koresar** [comment]
Do you think this change is enough?
https://github.com/stampit-org/stamp-specification/pull/87
Where else we should state that it must be an array?

**Comment by FredyC** [comment]
Um, I am confused how, why it needs to be an array? This has never been a need in v2 and I can even do this and that works correctly. Wrapping to array just seems completely unnecessary step.

```js
export default Model('Tree').compose(
	Property('name'),
	Property('description'),
	stampit({
		initializers: initializeTreeModel,
	})
);

```

**Comment by FredyC** [comment]
Or perhaps it will be less misleading since it's plural, not singular. I just realized I can do fancy stuff like this and avoid hassle of typing explicit array there. I am really starting to love this :)

```js
function Initialize(...initializers) {
	return stampit().initializers(initializers);
}

export default Model('Tree').compose(
	Initialize(initializeTreeModel),
	Property('name'),
	Property('description'),
);
```

**Comment by koresar** [comment]
Instead of the function you wrote yourself you can use `stampit.init(initializers)`.

Also, if you use "statics" feature:
```js
const SetupPropertyName = stampit().statics({
  setupPropName(...propNames) {
    return this.compose(...); // need to see the Property func. to implement this line
  }
});
```
you can implement the following syntax:
```js
export default Model('Tree').compose(
    Initialize(initializeTreeModel),
    SetupPropertyName
)
.setupPropName('name', 'description');
```
Or ever better (you don't need the `Initialize` function):
```js
export default Model('Tree')
  .init(initializeTreeModel)
  .compose(SetupPropertyName).setupPropName('name', 'description');
```

**Comment by koresar** [comment]
Btw, this is a bug!
> I tried this, but initializer is never invoked.

Thanks for finding it 👍

**Comment by koresar** [comment]
stampit v3 rc1 just got published. The bug got fixed. New test added.

cheers :)

**Comment by FredyC** [comment]
I tried this in RC1 and still not working, the `build` method is not available.

```
const NodeModel = Model('Node').compose(
	Getter('name'),
	Getter('description'),
	{ statics: { build }}
);
```
=========

> ```
> export default Model('Tree').compose(
>     Initialize(initializeTreeModel),
>     SetupPropertyName
> )
> .setupPropName('name', 'description');
> ```

Frankly this looks terrible :) I don't want to expose a way how to add more properties to the model from outside.

**Comment by koresar** [comment]
> I don't want to expose a way how to add more properties to the model from outside.

You shouldn't worry. All stamps are immutable. None will add properties to your model. :)
But only if you make the "setupPropName" to always return a new stamp instance. Like in the example [above](https://github.com/stampit-org/stampit/issues/207#issuecomment-220176871).

Please remember! All stamps are immutable.

**Comment by koresar** [comment]
> I tried this in RC1 and still not working, the build method is not available.

Oh, crap. That's another bug. Sorry.

**Comment by FredyC** [comment]
> You shouldn't worry. All stamps are immutable. None will add properties to your model. :)
> But only if you make the "setupPropName" to always return a new stamp instance. Like in the example above.
> 
> Please remember! All stamps are immutable.

Alright, I missed that part, that's very good indeed :)

**Comment by koresar** [comment]
Fixed and published as part of RC3. See [this unit test](https://github.com/stampit-org/stampit/blob/v3_0/test/compose.js#L158). If you have free cycles then feel free to check.

Also, new shortcut methods were added: conf, deepConf, deepStatics.

I'll close this issue in a day or so.

Thanks!
