### ISSUE TITLE
Proper build for various environments 

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stampit#208]
Regarding closed issue #189 we might give it another try. Call me masochist, but I kinda do enjoy fiddling with various build tools and stuff :)

I have run into this article recently: https://medium.com/@tarkus/how-to-build-and-publish-es6-modules-today-with-babel-and-rollup-4426d9c7ca71#.jj0esfcdm. 

I am going to implement this soon for another library I am publishing, so if it proves itself, I am willing to apply same thing for stampit, if you like it.

**Comment by koresar** [comment]
Sounds great!

@ericelliott you'd love this happened I believe. :)

/cc @boneskull

**Comment by ericelliott** [comment]
=)

**Comment by FredyC** [comment]
Ok so I have tested this for my library and truly works like a breeze. Normally I would use webpack, but that's uncessarily complex. Rollup seems indeed better choice for library packages, so I am going to give it a try for stampit.

First I am wondering. You have a `prepublish` script there which only runs some checks. Can I add build script there too? It's kinda safe option to make sure that you are publishing truly latest build. Or do you have a different workflow I am not aware off?

**Comment by koresar** [comment]
> Can I add build script there too?

Yes please! 👍

**Comment by ericelliott** [comment]
Build scripts are usually added via prepublish.

**Comment by koresar** [comment]
@FredyC btw, are you doing that in the v3_0 branch?

**Comment by FredyC** [comment]
Yes, of course I will do it there, most probably during weekend, I had to sort out some other stuff first.

**Comment by FredyC** [comment]
Sorry, I got bit sick over weekend, so I could do this. Anyway now looking more closely, would you mind actually to update babel to version 6?

**Comment by koresar** [comment]
@FredyC sure thing Dan. I was going to do it myself in few days. Thanks

**Comment by koresar** [comment]
The #209 merged. Closing this one. Great job @FredyC !
