### ISSUE TITLE
[v3] Cloning of functions within deepConfiguration

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stampit#217]
Something that got broken in RC4/5 with new merge used. I have a following code.
```js
const NodeMemory = Memory.withDefaults({
	openNodes: () => [],
})
const TreeMemory = Memory.withSubmemory('node', NodeMemory);
```

Both of these are essentially just wrappers for `deepConfiguration` (see below). Problem is with last line where I am passing whole Stamp function that I want to use for building submemories. Unfortunately this is only merged as for properties instead of a making reference to a whole function.
```js
function withSubmemory(name, submemory) {
	return this.deepConf({ submemories: { [name]: submemory }});
}
function withDefaults(defaults) {
	return this.deepConf({ defaults });
}
```

This is perhaps something that should be even solved on specification level as it doesn't mention details on **how** is deepConfiguration cloned.

**Comment by koresar** [comment]
This is rather a pain point of stamps currently.

We used to say "deep merge as in _.deepMerge", but lodash merging algorithm is somewhat bulky and doesn't concat arrays.

Another solution to the deep merging can be the user defined callback.
```js
const customMetadataMerger = compose({mergers: [function (dstDescriptor, srcDescriptor) {
  const {defaults} = srcDescriptor.deepConfiguration;
  if (defaults) {
    defaults.openNodes = []
      .concat(srcDescriptor.deepConfiguration.defaults.openNodes)
      .concat(defaults.openNodes);
  }
}]});
```
But that's a too deep debris, although a powerful feature.

**Comment by FredyC** [comment]
Well you misunderstood me here. One thing is concatenating array for sure, but also if you have just function as a value, it gets deeply cloned and you get this:

```js
  submemories:
   { tree:
      { refs: {},
        props: {},
        init: {},
        deepProps: {},
        statics: {},
        deepStatics: {},
        conf: {},
        deepConf: {},
        create: {},
        compose: [Object],
        methods: {},
        properties: {},
        initializers: {},
        deepProperties: {},
        staticProperties: {},
        staticDeepProperties: {},
        configuration: {},
        deepConfiguration: {},
        withSubmemory: {},
        withDefaults: {} } } }
```

**Comment by koresar** [comment]
I'm pretty sure I understood you correctly. It's just my thoughts are to broad, trying to catch every possible issue.

There is a problem with function referencing. Here:
```js
function F() {}
console.log(F); // [Function: F]
let Stamp = compose({deepProperties: { foo: F } }).compose({deepProperties: { foo: { bar: 42 } }});
console.log(F); //  [Function: F] foo: { bar: 42 } }
```
If we copy by reference then the `compose` merging algorithm can "damage" (add properties) to the referenced objects (in this case the function `F`).

Stamps are immutable. They should not change a third party state.

P.S. There are ways to clone functions in JS. (For example `F.bind()` creates the function copy).

**Comment by FredyC** [comment]
Ah I see, you are right, such side effect could be rather harmful. However using `bind` comes with problem of rebinding context of that function (unless lexical scope with fat arrow) which is also something unwanted. I am wondering how is lodash doing it actually...

**Comment by FredyC** [comment]
Ok I think that lodash way is kinda best way to solve this. It doesn't try to merge functions with another properties, it simply overrides whole function there ... see http://jsfiddle.net/ybem606s/2/

It's side effect free and consumer needs to decide if that property should have function or something else. I am more than fine with such solution.

**Comment by koresar** [comment]
> However using bind comes with problem of rebinding context of that function

Nope.
```
> function F() { console.log(this); }
> var f = F.bind({a:1})
> f()
{ a: 1 }
> f.bind()()
{ a: 1 }
```

**Comment by koresar** [comment]
If you want to preserve functions in the "deepConfiguration" I'd recommend storing it in an array. As it is declared in the spec that we concat arrays.

**Comment by FredyC** [comment]
Ah I see, so you can even omit to specify context in `bind` call, did not know about that, cool :) Hope it works in all engines like that.

> If you want to preserve functions in the "deepConfiguration" I'd recommend storing it in an array. As it is declared in the spec that we concat arrays.

Uhh, that sounds totally silly, I surely don't want to allow multiple stamps for a single submemory.

**Comment by koresar** [comment]
Implemented. Released as stampit v3 RC9.
