### ISSUE TITLE
statics this

### ISSUE THREAD

**Issue by pdavidow** [stampit-org/stampit#220]
````
// 'this' is undefined for statics

import stampit from 'stampit';
import test from 'tape';

const Q = stampit({
    staticProperties: {
        myName: () => this.myId, // TypeError: Cannot read property 'myId' of undefined
        myId: 'Q'
    }
});

test('staticProperties', (assert) => {
    let actual = Q.myName();
    let expected = 'Q';
    assert.equal(actual, expected);

    assert.end();
});
````

**Comment by ericelliott** [comment]
Did you intentionally use an arrow function in that example?

**Comment by koresar** [comment]
Oh! The fat arrow. :) I didn't notice.
Hey @pdavidow 
Change the line to be
```
        myName() { return this.myId },
```
and it will just work. :)

**Comment by FredyC** [comment]
Fat arrows seem like ugly monsters for stamps unless used inside another functions.

**Comment by JosephClay** [comment]
@FredyC I've done the same. Powerful features are easy to abuse.

**Comment by pdavidow** [comment]
This should be documented.

**Comment by JosephClay** [comment]
@pdavidow  It is documented:
> An arrow function expression has a shorter syntax compared to function expressions and lexically binds the this value

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)

Scoping of `this` is a feature of the language.
