### ISSUE TITLE
object this bind

### ISSUE THREAD

**Issue by rickmed** [stampit-org/stampit#222]
Is there a way to bind this to the target object?
Considering the bar code example at the end of the main page. If I do something like this:

```javascript
const toPassItSomewhere = myBar.getMember
toPassItSomewhere('Homer')
```

it errs because this dynamically changed to the context.
Isn't preferable to fix this to the instance?
Apologies in advance if this issue makes no sense...

**Comment by koresar** [comment]
It makes total sense mate. :)

Imagine if it was a class:
```js
class MyBar {
  getMember() { return this.members[name]; }
}
```
The context won't be bound too:
```js
const myBar = new MyBar();

const toPassItSomewhere = myBar.getMember;
toPassItSomewhere('Homer');
```

You can do regular binding though:
```js
const toPassItSomewhere = myBar.getMember.bind(myBar);
toPassItSomewhere('Homer');
```

**Comment by rickmed** [comment]
@koresar thanks for the quick response!

Shouldn't stamp it make this behavior by default? binding all methods to the instance (I don't think there are any cases in which you would want to this refers to something else other than the instance, right?)

**Comment by koresar** [comment]
Well, you can easily create one more stamp, call it "BindAllMethods" and merge it with any of your existing stamps. Look:
```js
const BindAllMethods = stampit().init(function () {
  Object.keys(Object.getPtototypeOf(this))
  .filter(key => typeof this[key] === 'function')
  .forEach(key => {
    this[key] = this[key].bind(this);
  });
});
```
And you're done!
WARNING. The code above is not tested. I have just typed it. :)
