### ISSUE TITLE
Drop support for node.js 0.x and IE11

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#224]
How about dropping support for these two outdated platforms? :) Basically, because I don't want to introduce any new package dependencies to `stampit`.

node v0.x and IE11 do not have `Object.assign` implemented.

Many tools and modules already dropped support for node 0.x. We won't be the first.

For IE11 compatibility we would need to announce that [a polyfil](https://github.com/sindresorhus/object-assign) is required. But that's basically it.

Thoughts?

**Comment by FredyC** [comment]
Well IE11 is still sort of used as not many user has migrated to Windows 10 yet, but I don't have any actual stats of how many users actually use it on Win7.

I do like more this polyfill: https://cdn.polyfill.io/v2/docs/features/ as it provides automatic detection of missing features and serves only those, but obviously it cannot be used in NodeJS environment so your recomendation is fine as well.

**Comment by koresar** [comment]
If no other objections arise in couple of days we would go this direction.

**Comment by koresar** [comment]
Ok. 3 days. No objections.
It's decided!
Stampit v3 is dropping support for environments which do not have `Object.assign` function or polyfil.
