### ISSUE TITLE
Can't override normal function with generator function with `methods`

### ISSUE THREAD

**Issue by hoschi** [stampit-org/stampit#225]
I changed the hook definition from #223 and implemented is a noop function:
```
let DefaultHooks = stampit().methods({
  preHook:() => {}
});
```

so I can override it with an implementation if needed in other stamps like:
```
let LoggerHooks = stampit().compose(DefaultHooks).methods({
  preHook:function *() {
    yield console.log(arg);
  }
});
```

This works only for normal functions and not for generator functions. My current workarround is
```
let LoggerHooks = stampit().compose(DefaultHooks).init(function ({instance}) {
  instance.preHook = function *() {
    yield console.log(arg);
  };
});
```

@koresar I took a short try with current v3rc but it breaks my code base too hard. Perhaps this is already fixed in v3?

**Comment by koresar** [comment]
Great workaround!

Could you please elaborate on this:
> This works only for normal functions and not for generator functions.

What does not work?

**Comment by koresar** [comment]
I know why it does not work. Because stampit v2 limits the `methods` to be only `typeof` function. Whereas stampit v3 allows anything in the `methods`, including generators.

Here is the problematic [LOC](https://github.com/stampit-org/stampit/blob/9f87657d4e55d0ea86391aa8ee5d314e7ce377db/src/stampit.js#L47).

The proper workaround in stampit would be:
1) Leave the `DefaultHooks` as is.
2) Replace `methods` with `refs` in `LoggerHooks` like so:
```js
let LoggerHooks = DefaultHooks.refs({
  preHook: function *() {
    yield console.log(arg);
  }
});
```

And done!

**Comment by hoschi** [comment]
> I know why it does not work. Because stampit v2 limits the methods to be only typeof function.
I thought about something like that ;)

> Whereas stampit v3 allows anything in the methods, including generators.
Great! I make a local ticket for me to upgrade to v3 when it is released.

Thanks for your workaround, this is makes composition easier, I use that one till v3 is released and stable.

**Comment by koresar** [comment]
v3 is stable. Not released though. :) Working on it as we speak.

**Comment by ericelliott** [comment]
> Because stampit v2 limits the methods to be only typeof function. Whereas stampit v3 allows anything in the methods, including generators.

Generators are not `typeof function`?

That's news to me:

```js
function* foo () {}
typeof foo // 'function'
```

That's native code running in Node 6+.

**Comment by hoschi** [comment]
I use Babel, perhaps it transpiles it to something which has type object.

Eric Elliott <notifications@github.com> schrieb am Mi., 27. Juli 2016 21:49:

**Comment by FredyC** [comment]
> I use Babel, perhaps it transpiles it to something which has type object.

That doesn't sound right because generator is essentially just a function, but returning iterator. With Babel that function just has this in a body `return _regenerator2.default.wrap(function...` which handles magic of "pausing" the function.

More likely it's some other issue or you may have missed something perhaps?

**Comment by koresar** [comment]
@FredyC you are correct!
```
┌vasyl@192-168-1-11 ~/c/stampit (v3_0 *$)                                           
└> nvm use 6
Now using node v6.3.0 (npm v3.10.3)
┌vasyl@192-168-1-11 ~/c/stampit (v3_0 *$)                                           
└> babel-node --presets es2015
> const g = function* (){}
'use strict'
> typeof g
'function'
> g()
GeneratorFunctionPrototype { _invoke: [Function: invoke] }
```

@hoschi you might want to double check your code.

**Comment by hoschi** [comment]
```
test.only('stampit generators - fails', t => {
    let b = function* () {
            return 'bar'
        }
    let s = stampit.methods({
        a:() => 'foo',
        b
    }).create();

    t.truthy(typeof s.a === 'function')
    t.truthy(typeof b === 'function')
    t.truthy(typeof s.b === 'function')

    t.truthy(s.a() === 'foo');
    t.truthy(s.b().next().value === 'bar');
})
```

`b` is a 'function', but `s.b` is not defined.

With ref it works:
```
test('stampit generators - works', t => {
    let s = stampit.refs({
        a:() => 'foo',
        b:function* () {
            return 'bar'
        }
    }).create();

    t.truthy(typeof s.a === 'function')
    t.truthy(typeof s.b === 'function')

    t.truthy(s.a() === 'foo');
    t.truthy(s.b().next().value === 'bar');
})
```

I noticed that all code work with node 5.4.1 but not with node 6.2.1

**Comment by hoschi** [comment]
In Chrome it never works with `methods`.

**Comment by koresar** [comment]
Okay, so stampit is using `lodash/isFunction` to check values.
Lodash is not using `typeof value === 'function'`. Instead, it is using `value.toString() === '[object Function]'`.
```js
> var g = function* (){};
> Object.prototype.toString.call(g);
'[object GeneratorFunction]'

> var f = function (){};
> Object.prototype.toString.call(f);
'[object Function]'
```
I believe stampit v2 need a fix to allow generators, as well as stampit v3.
Right?

To fix stampit v2 we need to patch the `supermixer` module. Any volunteers?

I'll fix stampit v3.

**Comment by ericelliott** [comment]
Good detective work. =)

**Comment by koresar** [comment]
Review needed: https://github.com/stampit-org/supermixer/pull/7

**Comment by hoschi** [comment]
Great you found it! I wait for v3.

Vasyl Boroviak <notifications@github.com> schrieb am Fr., 29. Juli 2016,
05:26:

**Comment by FredyC** [comment]
Lodash v4 does consider generators as functions, so it's merely problem of v3, so it's not necessary to report that.

I've merged pull request, lodash does too sofisticated checks for our needs.

**Comment by koresar** [comment]
Oh, wait. I was wrong. Stampit v3 does not need a fix because it does no checks at all. :) One can put anything as "methods".

**Comment by FredyC** [comment]
Yea I was bit confused what do you want to check there. We even dropped lodash there some time ago :)

**Comment by koresar** [comment]
@hoschi thanks for reporting the bug. stampit v2.1.2 was just published.
