### ISSUE TITLE
FlowType  declarations

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#227]
@jmancine [asked](https://gitter.im/stampit-org/stampit?at=57a157260bd017c16e36ff1e) for a feature - FlowType declarations. Related FlowType docs are [here](https://flowtype.org/docs/declarations.html#_).

**Comment by FredyC** [comment]
Well I am not really sure what is currently better way of static type checking. I haven't get into any of those yet. From what I remember, when I tried flow last time, it wasn't working on Windows. I am not sure if that's still a true.

Lately I am hearing more and more about Typescript as a more robust solution. From what I found out, there is also ability to keep types in separate file. There is also the [typings](https://github.com/typings/typings) tool that can manage these files.

I am not sure if we should combine both of these mechanics really, might add uncessary complexity in maintenance.

**Comment by koresar** [comment]
They fixed flow type for Windows just yesterday AFAIK.

The `/* flow */` comment is not necessary for FlowType declarations. Just like our [TypeScript declarations](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/stampit).

We can support both declarations if anyone is willing to contribute.

PS: thanks for `typings` link!
