### ISSUE TITLE
Help with private data and methods

### ISSUE THREAD

**Issue by JVMartin** [stampit-org/stampit#229]
Hey guys, I'm hoping you can help me out here.  Let's say I have a `User` stamp that looks like this:
```javascript
// User.js

let numUsers = 0;

export default stampit().init(function() {
	var userID = ++numUsers;

	this.getUserID = function() {
		return userID;
	};

	this.getUserInfo = function() {
		return {
			userID: userID,
			complicated: complicated()
		};
	};

	function complicated() { // Private method
		// Do lots of complicated stuff
		return result;
	}
});
```
If I understand correctly, this is no good because if I create a million instances of it, each one of those objects has its own copy of all of those functions totally unnecessarily, resulting in a *huge* waste of memory - I don't need a million copies of those functions floating around in memory, just one of each would be fine.

However, if I try to fix that by doing something like this:
```javascript
// User.js

let numUsers = 0;

export default stampit().init(function() {
	var userID = ++numUsers;
}).methods({
	getUserID() {
		// Ugh, no way to access userID from here!
	},
	complicated() {
		// Ugh, this should not be a public method!
	}
});
```
Well, now all of the methods that I wanted to be private/privileged are public, and furthermore... there's no way to access the private data from them!

I'm hoping there is a stampit way to achieve private data without being so wasteful with memory.  Thanks so much in advance for any guidance.

**Comment by koresar** [comment]
There are various ways you can do that in JS.

1) Use `WeakMap` 
```js
const myWeakMap = new WeakMap();

export default stampit().methods({
  accessingPrivateData() {
    const privateData = myWeakMap.get(this); // getting the private data
  }
});
```

2) Another approach (for JS environments without WeakMap):
```js
let numUsers = 0;

export default stampit().init(() => { 
  const userID = ++numUsers;

  const myProto = Object.getPrototypeOf(this);
  if (!myProto.accessingPrivateData) { // key line
    this.accessingPrivateData = () => {
      return userID;
    }
  }
});
```

A side note on that "userID". It's generally recommended to avoid numeric IDs for anything. UUIDs are much better in many ways.

**Comment by koresar** [comment]
3) ES6 Symbols. :)

**Comment by JVMartin** [comment]
Thank you - those are both very innovative, @koresar!  :+1:

A couple of questions for you:
1. Did you mean to put `myProto.accessingPrivateData = () => {` on approach #2?  This approach is tripping me out... so the fist time I create an instance, it will add that method to its prototype... won't then all future objects be referring to the first object's userID (and all return 1)?  I'm going to try this and report back.
2. Will WeakMap return the same value for a given object even after you change that object's properties?  I would guess it just uses the reference/pointer and not the value of the object... (I suppose I can do a quick test to find out!)
3.  Could I perhaps coerce you into giving an example with ES6 Symbols?  :)

**Comment by JVMartin** [comment]
I'm afraid solution 1 doesn't work because when the garbage collector collects an object, it will leave all of its private data behind...

**Comment by koresar** [comment]
* Sorry, I surely meant `myProto`. Corrected.

I'm using the approach myself. It worked last time. :)
Basically, the JS engine creates new **closure**, but does not create a new copy of the function.

* Yes, the [WeakMap](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) uses references.

* Here is my favourite introduction to Symbols - http://www.2ality.com/2014/12/es6-symbols.html
Although, I must mention that this is a semi-private approach. Symbols of an can be iterated through.

**Comment by JVMartin** [comment]
And sure enough, with approach 2:
```javascript
import User from './User';

const user_a = User();
const user_b = User();


console.log(user_a.getUserID()); // 1
console.log(user_b.getUserID()); // 1
```

**Comment by koresar** [comment]
Number 1: 
Not sure what you mean.

Number 2:
I would need to double check my code then. :\

**Comment by koresar** [comment]
Feel free to have more real time chat here: https://gitter.im/stampit-org/stampit

**Comment by JVMartin** [comment]
If anyone else stumbles across this issue:

@koresar pointed out in chat that WeakMap actually doesn't cause any memory leaking because it will let go of the private data when there are no other references to the given object.  I'm going to go with that approach for now!

**Comment by koresar** [comment]
A new stamp was developed - https://www.npmjs.com/package/@stamp/privatize
This is how it works:
```js
import Privatize from '@stamp/privatize';

let accessPassword, accessSetPassword;
const Original = compose({
  properties: {password: '123'},
  methods: {
    setPassword(value) { this.password = value; },
    checkAccess() {
      accessPassword = this.password;
      accessSetPassword = this.setPassword;
    }
  }
});
 
// Add Privatize behavior, additionally protect the 'setPassword' method  
const Stamp = Original.compose(Privatize).privatizeMethods('setPassword');
 
// All properties and the method 'setPassword' are undefined 
const instance = Stamp();
expect(instance.password).toBeUndefined();
expect(instance.setPassword).toBeUndefined();
 
// But the 'checkAccess' method have access to the properties and 'setPassword' 
instance.checkAccess();
expect(accessPassword).toBe('123');
expect(accessSetPassword).toBe(Original.compose.methods.setPassword);
```
