### ISSUE TITLE
UMD build in browser environment doesn't work actually

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stampit#259]
We have never tested that apparently. The problem is, that `window.stampit` gets assigned the `exports` object instead of actual stampit function. Then anyone actually trying to use `stampit()` won't succeed.

Obviously it's a rollup thing, but kinda understandable. I've created [the issue](https://github.com/rollup/rollup/issues/1044) there with possible solution, so we will see what happens.

In case they would be against it, we should add warning to the README that `stampit.default` needs to be used. I assume that not many people actually uses libraries directly like this anymore, so I it's not a big problem I would say.

**Comment by koresar** [comment]
Took a read. Thought a lot.

Why stampit need ES6 exports?
The only useful feature I see is the tree-shaking. However, it's not beneficial for a small module like stampit to provide tree-shaking. There is no gain.

My proposal: Ditch the ES6 `exports` syntax. And simply `module.exports = stampit`. As the result:
* CJS (node.js) will work
* UMD will work
* ES `import` statement will work
* No PITA for us

But! We would need to revive ES6 `exports` in the future `@stamp/stamp` project.

What do you think?

**Comment by FredyC** [comment]
Well I am using named exports in my project, it just feels better if I can write directly `init(...)` instead of `stampit.init(...)` :) It's also breaking change, so I wouldn't really go that way anytime soon. Extra entry point is lesser evil.

**Comment by koresar** [comment]
Oh. You mean `import init from 'stampit'` won't work any more if we leave this line only?
`module.exports = assign(stampit, allUtilities);`

**Comment by FredyC** [comment]
`import init from 'stampit' is same as `import stampit from 'stampit', just different name for a default export. You will always get stampit function so I would need to do `init.init()` :D

You cannot really use import to retrieve only one property of default export, that's not how it works because ESM are completely lexical, they cannot statically analyze what you are exporting.

**Comment by koresar** [comment]
Surely I meant `{init}` :)

**Comment by FredyC** [comment]
Yea, that wont work either obviously :) You can [check it out here](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwdGVzdCUyMCU3RCUyMGZyb20lMjAnLiUyRm1vZHVsZS5qcyclM0IlNUNuJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtb2R1bGUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwRGVmYXVsdCUyMGV4cG9ydHMlMjBmcm9tJTIwdGhlJTIwJ2VudHJ5JTIwbW9kdWxlJyUyMGFyZSU1Q24lMkYlMkYlMjBleHBvcnRlZCUyMGZyb20lMjB0aGUlMjBidW5kbGUlNUNuZnVuY3Rpb24lMjBtYWluKCklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdtYWluJyklM0IlNUNuJTdEJTVDbiU1Q25tYWluLnRlc3QlMjAlM0QlMjBmdW5jdGlvbigpJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKCd0ZXN0JyklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwbWFpbiUzQiUyMiU3RCU1RCU3RA==)

**Comment by anhuiliujun** [comment]
So, if i am not using any bundle system, how should i use stampit now?

**Comment by koresar** [comment]
In the README.md we say about unpkg.com a
https://unpkg.com/stampit@latest/dist/stampit.umd.min.js
and cndjs.com
https://cdnjs.com/libraries/stampit

Did those UMD bundles worked for you?

**Comment by anhuiliujun** [comment]
Thank you very much, and sorry for the noise, I forgot the object.assign polyfill.

**Comment by koresar** [comment]
No worries.

**Comment by koresar** [comment]
I tested. UMD work now. Here is the installation instructions: https://github.com/stampit-org/stampit#install

I'm closing this issue. It looks done long ago :)
