### ISSUE TITLE
"composers" experiments implementation

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#276]
- [x] Discuss in this issue which API should the composer function have
- [x] Implement the [composers proposal](https://github.com/stampit-org/stamp-specification/issues/109) in a new PR.
- [x] The PR should change the API doc:
 - [ ]  The docs should show some examples of how you can alter stamps if you want to using higher order functions instead of using composers. At least that way people won't think that's the only way to do things.
 - [x] The docs should mention that the feature is experimental.

**Comment by koresar** [comment]
After trying it out I found that the simplest and the most universal API would be this:
```js
const HaveComposer = stampit.composers(function ({stamp, composables}) {
  console.log('Resulting stamp:', stamp);
  console.log('Was made of composables:', composables);
});
```

The implementation will still be specification compatible. The "composers" will be attached to the `deepConfiguration` as the `.composers` array. It will be deduped just like initializers array is.

The provided composers will be invoked immediately after being passed to the `compose()`:
```js
stampit.compose(AnyStamp, {composers({stamp, composables}) {
  assert(composables[0] === AnyStamp);
  assert(typeof composables[1] === 'object');
}});
```

**Comment by FredyC** [comment]
Can you perhaps provide some real use case scenario? I still have a hard time to realize what this is good for actually. Even after rereading proposal couple times :) Consider me as the outside user on this and if there will be big barrier to understand this, not many people is actually going to use it.

**Comment by koresar** [comment]
Providing the use case scenarios as a Fun with Stamps. Episode 11. Interfering composition
https://medium.com/@koresar/fun-with-stamps-episode-11-interfering-composition-7abc44ac1f99
/cc @FredyC @amelon

**Comment by koresar** [comment]
Done
