### ISSUE TITLE
Default values for properties vs repeated composition

### ISSUE THREAD

**Issue by FredyC** [stampit-org/stampit#278]
Well I just encountered rather peculiar problem. Simplified code looks like this.

> Action.js

```js
const Action = stampit.statics({
	actionName: null,
	define(name) {
		return this.statics({ actionName: name })
	}
})

export default Action
```

> EngineAction.js

```js
import Action from './Action'

const EngineAction = Action.statics({
	trigger: ...
})
```

In some other point a do have just `Action` stamp and conditionally I am composing it with `EngineAction`, eg. `MyAction.compose(EngineAction)`. What was a surprise to find out that `ResultAction.actionName` is actually `null`.

After some debugging I've realized that culprit is obviously that in `EngineAction.js` I already use `Action` as a base stamp. In a process of merging it then overrides again the `actionName`.

Does it classify as a bug? It certainly prevents me to do one of these which would be normally expected to work properly in my opinion.

* Set default values for my properties ... makes it less confusing to see everything in one place
* Compose same stamp multiple times ... allows not to make any assumptions about used stamps

**Comment by koresar** [comment]
> Does it classify as a bug?

Nope.

There are few ways to solve that.
1) The default `actionName` should be `undefined` instead of `null`. Then it will work as expected.
2) I'd have `HaveTrigger` stamp instead of the `EngineAction`. Because `EngineAction` just too bulky and duplicates `Action`.
3) ...

I see `statics` abuse in your code. Have you considered `configuration`/`properties` instead?

**Comment by FredyC** [comment]
> 1) The default actionName should be undefined instead of null. Then it will work as expected.

This kinda sounds like a bug or at least it's not documented? Since it's `undefined` by default I rather use `null` so I can easily distinguish if it was set or not at all.

Reason why I am composing `Action` into `EngineAction` is because I am calling static method of it. 

```js
const Action = stampit.statics({
	setupAction(app) {
		const { setupListeners } = this.compose.deepConfiguration
		// here I am composing stamp from results of all listeners
		return setupListeners.reduce((stamp, listener) => listener.call(stamp, app), this)
	},
	addSetupListener(listener) {
		return this.deepConf({ setupListeners: [listener] })
	}
})

const EngineAction = Action..addSetupListener((app) => {
	const engine = app.engine
	return this.methods({
		trigger() {
			this.log('triggering')
			engine.triggerAction(this.name, this.payload)
		},
	}).statics({ engine })
})
```

Declaring actions happens way before the `app` is available. I am aware it's not pretty, but if you have an idea for better solution...

**Comment by koresar** [comment]
Anything to discuss here? Can you consider closings this one @fredyc?

**Comment by FredyC** [comment]
Yea, I don't really remember how I actually solved it and it's kinda abandoned thing in general so I am closing it.
