### ISSUE TITLE
PJA Book concatenative inheritance example

### ISSUE THREAD

**Issue by Ephs05msm** [stampit-org/stampit#301]
Hi,

I'm having a bit of trouble producing the expected result for this example.  With node.js, tape, tap-spec, and stampit, I've written the following:

```
const test = require('tape'), tapSpec = require('tap-spec'),
  stampit = require('stampit');

var person = stampit().props({name: ''}),
  jimi = person({name: 'Jimi Hendrix'});

test.createStream().
  pipe(tapSpec()).
  pipe(process.stdout);

test('Initialization', (t) => {
  t.equal(jimi.name, 'Jimi Hendrix',
    'Object should be initialized.');

  t.end();
});
```

...adjusting for the most recent version of stampit.  The test fails:

```
Object should be initialized.
    --------------------------------
      operator: equal
      expected: 'Jimi Hendrix'
      actual:   ''
```

Please let me know where I've gone wrong.  Thanks in advance.

**Comment by koresar** [comment]
There were few breaking changes in the recent stampit v3
https://github.com/stampit-org/stampit/releases/tag/v3.0.0
Please check if any of those relate to your code. 
Otherwise, I can investigate. 

Waiting for your investigation. 
Cheers

**Comment by koresar** [comment]
I found the bug. Here is the breaking change described on this page: https://github.com/stampit-org/stampit/releases/tag/v3.0.0

-----

- The factory first argument properties are no longer automatically assigned to the instance.

Stampit v2:

``` js
const Stamp = stampit({ init({instance, stamp, args}) {
  console.log(this); // {foo: "bar"}
}});
Stamp({foo: 'bar'});
```

Stampit v3:

``` js
const Stamp = stampit({init(arg, {instance, stamp, args}) {
  console.log(this); // {}
}});
Stamp({foo: 'bar'});
```

A workaround can be implemented as a separate behavior (stamp).

``` js
const AssignFirstArgument = stampit({ init(opts) {
  Object.assign(this, opts);
}});
Stamp = AssignFirstArgument.compose(Stamp);
Stamp({foo: 'bar'}); // {foo: "bar"}
```

**Comment by Ephs05msm** [comment]
Thanks so much for the help (and the quick reply).  I'll review and revise on my end, and will spend more time with the change log going forward.

**Comment by koresar** [comment]
I'd recommend sticking with stampit v2. `npm install stampit@2` instead of the latest.
Cheers
