### ISSUE TITLE
Examples from readme

### ISSUE THREAD

**Issue by Mika83AC** [stampit-org/stampit#304]
Hello everyone,

sorry, but am I just blind/an idiot/dumb or aren't the examples found in the readme working?

I installed stampit via bower via "bower install stampit" an have the following code:

```
<script src="bower_components\stampit\stampit.js"></script>
<script>
// Some privileged methods with some private data.
const Availability = stampit().init(function() {
  var isOpen = false; // private
  ....
```

When executing this in Chrome, it says:
Uncaught TypeError: stampit is not a function at stampit.html:5

But when typing "stampit" into Chrome Dev Tools console, it shows me that stampit is available with all it's methods (compose, composers, conf ...).

So what the hell is wrong?

Thx in advance!
Regards,
Michael

**Comment by koresar** [comment]
Thank you for reporting.

It requires some investigation. Are you in the position to help?

**Comment by FredyC** [comment]
@Mika83AC  Where do you have these script tags? Both in head? In case you include both at the same spot, chances are that your "app code" is executed before stampit script is loaded and parsed. You can investigate that in Network tab of developer tools.

The safest path is load external scripts in head tag and your logic at the end of body.

**Comment by Mika83AC** [comment]
@koresar  Hm... I think I'm not in a position to help as I'm a JS and StampIt newbie ... :( Really have no idea what might be wrong.

@FredyC Even this is not working for me. Here is my example done as I understood your advice:

```
<!doctype html>
	<head>
		<meta charset="utf-8">
		
		<script src="bower_components\stampit\stampit.js"></script>
	</head>
	<body>
		Test
	</body>
	<script>
	// Some privileged methods with some private data.
	const Availability = stampit().init(function() {
	  var isOpen = false; // private

	  this.open = function open() {
		isOpen = true;
		return this;
	  };
	  this.close = function close() {
		isOpen = false;
		return this;
	  };
	  this.isOpen = function isOpenMethod() {
		return isOpen;
	  }
	});

	// Here's a stamp with public methods, and some state:
	const Membership = stampit({
	  methods: {
		add(member) {
		  this.members[member.name] = member;
		  return this;
		},
		getMember(name) {
		  return this.members[name];
		}
	  },
	  properties: {
		members: {}
	  }
	});

	// Let's set some defaults:
	const Defaults = stampit({
	  init({name, specials}) {
		this.name = name || this.name;
		this.specials = specials || this.specials;
	  },
	  properties: {
		name: 'The Saloon',
		specials: 'Whisky, Gin, Tequila'
	  }
	});

	// Classical inheritance has nothing on this.
	// No parent/child coupling. No deep inheritance hierarchies.
	// Just good, clean code reusability.
	const Bar = stampit(Defaults, Availability, Membership);

	// Create an object instance
	const myBar = Bar({name: 'Moe\'s'});

	// Silly, but proves that everything is as it should be.
	myBar.add({name: 'Homer'}).open().getMember('Homer');
	</script>

</html>
```

Still the error "Uncaught TypeError: stampit is not a function at index.html:12".

**Comment by FredyC** [comment]
@Mika83AC Where did you actually get that stampit script? Is it freshly installed from bower or did made a copy from somewhere? Can you please try this live URL instead ? https://npmcdn.com/stampit@3.1.3/dist/stampit.umd.min.js

**Comment by Mika83AC** [comment]
@FredyC I freshly installed it via bower as described in the readme: "bower install stampit".  This morning (before posting here) I performed a "bower update" to be sure to be on the latest version.

Using the CDN link you posted results in the same error. I've put my "example" on my server so you can have a direct look at it: [http://divelop.de/stampit/](url)

As I'm using the latest Chrome, I don't think it can/will be a browser compatibility issue.

**Comment by FredyC** [comment]
I see, there seems to be some issue unrelated to your code indeed. Quick workaround is simply to call `stampit.init` instead of `stampit().init`

@koresar Once again there is exported object with `default` instead of a function being exported. I though we solved this before, not sure if you were doing some changes there.

**Comment by koresar** [comment]
Fixed with stampit v4.
