### ISSUE TITLE
compiled releases?

### ISSUE THREAD

**Issue by Brian151** [stampit-org/stampit#314]
Would it be possible to include releases that actually have the 'compiled' js files?

This looks like it could be a useful library, but I can't really use it because quite frankly, I have no desire, nor a good reason to involve myself with the nightmare that is npm/nodejs. I don't use it, in fact, I go out of my way not to. Generally not a problem, aside from when I find libraries that just HAVE to have it for some reason...

Beside the nodejs annoyances, releases really should have the finished product, anyways. At least far as I can tell, this is the purpose github intended for them.

**Comment by koresar** [comment]
Did any of this approaches worked for you?
https://github.com/stampit-org/stampit#install
Those are browser ready compiled released.

Tell me if it doesn't work or you need something else.

**Comment by Brian151** [comment]
IDK how i missed those...
You might want to make them a bit more noticeable since some people see console commands and quit reading...

however, i do get THIS problem, now
stampit()
TypeError: stampit is not a function [Learn More]
typeof stampit
"object"

i also did a toSource() , but other than confirm it's an object, nothing of note.

So, how am I supposed to create a new stamp, then? your documentation all says to call stampit()
do i just use stampit.<whatever>() , now?

another question, can i define the methods like 
{
methodName:function(){}
}
?

I'm certainly not willing to trust certain ES6+ syntax to be supported just enough to be safe to use everywhere, also... I might use either typescript or haxe, and i have to use not so exciting things as-is to do what I'm planning to do.

**Comment by koresar** [comment]
>You might want to make them a bit more noticeable

I'll be glad to accept your contribution! Feel free to submit a PR.

> TypeError: stampit is not a function [Learn More]

This is an unfortunate error of "too much compilation" so to say. There is an opened issue about that. Have no time to fix it properly. A quick workaround is to replace `stampit().bla` with `stampit.bla`.

To dive deeper into the stamps I'd recommend you this blog post series: https://medium.com/@koresar/fun-with-stamps-episode-1-stamp-basics-e0627d81efe0

Have I answered all your questions?

**Comment by Brian151** [comment]
All you need really to do is put "download compiled version" or something
Or note that Bower and whatever else aren't mandatory
I don't feel comfortable editing an MD file... I generally don't use them, thus never bothered to learn their syntax

Alright... As long as it still works

Neat!

Probably... we'll just see further down the road

**Comment by koresar** [comment]
Looks like you're new too this JavaScript world. I haven't seen people using the word "compiled" in the community in 4 years. People typically say "browser-ready" or "minified" or "transpiled".

I'm glad we could work out your questions.

👍

**Comment by Brian151** [comment]
kinda? i started a few years ago and was only writing things by hand. eventually was made aware that there are tools to build JavaScript from much nicer-looking code, Like the Haxe compiler and VS:Code. I still have quite mixed feelings about using it to build entire programs, though. I am aware it's not "true" compilation... lol. Definitely heard permutations of "trans" + "piled" , as well. Just don't use them because I rarely see any reason to.

There is one totally pointless one I forgot multiple times now...
what's the "umd" stand for in the filename?

and yes, thanks for the help.

**Comment by JosephClay** [comment]
UMD = [Universal Module Definition](https://github.com/umdjs/umd)

Used to expose code to different module systems

**Comment by Brian151** [comment]
Alright

Well, I'll let you know if I have any other problems/questions
Should be safe to close this now.

**Comment by koresar** [comment]
Thanks!
