### ISSUE TITLE
Reducing size even more

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#323]
Recently @ericelliott posted a truly great concern that we are bloating stampit: https://github.com/stampit-org/stampit/pull/320#issuecomment-325812185

I agree, we should save those bytes (lines of code). I would even add that we should simplify stampit infrastructure because it was overly complexified with ES6->ES5 compilation.

Current stampit UMD build size is `5.26 KB`. By removing fancy ES6 stuff (plus some optimization techniques) I managed to reduce the size down to `4.0 KB`.

To be precise: `5393` -> `4128` bytes. It is `1,265` bytes or 23.5% less.

Simultaneously, this will fix #317, which was reported three times IIRC. (TL;DR: our own examples do not work in browsers.)

Also, this will reduce `devDepencencies` a bit.

Pinging all people from the #320 discussion: @sethlivingston @FredyC @Mustack @jyboudreau @ericelliott 

Should I proceed and submit the PR?

**Comment by koresar** [comment]
New result: `3931` bytes.

stampit.umd.min.js: `5393` -> `3931` bytes. It is `1462` bytes or 27.1% less.

(Btw, GZIP: `1.84KB` -> `1.77KB`. Or `1906` -> `1790` bytes.)

[Changes](https://github.com/stampit-org/stampit/compare/master...simplifying-minifying).

**Comment by koresar** [comment]
So, I went crazy today.

New new result: `3206` bytes. The performance did not suffer, even increased!

stampit.umd.min.js: `5393` -> `3206` bytes. It is `2187` bytes or 40.6% less.
`5.26 KB -> `3.13 KB`

(Btw, GZIP: `1.84 KB` -> `1.55 KB`. Or `1906` -> `1591` bytes.)

[Code](https://github.com/stampit-org/stampit/compare/master...simplifying-minifying) become less readable though.

**Comment by koresar** [comment]
New new result: `2983` bytes. The performance is the same.

stampit.umd.min.js: `5393` -> `2983` bytes. It is `2410` bytes or 44.7% less.
`5.26 KB` -> `2.91 KB`

GZIP: `1.84 KB` -> `1.45 KB`. Or `1906` -> `1489` bytes.

**Comment by JosephClay** [comment]
Those are some impressive gains

**Comment by koresar** [comment]
This is what stampit is currently:

![image](https://user-images.githubusercontent.com/1622575/31322872-d8283fe4-acea-11e7-9d73-98235e7a3fbd.png)

**Comment by koresar** [comment]
Thinking of releasing stampit v4:
  * Support the upcoming stamp specification v1.5: https://github.com/stampit-org/stamp-specification/issues/118 (adds composers feature). It opens following:
  * Drop `stampit/isStamp`, `stampit/isComposable`, and `stampit/compose`. Ask users to use `@stamp/is/stamp`, `@stamp/is/composable`, and `@stamp/compose` instead. (Almost none is using these anyway.)
  * Copy the Preact's approach to file minifiaction and module development.
  * Add IE11 tests. Maybe not automated, but at least manual.

As the result `stampit` and `@stamp` modules will become fully compatible.

**Comment by koresar** [comment]
After size reduction the tests run fine in IE11:
![image](https://user-images.githubusercontent.com/1622575/31363592-12667246-adab-11e7-94a9-e0398f4220e0.png)

**Comment by koresar** [comment]
Using stamp-specification v1.5.
New new result: `2814` bytes. The performance is the same.

stampit.umd.min.js: `5393` -> `2814` bytes. It is `2579` bytes or 48% less.
`5.26 KB` -> `2.75 KB`

GZIP: `1.84 KB` -> `1.33 KB`. Or `1906` -> `1366` bytes.
