### ISSUE TITLE
Initializer bug or am i missing something ?

### ISSUE THREAD

**Issue by MarcLoupias** [stampit-org/stampit#324]
Hello,

i am playing with codes examples in the [Fun with Stamps medium.com articles series](https://medium.com/@koresar/fun-with-stamps-episode-1-stamp-basics-e0627d81efe0).

Just found something strange in the **Breaking down a stamp into pieces** from the first article code examples : 

```javascript
#!/usr/bin/env node
'use strict';

const {compose, init} = require('stampit');

const HasFoo = compose({
    properties: {
        foo: 'default foo!'
    }
});

const PrintFoo = compose({
    methods: {
        printFoo() {
            console.log(this.foo || 'There is no foo');
        }
    }
});

const InitFoo = init(function(foo) {
    console.log('init arg value is ', foo);
    if (foo) this.foo = foo;
});

const Foo = compose(HasFoo, PrintFoo, InitFoo);

const objNoArg = Foo();
console.log('objNoArg :', objNoArg); // objNoArg : { foo: {} }

const objArgNull = Foo(null);
console.log('objArgNull :', objArgNull); // objArgNull : { foo: 'default foo!' }
```

When the initializer receive no value at all, the stamp lib replace `undefined` by an empty literal object, so the `if` statement is `true` instead of `false`, and the default value is overwritten with the literal object.

I am using `stampit@3.2.1` and node `6.11.3`.

**Comment by koresar** [comment]
Oh, right. The article was written before this change: https://github.com/stampit-org/stamp-specification/issues/93
Thank you for finding it!

Basically, the first argument is considered an _options object_. Thus, should never be undefined. You can manually specify `null` which is an object `typeof null === 'object'`.

Let me fix the article.

**Comment by koresar** [comment]
The article should be fixed now.

Thank you for the great issue!

**Comment by MarcLoupias** [comment]
Oooookayyyyy ;)

It's crystal clear now.

It imply that factory function have to takes an object as param.

We cannot do that `const myInstance = FactoryFn(prop1, prop2, ...)`

We have to do that `const myInstance = FactoryFn({prop1: 'val1', prop2, ...})`

To be honest the rtype spec to describe stamps add a step in the library adoption. You want to learn stamp but you have to learn rtype + stamp. Javascript executable examples in addition to the rtype def in the stamp-specification repo would be valuable.

Thanks !
