### ISSUE TITLE
✨ Add .version to stampit object

### ISSUE THREAD

**Issue by dwiyatci** [stampit-org/stampit#332]
My story: I just got back again to my old project that uses stampit after leaving it for 3+ years. I was confused for quite some time because I forgot which stampit version I used (was it 2.x or was it 3.x?). The frontend libraries of this project weren't managed by bower/npm, so... 😅 

I guess it would be useful if version information could be added to the API like `angular.version`, `React.version`, `lodash.VERSION`, etc.?

**Comment by koresar** [comment]
Good idea! Would you PR that thing for the rest of us? 🥇

**Comment by koresar** [comment]
Btw, I can tell you which version you are using by looking at the code. Feel free to gist and paste the link here.

**Comment by dwiyatci** [comment]
I identified it already before I submitted this issue (it was 2.x 😁). Just want to make sure it won't happen again in the future. PR been created.

**Comment by koresar** [comment]
Done in #334
