### ISSUE TITLE
Link to API docs is broken in Readme?

### ISSUE THREAD

**Issue by lp-belliot** [stampit-org/stampit#335]
Can't get to the API docs on gitbook, getting a 404.

**Comment by koresar** [comment]
Freacking gitbook! :(
Sorry. Let me quick fix that.

**Comment by koresar** [comment]
Ok. It fixed itself. I did nothing.
https://stampit.js.org

Can you please test if it's available on your side?

**Comment by benjiboi214** [comment]
Fixed!
