### ISSUE TITLE
Compose using an instance?

### ISSUE THREAD

**Issue by astanciu** [stampit-org/stampit#336]
I can't figure out if this is possible and if so, how.

I'd like to be able to compose using an existing POJO or previous instance. ex:

```js
const obj = {name: 'something'}

const Thing = stampit.compose(obj, OtherStamp, etc..)
```

I saw there's a convert-class utility, why not a convert-object? or is there a simpler way to do this other than merging object myself?

**Comment by koresar** [comment]
Sure there is a way. Actually, **three** ways. :)

If your POJO props need to go the `__proto__` then: 
```js
const obj = {name: 'something'}
const Thing = stampit.methods(obj).compose(OtherStamp, etc..)
```

If they need to be regular properties (a-la mixin) then:
```js
const obj = {name: 'something'}
const Thing = stampit.props(obj).compose(OtherStamp, etc..)
```

If you want some control over assignment logic then:
```js
const obj = {name: 'something'}
const Thing = stampit.init(function () {
  this.name = obj.name;
}).compose(OtherStamp, etc..)
```
-----
A good idea would be extract that stamp to a separate variable, which would have a descriptive name. For example:
```js
const HaveNameSomething = stampit.props({name: 'something'})

const Thing = stampit(HaveNameSomething, OtherStamp, etc..)
```

-----
Here is a [5 min article](https://medium.com/@koresar/fun-with-stamps-episode-1-stamp-basics-e0627d81efe0) which can help you to get your head around the above code.

**Comment by astanciu** [comment]
Amazing, so simple.. thank you.

**Comment by astanciu** [comment]
Quick followup, if `obj` was instantiated from a Stamp, its methods are on __proto__, which means neither .props nor .methods will pick them up:

```js
const Bar = stampit.methods({
    bar() {
      console.log('bar');
    }
  });

  const obj = Bar();

  const a = stampit.props(obj)(); // a.bar() undefined
  const b = stampit.methods(obj)(); // b.bar() undefined
  const c = stampit.methods(obj.__proto__)(); // bcbar() exists
```
 
Is this recommended if you want to enhance an existing Instance:
`const d =  stampit.props(obj).methods(obj.__proto__).compose(Something)()`

**Comment by koresar** [comment]
We recommend developers to do whatever they want with they code!
Stampit do not have any formal rules you should follow.
So, yeah. Your code is absolutely valid and recommended. :)

Good job on reading the above mentioned article. 👍
