### ISSUE TITLE
when i return something in init(), and then i can not call all methods

### ISSUE THREAD

**Issue by lornally** [stampit-org/stampit#342]
i did not certain this is a bug. this is my test code:
```js
function teststampinit() {
  const mckpoint = stampit()
    .statics({
      keymap: {},
    })
    .init(({ lng, lat, info, ...p }) => {
      const t = {};
      t.p = p;
      t.lng = lng;
      return t;
    })
    .methods({
      info() {   //这个不能被调用. this is can not be call.
        return "ooo";
      },
    });

  const xxx = mckpoint();
  xxx.info(); //这里会提示info不是函数.
  //here will info: xxx.info is not a function
}
```

**Comment by koresar** [comment]
Thanks for the question!

Here is a quote from our [docs](https://stampit.js.org/api/initializers)

> If you return anything from an initializer then it becomes the object instance.

Feel free to ask any other questions. 👍 

Cheers

**Comment by lornally** [comment]
and then, how can i get a stamp when i return an object in init method.

**Comment by lornally** [comment]
describe what is  my target:  i want a new object that has two feature: 
1.  IT copy all property from another object, that object from json, so it is different every time.
2. It is a stamp, example a mckpoint.
and how can i get the target? thank you.

**Comment by koresar** [comment]
Hello @lornally 

Looks like you need to understand that basics of stamps. I'd highly recommend going through this little article: https://medium.com/@koresar/fun-with-stamps-episode-1-stamp-basics-e0627d81efe0

It's very easy to solve your problem. :)
Do not create new objects inside the `init`. Think of `init` as a class constructor. Use `this`.
```
    .init(({ lng, lat, info, ...p }) => {
      t.p = p;
      t.lng = lng;
    })
```

Does that answer?

**Comment by lornally** [comment]
actually, i write code like this:
```js
const mckpath = stampit()
  .init(function init({ start, end, list, ...p }) {
    this.start = mpoint(start);
    this.end = mpoint(end);
    this.train = train({ list });
  Object.keys(p).forEach(e => { //here i got all last property, but can we elegant more
      this[e] = p[e];
    });
  }) 
```
i use object.key got all property, but can we do it more elegant?

**Comment by lornally** [comment]
and i will read tho topic, thank you:)

**Comment by lornally** [comment]
and your code should use function not =>, because use 'this'

**Comment by koresar** [comment]
Thanks for the correction about `=>`. Indeed there should be `function`. Corrected now.

Instead of the `forEach` you should use `Object.assign(this, p);`

**Comment by lornally** [comment]
thank you very much, and can we do it  more elegant than object.assign?

**Comment by koresar** [comment]
Yep. Here is my favourite method
https://www.npmjs.com/package/@stamp/arg-over-prop

**Comment by lornally** [comment]
thank you, you are really nice:)  i will learn your suggest:)

**Comment by koresar** [comment]
Thank you for the kind words mate!
Feel free to contact any time. 

Cheers
