### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by basejump** [stampit-org/stampit#351]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/187726/83338621-60670080-a283-11ea-9e74-5ccbdd733370.png">

**Comment by koresar** [comment]
Thanks!
I've asked people behind the .js.org here: https://github.com/js-org/js.org/issues/4134

**Comment by koresar** [comment]
Aaand the amazing folks from js.org put it back up in no time!
Thanks again for reporting the problem @basejump

**Comment by basejump** [comment]
thank you, checking out site/docs now
