### ISSUE TITLE
using stampit with jsdoc

### ISSUE THREAD

**Issue by foxaal** [stampit-org/stampit#36]
This is an important issue, but I am new to all this -- please tell me if not the place to write this:  I cannot find a recommended way to use jsdoc to document the creation of a stampit factory in addition to the pieces that go into it, i.e., method, state, and enclose pieces.  I have had some success treating the factory as mixing in the three pieces like this:
/** 
* Use stampit to compose methods, state, and private data to create a factory object. 
* @mixes platonicMethods 
* @mixes platonicState 
* @mixes platonicPrivate
* @return {Object} platonicFactory()
*/
platonicFactoryCreator = function ( ) { ....}

/** 
 * Methods going into the factory.
 * @mixin
 */
platonicMethods = {
  /**
   * Generated function used to test masking of the interface function of the same name.
   * @lend platonicMethods
   * @return {String} "platonic1() WIP"
   */
  platonic1 : function ( ) {...} ,  BUT THIS SHOWS UP AS A STATIC FUNCTION in Jsdoc output. 

Is there a better or accepted way?

**Comment by backspaces** [comment]
Is there any reason not to just use Docco?  I find the jsdoc approach less useful than a simple description  of what the code is doing.

I guess it's important to distinguish between "dev" docs (how it all works) and "api" documentation (what the inputs and outputs are).  For teams, the dev docs are more important, for users, api.

For stampit, I'd prefer dev, thus docco.

**Comment by foxaal** [comment]
Took a look at Docco -- shows me how crappy some of the comments littering my code really are...  (I see underscore.js makes good use of it:  http://underscorejs.org/docs/underscore.html )  But I want more.  I am using stampit in a project, and the code seems so organized and easy to work with that so too should be its "self" documentation piece...maybe could be a namespace / refactoring tool as well...

**Comment by koresar** [comment]
This issue is rather old. I'll close it for now. Please, yield at me if you need this opened back.
