### ISSUE TITLE
New feature: Debug mode that warns in the console when stamp props collide.

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stampit#50]
We could diff the object after a stamp is applied and display all the changes in the console.

@koresar - any interest in this for 2.0?

**Comment by LegitTalon** [comment]
This seems like a useful feature. When reasoning about an application the developer can more easily keep track of unwanted side-effects. It might also be helpful to have an optional "strict" mode of sorts that **prevents** prop collision by throwing an error.

**Comment by ericelliott** [comment]
I'm not sure we want a strict mode, because it would prevent the very common **defaults and overrides pattern**.

**Comment by LegitTalon** [comment]
Could be a per stamp setting maybe to provide a sort of constant prop? I'm only conceptually speaking here, just thought it would be worth considering.

**Comment by koresar** [comment]
Firstly, I believe all the new features should be introduced after we finalize the 2.0 branch (merge existing PR's, implement #41).

The proposed feature looks useful, although a rare developer would need it. Instead of implementing every feature in the world we could leave extensibility points. For example the three new upcoming [functions](https://github.com/ericelliott/stampit/blob/mixInChain/stampit.js#L52) `addMethods`, `addState`, and `addEnclose` are the very good candidate to be the first point. See possible code sample:
```js
var oldAddState = stampit._addState;
stampit._addState = function (fixed, states) {
  console.log(_.difference(fixed.state, _.merge.apply(null, [].concat(states))));
  fixed.state = _.merge.apply(null, [fixed.state].concat(states));
};
```

I haven't thought about the extensibility of stampit much. There got to be better ways to do it.

**Comment by ericelliott** [comment]
I agree, RE: finalize the 2.0 branch.

I also agree about making Stampit extensible.

However, I also think that static analysis of stamps is essential to Stampit as a tool for building large applications, and a tool that could very easily tell you which stamps are likely to play nice with each other would be very useful, indeed. Integrating it into Stampit core so that you can easily interact with it in the console *as you're building the application* seems like a very valid use-case to me ...

And it would only take a few lines of code to do it.

**Comment by koresar** [comment]
Would you please provide a code sample on how you see the
> easily tell you which stamps are likely to play nice with each other 

?

**Comment by LegitTalon** [comment]
Rough prototype of how it might work

```javascript
function checkClashes(objOne, objTwo) {
  var props = Object.keys(objTwo)
  Object.keys(objOne).forEach(function(key) {
    if (props.indexOf(key) !== -1) {
       console.warn('Merge overrides props.')
    }
  })
}
```

Allows developer to keep track of overrides therefore identifying unwanted overrides.

**Comment by ericelliott** [comment]
Clearly we'll want to include more detail in the message (like the key in question). This could happen one time per stamp, after the stamp is applied.

**Comment by koresar** [comment]
What's `stamp is applied`?

**Comment by ericelliott** [comment]
@koresar Each iteration of [this loop](https://github.com/ericelliott/stampit/blob/master/stampit.js#L154).

**Comment by koresar** [comment]
So, coming back to this issue. It looks alike the #67 

Still, I need high level code samples (not the implementation details). How a stampit user would like to use this feature?

**Comment by ericelliott** [comment]
Close in favor of https://github.com/stampit-org/stampit/issues/67
