### ISSUE TITLE
Warn on stamp propTypes conflicts

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stampit#67]
For 2.x, it would be great to have a static `propTypes` property that does structural type checking compatible with [React's `propTypes`](https://facebook.github.io/react/docs/reusable-components.html#prop-validation).

If composed stamps contain conflicting property names, Stampit could optionally warn in a special debug build, or continue without warning in production.

Warnings would not be the only benefit of a `propTypes` static. It could also be used for static analysis to provide type hints for stamps, or even automatically test for stamp compatibility in graphical dataflow tools like [`NoFlo`](http://noflojs.org/).

See also: https://github.com/ericelliott/stampit/issues/64#issuecomment-104854946

**Comment by koresar** [comment]
The 2.0 Milestone should contain incompatible changes. This issue seems like can be implemented in a fully compatible way. I'll create 2.1 Milestone and assign the issue to it. I really want to release stampit 2.0 ASAP.

Removing this issue from 2.0 Milestone.

**Comment by koresar** [comment]
I can't understand how to implement that. @ericelliott can you show any code samples you have in mind?

I just don't want to code something we'll through away just because it's useless.

**Comment by ericelliott** [comment]
During compose, look at the `propTypes` of stamps being composed. If any `propTypes` conflict, warn.

**Comment by koresar** [comment]
Yes, Eric. I understand how to implement that. Can you scratch a high level code please? Like:
```js
stampit.setup({ debug: ({ stampA, stampB, propA, propB, key }) => console.log(key) });
stampA.compose(stampB);
```

I cannot understand which exact way people age going to use this feature.

**Comment by koresar** [comment]
There is no requirment on this feature request. It's been opened for 2 months. /cc @troutowicz 

Please, either provide code examples or I'm closing this tomorrow.

**Comment by ericelliott** [comment]
We haven't even got typesystem specs, yet.
