### ISSUE TITLE
Tests for old IE compatibility (SauceLab integration reincarnation)

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#68]
After we migrated tests to tape (see #63) we do not run them against IE8 on SauceLab. Should be returned somehow.

Discussion is welcome.

**Comment by ericelliott** [comment]
I'm OK with dropping IE8 support in version 2, but version 1 still needs it.

**Comment by koresar** [comment]
What about IE9?

**Comment by ericelliott** [comment]
We should keep supporting IE9 in v2. There are still lots of people running old versions of Windows that don't support > IE9, unfortunately. );

**Comment by koresar** [comment]
As long as IE 8, 9 and 10 are not supported anymore we should aim to test IE11, Chrome, Safary, and FF.

**Comment by FredyC** [comment]
I agree with @koresar. People running software that no longer has any support are just shooting themselves in the leg.

Btw, don't forget about the Edge. If you don't know about it, it's a Microsoft browser in Windows 10 with much faster release cycles. They are are almost done implementing whole ES2015 in it, even modules.

**Comment by ericelliott** [comment]
Yep. IMO, our new targets should be IE11+ and all evergreens.

**Comment by koresar** [comment]
#326 contains significant simplification of stampit module code. Thus, I was able to make unit tests runnable in browsers.
No automatic tests though.

**Comment by koresar** [comment]
Implemented browser tests in v4. Manual tested in IE11. All good.

If someone would like to integrate stampit with SauceLab or similar - a PR is welcome.
