### ISSUE TITLE
Extract mixer.js to a separate npm module

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#69]
I already did it. :)
See https://www.npmjs.com/package/supermixer

It lacks few more tests, but should be ready for stampit.

Any objections, suggestions?

**Comment by ericelliott** [comment]
:+1:

**Comment by ericelliott** [comment]
Are we done with this? Please close the issue if it's done. =)

**Comment by koresar** [comment]
It's not done. I believe we should go this path:
* create a GitHub org for `stampit` (done).
* Move stampit there.
* Move the `supermixer` there too (convert to ES6 maybe). A new module name might be necessary.
* Replace the `mixer.js` with the `supermixer`.
* Move `react-stampit` if the author is okay with that.

**Comment by troutowicz** [comment]
> Move the supermixer there too (convert to ES6 maybe). A new module name might be necessary.

Last time I checked, I did this already :p

> Move react-stampit if the author is okay with that.

I created react-stampit for the community, I am OK with this.

**Comment by ericelliott** [comment]
=)

**Comment by koresar** [comment]
I'm working on this now.

**Comment by koresar** [comment]
Done. See https://github.com/stampit-org/supermixer
Used in stampit with PR #107

**Comment by ericelliott** [comment]
Nice.
