### ISSUE TITLE
Cannot create a stamp from an ES6 class

### ISSUE THREAD

**Issue by troutowicz** [stampit-org/stampit#75]
```js
import stampit from 'stampit';
import test from 'tape';

test('stamp from ES6 class', (t) => {
  t.plan(1);

  class Foo {}
  const fooStamp = stampit.convertConstructor(Foo);

  t.ok(
    fooStamp(),
    'should create instance'
  );
});
```

`TypeError: Cannot call a class as a function`

**Comment by ericelliott** [comment]
I don't think we should fix this in the 1.x line, but we should see if it's possible to fix this in the 2.x line.

They're looking at letting you set a custom invoke function if a constructor is called without `new` for ES7, but I'm not sure whether or not you can dynamically add that property to a class outside of the class declaration, so I'm not sure exactly how we'll fix this issue.

**Comment by troutowicz** [comment]
> Yet another reason to avoid the class keyword.

:+1:

**Comment by koresar** [comment]
I've changed the milestone of this issue from 2.0 to 2.1. I'm shifting all v2.0 compatible issues further to speed up stampit v2 release. I suppose this can be implemented in a compatible way. Can it?

**Comment by troutowicz** [comment]
Yeah, the problem here lies with the class spec, if the custom invoke function proposed in ES7 can be added after class declaration, then that would just be an extra step before passing the class into `convertConstructor`.

**Comment by ericelliott** [comment]
This issue is probably not going to get fixed anytime soon -- certainly not with our next minor update. Created 2.x as a "we have no idea when we'll do this" milestone. ;)

**Comment by troutowicz** [comment]
Turns out another part of the class spec makes this difficult. The classes prototype is not enumerable.

I came up with a solution as I was working on a feature for react-stampit. Take a look at this [gist](https://gist.github.com/troutowicz/9d2d994fd3794df0ff7a). The gist uses babel's playground feature for property initializers, use stage 0 when transpiling.

**Comment by koresar** [comment]
Gist is good, I even managed to run in with some modifications. But, could you please post more details to **this** issue? Like post the error, results, erroring line, etc?

**Comment by koresar** [comment]
Moreover, does ES6 support static properties? I heard that only static *methods* are allowed.

**Comment by troutowicz** [comment]
No, as I said above, the gist is using one of babel's playground features for statics. It was really just to make my example simpler.

**Comment by koresar** [comment]
Ok, I was running it locally via `babel-node`. Playground it something we would need to avoid as it is not final. We should consider only final ES decisions. Otherwise, it's just a waste of time and effort.

**Comment by koresar** [comment]
That's a pretty incredible ES6 class workarounds in your gist, btw. How did you manage to find those workarounds? :)

**Comment by troutowicz** [comment]
Never meant to give the idea that I wanted playground features in stampit. :p

I'm not sure what you want detail wise for this bug, more information about the constructor issue is discussed [here](https://github.com/babel/babel/issues/682).

Thanks, it was a mix of trial and error and MDN.

**Comment by koresar** [comment]
Oh, I was under an impression that you've found an obstacle we can't work around. But, actually, you've found a solution. :)

**Comment by rektide** [comment]
> Yet another reason to avoid the class keyword.

And all JavaScript code you might want to consume using it? That's going to get pretty difficulty pretty fast now.

**Comment by koresar** [comment]
To properly implement the `convertConstructor` we would have to support both ES5 classes, babel-transplied classes, and ES6 native classes. As the result stampit will become multy purpose tool, which we don't want very much. Stampit should do single thing and do it good, - namely, compose stamps.

We better create a separate module for the `convertConstructor` utility function. We even have an issue for that: https://github.com/stampit-org/stampit/issues/137

Thoughts?

**Comment by boneskull** [comment]
I'm struggling with wanting to compose from `Map` right now; whatever solves this issue from userland is going to be helpful.  If I can be of assistance, please let me know.

Also, if anyone knows *why* `Map` throws if not called with `new` (or if you can direct me to who might know), I'm all ears.

**Comment by koresar** [comment]
@boneskull http://www.ecma-international.org/ecma-262/6.0/#sec-map-constructor

I'd need your assistance.

**Comment by FredyC** [comment]
I suppose this is no longer valid here since `convertConstructor` is planned to be moved to [stamp-utils](https://github.com/stampit-org/stamp-utils/issues/1) eventually. Feel free to reopen if I've missed something here.

**Comment by ericelliott** [comment]
> if anyone knows why Map throws if not called with new (or if you can direct me to who might know), I'm all ears.

All ES6 constructors throw if you don't call them with `new`.

**Comment by koresar** [comment]
Thanks Daniel.

Btw, Eric is right. The "Promise()" also throws.
