### ISSUE TITLE
ADVANCED_EXAMPLES.md is needed

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#81]
We should create a comprehensive ADVANCED_EXAMPLES.md to showcase stampit powers. The most commonly (re)implemented stamps should be listed. Namely: 
* [x] Cloneable (`instance.clone()`), 
* [x] SelfAware (`instance.getStamp()`), 
* [x] AsyncInitializable (`init()` returns promise which resolves back to instance).
* [x] Hacking around `fixed` and its properties. Especially `.methods`.
* [x] Validate state before function(s) call.
* .. and much more.

**Comment by ericelliott** [comment]
:+1:

**Comment by koresar** [comment]
Done with #109
