### ISSUE TITLE
Scientifically define "stamp"

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#90]
Stamps are different from classic classes and factories. People seem to get confused when they hear of it first (and second, and third) time. It took me half a year to understand the concept in full. I propose to define `stamp` now and put it to the Wikipedia. No jokes.

The definition **must** be: short, easy to understand (like be based on widely known concepts and avoid using not widely known concepts).

My 5 cents:
> Stamp is a factory function with an ability to compose with other stamps. Ability to combine fields, methods, and initializers (object initialization behaviours) to a single stamp is the main difference to factories and classes: classic class inheritance is substituted with simple composition, classic factories can't be combined.

I like this because: the wording is short, it uses classes and factories to showcase the difference from the existing concepts.

Although, @ericelliott should have better wording I reckon. The one we have [in the README now](https://github.com/ericelliott/stampit#what-is-a-stamp) is lacking details.

Suggestions?

**Comment by troutowicz** [comment]
Made a few changes to your summary.

>A stamp is a factory function with an ability to compose with other stamps. The ability to combine fields, methods, and initializers (object initialization behaviors) to create a new stamp is what sets stamps apart from the typical factories or classes. Classic factories can not be combined, and classic class inheritance is substituted with simple composition.

**Comment by ericelliott** [comment]
How's this?

A stamp is a composable factory function. Stamps allow you to combine properties, methods, and initializers (with closures) from any number of stamps to produce a new stamp. Traditional factory functions can't be composed together to produce new factory functions. Class inheritance does not provide a standardized mechanism for class composition.

Stamp composition takes advantage of three different kinds of prototypal inheritance:

* Differential inheritance, aka delegation (e.g., JavaScript's [[Prototype]]),
* Mixins/cloning with optional deep merge, aka concatenative inheritance (e.g., JavaScript's `Object.assign()`),
* Functional / closure inheritance (for initialization or privacy / encapsulation)

**Comment by koresar** [comment]
Same length but better *composed*. I'll put that to Wikipedia later today (with some history backround of course). I'll share the link here for your further editions.

**Comment by ericelliott** [comment]
^^ I added quite a bit more detail. ^^ Is that better?

**Comment by koresar** [comment]
That's perfect for our README. But lacking some wikipedia-like seriousness. Wikipedia example: http://en.wikipedia.org/wiki/Liskov_substitution_principle

**Comment by ericelliott** [comment]
Yeah, I think it's important to get the README right first. We can take another pass and fix the tone for Wikipedia. I don't have time to do a tone edit right now, though. =)

**Comment by koresar** [comment]
All good. Thanks.

**Comment by koresar** [comment]
@ericelliott , you'd like to edit this one I reckon. :)
https://en.wikipedia.org/wiki/Stamp_(object-oriented_programming)

**Comment by koresar** [comment]
I believe this sentence requires more details:
>Traditional factory functions can't be composed together to produce new factory functions.

Because there is https://en.wikipedia.org/wiki/Function_composition concept.

**Comment by koresar** [comment]
Ok. Seems like the page is up. We might want to give a link to it on our README.

**Comment by koresar** [comment]
I'll copy&paste wikipedia article contents in here just for future reference in any.

```

In [[object-oriented programming]], a '''stamp''' is a composable [[factory (object-oriented programming)|factory function]] (not to be confused with [[function composition]]). Stamps allows [[inheritance (object-oriented programming)|inheritance]] from multiple ancestors by [[object composition|composing]] multiple source stamps. Technically, they allow to combine properties, methods, and initializers (with [[closure (computer programming)|closures]]) from any number of stamps to produce a new stamp.

==Motivation==
Stamps are more flexible than traditional factory functions or classical multiple [[inheritance (object-oriented programming)|inheritance]]. Traditional factory functions can't be composed together to produce new factory functions. [[class (computer programming)|Class]] inheritance does not provide a standardized mechanism for class composition.

Stamp composition takes advantage of three different kinds of [[Prototype-based programming|prototypal inheritance]]:

* Differential inheritance, aka delegation (e.g., JavaScript's [[JavaScript#Prototype-based|Prototype]]),
* [[Mixin]]s/cloning with optional deep merge, as known as concatenative inheritance (e.g., JavaScript's Object.assign()),
* Functional / closure inheritance (for initialization or privacy/encapsulation)

===Difference from Classes===
* It's easy to compose (see [[composition over inheritance]]) multiple stamps to create a new stamp with all of the source stamp capabilities 
* Stamps are factory functions, so they don't need to be invoked with the ''new'' [[Reserved word|keyword]] (which couples callers to the implementation of object instantiation)
* Stamps don't create parent-child class hierarchies. Class hierarchies create "is-a" relationships between classes. Stamp composition creates "has-a" or "uses-a" relationships, instead. For that reason, stamp inheritance is less brittle than class inheritance.

==History==
The word '''stamp''' for computer programming was [http://chimera.labs.oreilly.com/books/1234000000262/ch03.html#prototypal_inheritance_with_stamps originally used] by Eric Elliott in his book, "Programming JavaScript Applications" in 2013 and propagated via the Stampit JavaScript library. The concept started gaining wide popularity in 2015.{{Citation needed|date=June 2015}}

[[Category:Object-oriented programming]]
[[Category:Programming principles]]
```

**Comment by koresar** [comment]
Closing this issue as done. See text in the previous comment.
And let's hope wikipedia moderators won't remove it https://en.wikipedia.org/wiki/Stamp_(object-oriented_programming)

**Comment by ericelliott** [comment]
If we want the Wikipedia article to remain, we need to find some credible third-party sources discussing stamps. I know of a couple slide shows, but nothing credible that I didn't have a direct hand in creating. (Multiple sources by the same author are considered the same source by Wikipedia).

**Comment by koresar** [comment]
We can point to the two **functional mixins** articles and reddit discussions. What do you reckon?
