### ISSUE TITLE
Bring Stampit 2.x up to modern coding standards

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stampit#91]
* [x] Convert to ES6
* [x] Add automatic validation in precommit and prepublish
* [x] Add other useful scripts

See [prod-module-boilerplate](https://github.com/ericelliott/prod-module-boilerplate) and [a real example](https://github.com/ericelliott/irecord).

**Comment by koresar** [comment]
@troutowicz Take the first one! :)

**Comment by ericelliott** [comment]
@troutowicz You might like that real example link. Click it. =)

**Comment by troutowicz** [comment]
I'll take the first one. \o/

@ericelliott Looks like I need to take a crash course in RP ;)

**Comment by ericelliott** [comment]
## Learn about Reactive Programming

### Video

* [Asynchronous Programming at Netflix](https://www.youtube.com/watch?v=gawmdhCNy-A) [Jafar Husain](https://twitter.com/jhusain)
* [What is Reactive Programming?](https://www.youtube.com/watch?v=dwP1TNXE6fc) [Jafar Husain](https://twitter.com/jhusain) explains reactive programming
* [Immutability: Putting The Dream Machine To Work](https://www.youtube.com/watch?v=SiFwRtCnxv4) by [David Nolen](https://twitter.com/swannodette)

### Reading

* [Introduction to Reactive Programming](https://gist.github.com/staltz/868e7e9bc2a7b8c1f754)
* [The Dao of Immutability](https://medium.com/javascript-scene/the-dao-of-immutability-9f91a70c88cd) The Way of the Functional Programmer
* [The General Theory of Reactivity](https://github.com/kriskowal/gtor) What is all this talk about reactive? Functional? Promises? This is the beginning of a reactive programming bible.
* [Reactive MVC and the Virtual DOM](http://futurice.com/blog/reactive-mvc-and-the-virtual-dom) Great read, even if you're not a React user.

**Comment by tropet123456** [comment]
Is it possible to get this new version (v2) from Bower? and How?

**Comment by koresar** [comment]
The only way to get the buggy v2 is to clone the repository. It's the
current master branch.

**Comment by koresar** [comment]
@troutowicz It's the time. You can start converting stampit to ES6.

Please take a look at the link above: https://github.com/ericelliott/prod-module-boilerplate
The approach there suits us perfectly, IMO. Don't hesitate to strip parts you think we don't need. :)

**Comment by troutowicz** [comment]
:grinning: Should be able to start this over the weekend.

**Comment by ericelliott** [comment]
Nice.

**Comment by koresar** [comment]
Useful scripts will be added with #116
Some were already added with #123 

Closing this issue as outdated.
